/*
 * Copyright (c) 2017, Adam <Adam@sigterm.info>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package net.runelite.api;

public enum Prayer
{
	THICK_SKIN(Varbits.PRAYER_THICK_SKIN),
	BURST_OF_STRENGTH(Varbits.PRAYER_BURST_OF_STRENGTH),
	CLARITY_OF_THOUGHT(Varbits.PRAYER_CLARITY_OF_THOUGHT),
	SHARP_EYE(Varbits.PRAYER_SHARP_EYE),
	MYSTIC_WILL(Varbits.PRAYER_MYSTIC_WILL),
	ROCK_SKIN(Varbits.PRAYER_ROCK_SKIN),
	SUPERHUMAN_STRENGTH(Varbits.PRAYER_SUPERHUMAN_STRENGTH),
	IMPROVED_REFLEXES(Varbits.PRAYER_IMPROVED_REFLEXES),
	RAPID_RESTORE(Varbits.PRAYER_RAPID_RESTORE),
	RAPID_HEAL(Varbits.PRAYER_RAPID_HEAL),
	PROTECT_ITEM(Varbits.PRAYER_PROTECT_ITEM),
	HAWK_EYE(Varbits.PRAYER_HAWK_EYE),
	MYSTIC_LORE(Varbits.PRAYER_MYSTIC_LORE),
	STEEL_SKIN(Varbits.PRAYER_STEEL_SKIN),
	ULTIMATE_STRENGTH(Varbits.PRAYER_ULTIMATE_STRENGTH),
	INCREDIBLE_REFLEXES(Varbits.PRAYER_INCREDIBLE_REFLEXES),
	PROTECT_FROM_MAGIC(Varbits.PRAYER_PROTECT_FROM_MAGIC),
	PROTECT_FROM_MISSILES(Varbits.PRAYER_PROTECT_FROM_MISSILES),
	PROTECT_FROM_MELEE(Varbits.PRAYER_PROTECT_FROM_MELEE),
	EAGLE_EYE(Varbits.PRAYER_EAGLE_EYE),
	MYSTIC_MIGHT(Varbits.PRAYER_MYSTIC_MIGHT),
	RETRIBUTION(Varbits.PRAYER_RETRIBUTION),
	REDEMPTION(Varbits.PRAYER_REDEMPTION),
	SMITE(Varbits.PRAYER_SMITE),
	CHIVALRY(Varbits.PRAYER_CHIVALRY),
	PIETY(Varbits.PRAYER_PIETY),
	PRESERVE(Varbits.PRAYER_PRESERVE),
	RIGOUR(Varbits.PRAYER_RIGOUR),
	AUGURY(Varbits.PRAYER_AUGURY);
	
	private final Varbits varbit;

	private Prayer(Varbits varbit)
	{
		this.varbit = varbit;
	}

	public Varbits getVarbit()
	{
		return varbit;
	}
}
