/*
 * Copyright (c) 2018, Lotto <https://github.com/devLotto>
 * Copyright (c) 2018, Raqes <j.raqes@gmail.com>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package net.runelite.client.plugins.uicustomizer;

import lombok.AllArgsConstructor;
import lombok.Getter;
import net.runelite.api.SpriteID;
import static net.runelite.client.plugins.uicustomizer.Skin.AROUND_2005;
import static net.runelite.client.plugins.uicustomizer.Skin.AROUND_2010;

@AllArgsConstructor
@Getter
public enum SpriteOverride
{
	TAB_COMBAT_2005(AROUND_2005, SpriteID.TAB_COMBAT),
	TAB_STATS_2005(AROUND_2005, SpriteID.TAB_STATS),
	TAB_QUESTS_2005(AROUND_2005, SpriteID.TAB_QUESTS),
	TAB_QUESTS_PURPLE_KOUREND_1299_2005(AROUND_2005, SpriteID.TAB_QUESTS_PURPLE_KOUREND_1299),
	TAB_QUESTS_RED_MINIGAMES_2005(AROUND_2005, SpriteID.TAB_QUESTS_RED_MINIGAMES),
	TAB_QUESTS_GREEN_ACHIEVEMENT_DIARIES_2005(AROUND_2005, SpriteID.TAB_QUESTS_GREEN_ACHIEVEMENT_DIARIES),
	TAB_INVENTORY_2005(AROUND_2005, SpriteID.TAB_INVENTORY),
	TAB_EQUIPMENT_2005(AROUND_2005, SpriteID.TAB_EQUIPMENT),
	TAB_PRAYER_2005(AROUND_2005, SpriteID.TAB_PRAYER),
	TAB_MAGIC_2005(AROUND_2005, SpriteID.TAB_MAGIC),
	TAB_CLAN_CHAT_2005(AROUND_2005, SpriteID.TAB_CLAN_CHAT),
	TAB_FRIENDS_2005(AROUND_2005, SpriteID.TAB_FRIENDS),
	TAB_IGNORES_2005(AROUND_2005, SpriteID.TAB_IGNORES),
	TAB_LOGOUT_2005(AROUND_2005, SpriteID.TAB_LOGOUT),
	TAB_OPTIONS_2005(AROUND_2005, SpriteID.TAB_OPTIONS),
	TAB_EMOTES_2005(AROUND_2005, SpriteID.TAB_EMOTES),
	TAB_MUSIC_2005(AROUND_2005, SpriteID.TAB_MUSIC),

	SKILL_PRAYER_2005(AROUND_2005, SpriteID.SKILL_PRAYER),

	COMPASS_2005(AROUND_2005, SpriteID.COMPASS_TEXTURE),
	CHATBOX_2005(AROUND_2005, SpriteID.CHATBOX),
	CHATBOX_BUTTONS_BACKGROUND_STONES_2005(AROUND_2005, SpriteID.CHATBOX_BUTTONS_BACKGROUND_STONES),
	CHATBOX_BUTTON_2005(AROUND_2005, SpriteID.CHATBOX_BUTTON),
	CHATBOX_BUTTON_HOVERED_2005(AROUND_2005, SpriteID.CHATBOX_BUTTON_HOVERED),
	CHATBOX_BUTTON_NEW_MESSAGES_2005(AROUND_2005, SpriteID.CHATBOX_BUTTON_NEW_MESSAGES),
	CHATBOX_BUTTON_SELECTED_2005(AROUND_2005, SpriteID.CHATBOX_BUTTON_SELECTED),
	CHATBOX_BUTTON_SELECTED_HOVERED_2005(AROUND_2005, SpriteID.CHATBOX_BUTTON_SELECTED_HOVERED),
	CHATBOX_REPORT_BUTTON_2005(AROUND_2005, SpriteID.CHATBOX_REPORT_BUTTON),
	CHATBOX_REPORT_BUTTON_HOVERED_2005(AROUND_2005, SpriteID.CHATBOX_REPORT_BUTTON_HOVERED),
	FIXED_MODE_SIDE_PANEL_BACKGROUND_2005(AROUND_2005, SpriteID.FIXED_MODE_SIDE_PANEL_BACKGROUND),
	FIXED_MODE_TABS_ROW_BOTTOM_2005(AROUND_2005, SpriteID.FIXED_MODE_TABS_ROW_BOTTOM),
	OLD_SCHOOl_MODE_SIDE_PANEL_EDGE_LEFT_UPPER_2005(AROUND_2005, SpriteID.OLD_SCHOOl_MODE_SIDE_PANEL_EDGE_LEFT_UPPER),
	OLD_SCHOOl_MODE_SIDE_PANEL_EDGE_LEFT_LOWER_2005(AROUND_2005, SpriteID.OLD_SCHOOl_MODE_SIDE_PANEL_EDGE_LEFT_LOWER),
	OLD_SCHOOl_MODE_SIDE_PANEL_EDGE_RIGHT_2005(AROUND_2005, SpriteID.OLD_SCHOOl_MODE_SIDE_PANEL_EDGE_RIGHT),
	FIXED_MODE_TABS_TOP_ROW_2005(AROUND_2005, SpriteID.FIXED_MODE_TABS_TOP_ROW),
	FIXED_MODE_MINIMAP_LEFT_EDGE_2005(AROUND_2005, SpriteID.FIXED_MODE_MINIMAP_LEFT_EDGE),
	FIXED_MODE_MINIMAP_RIGHT_EDGE_2005(AROUND_2005, SpriteID.FIXED_MODE_MINIMAP_RIGHT_EDGE),
	FIXED_MODE_WINDOW_FRAME_EDGE_TOP_2005(AROUND_2005, SpriteID.FIXED_MODE_WINDOW_FRAME_EDGE_TOP),
	FIXED_MODE_MINIMAP_AND_COMPASS_FRAME_2005(AROUND_2005, SpriteID.FIXED_MODE_MINIMAP_AND_COMPASS_FRAME),
	UNKNOWN_1441_2005(AROUND_2005, SpriteID.UNKNOWN_1441),
	FIXED_MODE_MINIMAP_FRAME_BOTTOM(AROUND_2005, SpriteID.FIXED_MODE_MINIMAP_FRAME_BOTTOM),

	TAB_COMBAT_2010(AROUND_2010, SpriteID.TAB_COMBAT),
	TAB_STATS_2010(AROUND_2010, SpriteID.TAB_STATS),
	TAB_EQUIPMENT_2010(AROUND_2010, SpriteID.TAB_EQUIPMENT),
	TAB_INVENTORY_2010(AROUND_2010, SpriteID.TAB_INVENTORY),
	TAB_PRAYER_2010(AROUND_2010, SpriteID.TAB_PRAYER),
	TAB_MAGIC_2010(AROUND_2010, SpriteID.TAB_MAGIC),
	TAB_CLAN_CHAT_2010(AROUND_2010, SpriteID.TAB_CLAN_CHAT),
	TAB_FRIENDS_2010(AROUND_2010, SpriteID.TAB_FRIENDS),
	TAB_IGNORES_2010(AROUND_2010, SpriteID.TAB_IGNORES),
	TAB_LOGOUT_2010(AROUND_2010, SpriteID.TAB_LOGOUT),
	TAB_OPTIONS_2010(AROUND_2010, SpriteID.TAB_OPTIONS),
	TAB_EMOTES_2010(AROUND_2010, SpriteID.TAB_EMOTES),
	TAB_MUSIC_2010(AROUND_2010, SpriteID.TAB_MUSIC),

	SKILL_ATTACK_2010(AROUND_2010, SpriteID.SKILL_ATTACK),
	SKILL_STRENGTH_2010(AROUND_2010, SpriteID.SKILL_STRENGTH),
	SKILL_DEFENCE_2010(AROUND_2010, SpriteID.SKILL_DEFENCE),
	SKILL_RANGED_2010(AROUND_2010, SpriteID.SKILL_RANGED),
	SKILL_PRAYER_2010(AROUND_2010, SpriteID.SKILL_PRAYER),
	SKILL_MAGIC_2010(AROUND_2010, SpriteID.SKILL_MAGIC),
	SKILL_HITPOINTS_2010(AROUND_2010, SpriteID.SKILL_HITPOINTS),
	SKILL_AGILITY_2010(AROUND_2010, SpriteID.SKILL_AGILITY),
	SKILL_HERBLORE_2010(AROUND_2010, SpriteID.SKILL_HERBLORE),
	SKILL_THIEVING_2010(AROUND_2010, SpriteID.SKILL_THIEVING),
	SKILL_CRAFTING_2010(AROUND_2010, SpriteID.SKILL_CRAFTING),
	SKILL_FLETCHING_2010(AROUND_2010, SpriteID.SKILL_FLETCHING),
	SKILL_MINING_2010(AROUND_2010, SpriteID.SKILL_MINING),
	SKILL_SMITHING_2010(AROUND_2010, SpriteID.SKILL_SMITHING),
	SKILL_FISHING_2010(AROUND_2010, SpriteID.SKILL_FISHING),
	SKILL_COOKING_2010(AROUND_2010, SpriteID.SKILL_COOKING),
	SKILL_FIREMAKING_2010(AROUND_2010, SpriteID.SKILL_FIREMAKING),
	SKILL_WOODCUTTING_2010(AROUND_2010, SpriteID.SKILL_WOODCUTTING),
	SKILL_RUNECRAFT_2010(AROUND_2010, SpriteID.SKILL_RUNECRAFT),
	SKILL_SLAYER_2010(AROUND_2010, SpriteID.SKILL_SLAYER),
	SKILL_HUNTER_2010(AROUND_2010, SpriteID.SKILL_HUNTER),
	SKILL_CONSTRUCTION_2010(AROUND_2010, SpriteID.SKILL_CONSTRUCTION),

	WINDOW_CLOSE_BUTTON_BROWN_X_HOVERED(AROUND_2010, SpriteID.WINDOW_CLOSE_BUTTON_BROWN_X_HOVERED),
	TAB_STONE_TOP_LEFT_SELECTED_2010(AROUND_2010, SpriteID.TAB_STONE_TOP_LEFT_SELECTED),
	TAB_STONE_TOP_RIGHT_SELECTED_2010(AROUND_2010, SpriteID.TAB_STONE_TOP_RIGHT_SELECTED),
	TAB_STONE_BOTTOM_LEFT_SELECTED_2010(AROUND_2010, SpriteID.TAB_STONE_BOTTOM_LEFT_SELECTED),
	TAB_STONE_BOTTOM_RIGHT_SELECTED_2010(AROUND_2010, SpriteID.TAB_STONE_BOTTOM_RIGHT_SELECTED),
	TAB_STONE_MIDDLE_SELECTED(AROUND_2010, SpriteID.TAB_STONE_MIDDLE_SELECTED),
	FIXED_MODE_TABS_ROW_BOTTOM_2010(AROUND_2010, SpriteID.FIXED_MODE_TABS_ROW_BOTTOM),
	OLD_SCHOOl_MODE_SIDE_PANEL_EDGE_LEFT_UPPER_2010(AROUND_2010, SpriteID.OLD_SCHOOl_MODE_SIDE_PANEL_EDGE_LEFT_UPPER),
	OLD_SCHOOl_MODE_SIDE_PANEL_EDGE_LEFT_LOWER_2010(AROUND_2010, SpriteID.OLD_SCHOOl_MODE_SIDE_PANEL_EDGE_LEFT_LOWER),
	OLD_SCHOOl_MODE_SIDE_PANEL_EDGE_RIGHT_2010(AROUND_2010, SpriteID.OLD_SCHOOl_MODE_SIDE_PANEL_EDGE_RIGHT),
	FIXED_MODE_TABS_TOP_ROW_2010(AROUND_2010, SpriteID.FIXED_MODE_TABS_TOP_ROW),
	FIXED_MODE_MINIMAP_LEFT_EDGE_2010(AROUND_2010, SpriteID.FIXED_MODE_MINIMAP_LEFT_EDGE),
	FIXED_MODE_MINIMAP_RIGHT_EDGE_2010(AROUND_2010, SpriteID.FIXED_MODE_MINIMAP_RIGHT_EDGE),
	FIXED_MODE_WINDOW_FRAME_EDGE_TOP_2010(AROUND_2010, SpriteID.FIXED_MODE_WINDOW_FRAME_EDGE_TOP),
	MINIMAP_ORB_FRAME_2010(AROUND_2010, SpriteID.MINIMAP_ORB_FRAME),
	MINIMAP_ORB_FRAME_HOVERED_2010(AROUND_2010, SpriteID.MINIMAP_ORB_FRAME_HOVERED),
	RESIZEABLE_MODE_TABS_TOP_ROW_2010(AROUND_2010, SpriteID.RESIZEABLE_MODE_TABS_TOP_ROW),
	RESIZEABLE_MODE_TABS_BOTTOM_ROW_2010(AROUND_2010, SpriteID.RESIZEABLE_MODE_TABS_BOTTOM_ROW),
	RESIZEABLE_MODE_SIDE_PANEL_EDGE_LEFT_2010(AROUND_2010, SpriteID.RESIZEABLE_MODE_SIDE_PANEL_EDGE_LEFT),
	RESIZEABLE_MODE_SIDE_PANEL_EDGE_RIGHT_2010(AROUND_2010, SpriteID.RESIZEABLE_MODE_SIDE_PANEL_EDGE_RIGHT),
	RESIZEABLE_MODE_MINIMAP_AND_COMPASS_FRAME_2010(AROUND_2010, SpriteID.RESIZEABLE_MODE_MINIMAP_AND_COMPASS_FRAME),
	RESIZEABLE_MODE_TAB_STONE_MIDDLE_2010(AROUND_2010, SpriteID.RESIZEABLE_MODE_TAB_STONE_MIDDLE),
	RESIZEABLE_MODE_TAB_STONE_MIDDLE_SELECTED_2010(AROUND_2010, SpriteID.RESIZEABLE_MODE_TAB_STONE_MIDDLE_SELECTED),
	FIXED_MODE_MINIMAP_AND_COMPASS_FRAME_2010(AROUND_2010, SpriteID.FIXED_MODE_MINIMAP_AND_COMPASS_FRAME),
	MINIMAP_ORB_XP_2010(AROUND_2010, SpriteID.MINIMAP_ORB_XP),
	MINIMAP_ORB_XP_ACTIVATED_2010(AROUND_2010, SpriteID.MINIMAP_ORB_XP_ACTIVATED),
	MINIMAP_ORB_XP_HOVERED_2010(AROUND_2010, SpriteID.MINIMAP_ORB_XP_HOVERED),
	MINIMAP_ORB_XP_ACTIVATED_HOVERED_2010(AROUND_2010, SpriteID.MINIMAP_ORB_XP_ACTIVATED_HOVERED),
	MINIMAP_ORB_WORLD_MAP_FRAME_2010(AROUND_2010, SpriteID.MINIMAP_ORB_WORLD_MAP_FRAME),
	MINIMAP_ORB_WORLD_MAP_PLANET_2010(AROUND_2010, SpriteID.MINIMAP_ORB_WORLD_MAP_PLANET);

	private Skin skin;
	private int spriteID;
}
