import net.runelite.mapping.Export;
import net.runelite.mapping.ObfuscatedName;
import net.runelite.mapping.ObfuscatedSignature;

@ObfuscatedName("h")
public class class1 {
   @ObfuscatedName("x")
   @ObfuscatedSignature(
      signature = "(II)V",
      garbageValue = "1061968713"
   )
   static void method4(int var0) {
      if(var0 == -3) {
         class5.method88("Connection timed out.", "Please try using a different world.", "");
      } else if(var0 == -2) {
         class5.method88("", "Error connecting to server.", "");
      } else if(var0 == -1) {
         class5.method88("No response from server.", "Please try using a different world.", "");
      } else if(var0 == 3) {
         class33.loginIndex = 3;
      } else if(var0 == 4) {
         class5.method88("Your account has been disabled.", "Please check your message-centre for details.", "");
      } else if(var0 == 5) {
         class5.method88("Your account is already logged in.", "Try again in 60 secs...", "");
      } else if(var0 == 6) {
         class5.method88("RuneScape has been updated!", "Please reload this page.", "");
      } else if(var0 == 7) {
         class5.method88("This world is full.", "Please use a different world.", "");
      } else if(var0 == 8) {
         class5.method88("Unable to connect.", "Login server offline.", "");
      } else if(var0 == 9) {
         class5.method88("Login limit exceeded.", "Too many connections from your address.", "");
      } else if(var0 == 10) {
         class5.method88("Unable to connect.", "Bad session id.", "");
      } else if(var0 == 11) {
         class5.method88("We suspect someone knows your password.", "Press \'change your password\' on front page.", "");
      } else if(var0 == 12) {
         class5.method88("You need a members account to login to this world.", "Please subscribe, or use a different world.", "");
      } else if(var0 == 13) {
         class5.method88("Could not complete login.", "Please try using a different world.", "");
      } else if(var0 == 14) {
         class5.method88("The server is being updated.", "Please wait 1 minute and try again.", "");
      } else if(var0 == 16) {
         class5.method88("Too many login attempts.", "Please wait a few minutes before trying again.", "");
      } else if(var0 == 17) {
         class5.method88("You are standing in a members-only area.", "To play on this world move to a free area first", "");
      } else if(var0 == 18) {
         class5.method88("Account locked as we suspect it has been stolen.", "Press \'recover a locked account\' on front page.", "");
      } else if(var0 == 19) {
         class5.method88("This world is running a closed Beta.", "Sorry invited players only.", "Please use a different world.");
      } else if(var0 == 20) {
         class5.method88("Invalid loginserver requested.", "Please try using a different world.", "");
      } else if(var0 == 22) {
         class5.method88("Malformed login packet.", "Please try again.", "");
      } else if(var0 == 23) {
         class5.method88("No reply from loginserver.", "Please wait 1 minute and try again.", "");
      } else if(var0 == 24) {
         class5.method88("Error loading your profile.", "Please contact customer support.", "");
      } else if(var0 == 25) {
         class5.method88("Unexpected loginserver response.", "Please try using a different world.", "");
      } else if(var0 == 26) {
         class5.method88("This computers address has been blocked", "as it was used to break our rules.", "");
      } else if(var0 == 27) {
         class5.method88("", "Service unavailable.", "");
      } else if(var0 == 31) {
         class5.method88("Your account must have a displayname set", "in order to play the game.  Please set it", "via the website, or the main game.");
      } else if(var0 == 32) {
         class5.method88("Your attempt to log into your account was", "unsuccessful.  Don\'t worry, you can sort", "this out by visiting the billing system.");
      } else if(var0 == 37) {
         class5.method88("Your account is currently inaccessible.", "Please try again in a few minutes.", "");
      } else if(var0 == 38) {
         class5.method88("You need to vote to play!", "Visit runescape.com and vote,", "and then come back here!");
      } else if(var0 == 55) {
         class5.method88("Sorry, but your account is not eligible to", "play this version of the game.  Please try", "playing the main game instead!");
      } else {
         if(var0 == 56) {
            class5.method88("Enter the 6-digit code generated by your", "authenticator app.", "");
            class117.setGameState(11);
            return;
         }

         if(var0 == 57) {
            class5.method88("The code you entered was incorrect.", "Please try again.", "");
            class117.setGameState(11);
            return;
         }

         class5.method88("Unexpected server response", "Please try using a different world.", "");
      }

      class117.setGameState(10);
   }

   @ObfuscatedName("i")
   @ObfuscatedSignature(
      signature = "(B)[Lclass133;",
      garbageValue = "64"
   )
   public static class133[] method9() {
      return new class133[]{class133.field2110, class133.field2111, class133.field2113};
   }

   @ObfuscatedName("i")
   @ObfuscatedSignature(
      signature = "(IB)LKitDefinition;",
      garbageValue = "-8"
   )
   @Export("getKitDefinition")
   public static KitDefinition getKitDefinition(int var0) {
      KitDefinition var1 = (KitDefinition)KitDefinition.field1047.get((long)var0);
      if(var1 != null) {
         return var1;
      } else {
         byte[] var2 = KitDefinition.field1054.method3292(3, var0);
         var1 = new KitDefinition();
         if(null != var2) {
            var1.method958(new Buffer(var2));
         }

         KitDefinition.field1047.put(var1, (long)var0);
         return var1;
      }
   }

   @ObfuscatedName("cr")
   @ObfuscatedSignature(
      signature = "(IIIIII)V",
      garbageValue = "-2095861584"
   )
   static final void method12(int var0, int var1, int var2, int var3, int var4) {
      class222.field3222[0].method1905(var0, var1);
      class222.field3222[1].method1905(var0, var3 + var1 - 16);
      class82.method1853(var0, var1 + 16, 16, var3 - 32, Client.field380);
      int var5 = var3 * (var3 - 32) / var4;
      if(var5 < 8) {
         var5 = 8;
      }

      int var6 = var2 * (var3 - 32 - var5) / (var4 - var3);
      class82.method1853(var0, var1 + 16 + var6, 16, var5, Client.field381);
      class82.method1845(var0, var1 + 16 + var6, var5, Client.field383);
      class82.method1845(var0 + 1, var6 + 16 + var1, var5, Client.field383);
      class82.method1879(var0, 16 + var1 + var6, 16, Client.field383);
      class82.method1879(var0, 17 + var1 + var6, 16, Client.field383);
      class82.method1845(15 + var0, var6 + 16 + var1, var5, Client.field382);
      class82.method1845(14 + var0, 17 + var1 + var6, var5 - 1, Client.field382);
      class82.method1879(var0, var5 + 15 + var1 + var6, 16, Client.field382);
      class82.method1879(1 + var0, var5 + var6 + var1 + 14, 15, Client.field382);
   }

   @ObfuscatedName("h")
   @ObfuscatedSignature(
      signature = "(Lclass170;III)LSpritePixels;",
      garbageValue = "-1602096460"
   )
   public static SpritePixels method13(class170 var0, int var1, int var2) {
      return !class22.method559(var0, var1, var2)?null:class20.method529();
   }
}
