import net.runelite.mapping.Export;
import net.runelite.mapping.ObfuscatedName;
import net.runelite.mapping.ObfuscatedSignature;

@ObfuscatedName("fc")
public class class162 implements class161 {
	@ObfuscatedName("dm")
	@ObfuscatedSignature(
		signature = "Lij;"
	)
	@Export("archive14")
	static Archive archive14;

	@ObfuscatedName("fm")
	@ObfuscatedSignature(
		signature = "(IB)V",
		garbageValue = "45"
	)
	@Export("getLoginError")
	static void getLoginError(int var0) {
		if (var0 == -3) {
			PacketWriter.setLoginResponseString("Connection timed out.", "Please try using a different world.", "");
		} else if (var0 == -2) {
			PacketWriter.setLoginResponseString("Error connecting to server.", "Please try using a different world.", "");
		} else if (var0 == -1) {
			PacketWriter.setLoginResponseString("No response from server.", "Please try using a different world.", "");
		} else if (var0 == 3) {
			Login.loginIndex = 3;
			Login.field1186 = 1;
		} else if (var0 == 4) {
			Login.loginIndex = 12;
			Login.field1185 = 0;
		} else if (var0 == 5) {
			Login.field1186 = 2;
			PacketWriter.setLoginResponseString("Your account has not logged out from its last", "session or the server is too busy right now.", "Please try again in a few minutes.");
		} else if (var0 == 68 || !Client.onMobile && var0 == 6) {
			PacketWriter.setLoginResponseString("RuneScape has been updated!", "Please reload this page.", "");
		} else if (var0 == 7) {
			PacketWriter.setLoginResponseString("This world is full.", "Please use a different world.", "");
		} else if (var0 == 8) {
			PacketWriter.setLoginResponseString("Unable to connect.", "Login server offline.", "");
		} else if (var0 == 9) {
			PacketWriter.setLoginResponseString("Login limit exceeded.", "Too many connections from your address.", "");
		} else if (var0 == 10) {
			PacketWriter.setLoginResponseString("Unable to connect.", "Bad session id.", "");
		} else if (var0 == 11) {
			PacketWriter.setLoginResponseString("We suspect someone knows your password.", "Press 'change your password' on front page.", "");
		} else if (var0 == 12) {
			PacketWriter.setLoginResponseString("You need a members account to login to this world.", "Please subscribe, or use a different world.", "");
		} else if (var0 == 13) {
			PacketWriter.setLoginResponseString("Could not complete login.", "Please try using a different world.", "");
		} else if (var0 == 14) {
			PacketWriter.setLoginResponseString("The server is being updated.", "Please wait 1 minute and try again.", "");
		} else if (var0 == 16) {
			PacketWriter.setLoginResponseString("Too many login attempts.", "Please wait a few minutes before trying again.", "");
		} else if (var0 == 17) {
			PacketWriter.setLoginResponseString("You are standing in a members-only area.", "To play on this world move to a free area first", "");
		} else if (var0 == 18) {
			Login.loginIndex = 12;
			Login.field1185 = 1;
		} else if (var0 == 19) {
			PacketWriter.setLoginResponseString("This world is running a closed Beta.", "Sorry invited players only.", "Please use a different world.");
		} else if (var0 == 20) {
			PacketWriter.setLoginResponseString("Invalid loginserver requested.", "Please try using a different world.", "");
		} else if (var0 == 22) {
			PacketWriter.setLoginResponseString("Malformed login packet.", "Please try again.", "");
		} else if (var0 == 23) {
			PacketWriter.setLoginResponseString("No reply from loginserver.", "Please wait 1 minute and try again.", "");
		} else if (var0 == 24) {
			PacketWriter.setLoginResponseString("Error loading your profile.", "Please contact customer support.", "");
		} else if (var0 == 25) {
			PacketWriter.setLoginResponseString("Unexpected loginserver response.", "Please try using a different world.", "");
		} else if (var0 == 26) {
			PacketWriter.setLoginResponseString("This computers address has been blocked", "as it was used to break our rules.", "");
		} else if (var0 == 27) {
			PacketWriter.setLoginResponseString("", "Service unavailable.", "");
		} else if (var0 == 31) {
			PacketWriter.setLoginResponseString("Your account must have a displayname set", "in order to play the game.  Please set it", "via the website, or the main game.");
		} else if (var0 == 32) {
			PacketWriter.setLoginResponseString("Your attempt to log into your account was", "unsuccessful.  Don't worry, you can sort", "this out by visiting the billing system.");
		} else if (var0 == 37) {
			PacketWriter.setLoginResponseString("Your account is currently inaccessible.", "Please try again in a few minutes.", "");
		} else if (var0 == 38) {
			PacketWriter.setLoginResponseString("You need to vote to play!", "Visit runescape.com and vote,", "and then come back here!");
		} else if (var0 == 55) {
			Login.loginIndex = 8;
		} else {
			if (var0 == 56) {
				PacketWriter.setLoginResponseString("Enter the 6-digit code generated by your", "authenticator app.", "");
				class81.updateGameState(11);
				return;
			}

			if (var0 == 57) {
				PacketWriter.setLoginResponseString("The code you entered was incorrect.", "Please try again.", "");
				class81.updateGameState(11);
				return;
			}

			if (var0 == 61) {
				Login.loginIndex = 7;
			} else {
				PacketWriter.setLoginResponseString("Unexpected server response", "Please try using a different world.", "");
			}
		}

		class81.updateGameState(10);
	}
}
