/*
 * Copyright (c) 2018, Raqes <j.raqes@gmail.com>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package net.runelite.client.plugins.specialcounter;

import com.google.common.collect.Sets;
import java.util.Set;
import lombok.Getter;
import lombok.ToString;
import net.runelite.api.NpcID;

@Getter
@ToString
enum Boss
{
	ABERRANT_SPECTRE(1d, NpcID.ABERRANT_SPECTRE),
	ABYSSAL_DEMON(1d, NpcID.ABYSSAL_DEMON),
	ABYSSAL_SIRE(1.25d, NpcID.ABYSSAL_SIRE, NpcID.ABYSSAL_SIRE_5887, NpcID.ABYSSAL_SIRE_5888, NpcID.ABYSSAL_SIRE_5889, NpcID.ABYSSAL_SIRE_5890, NpcID.ABYSSAL_SIRE_5891, NpcID.ABYSSAL_SIRE_5908),
	ADAMANT_DRAGON(1.1d, NpcID.ADAMANT_DRAGON),
	AHRIM_THE_BLIGHTED(1.025d, NpcID.AHRIM_THE_BLIGHTED),
	ALCHEMICAL_HYDRA(1.2d, NpcID.ALCHEMICAL_HYDRA),
	AMMONITE_CRAB(1d, NpcID.AMMONITE_CRAB),
	ANCIENT_WYVERN(1.05d, NpcID.ANCIENT_WYVERN),
	ANCIENT_ZYGOMITE(1.025d, NpcID.ANCIENT_ZYGOMITE),
	ARCHER(1d, NpcID.ARCHER),
	ARRG(1.075d, NpcID.ARRG),
	BALFRUG_KREEYATH(1d, NpcID.BALFRUG_KREEYATH),
	BANDIT(1.025d, NpcID.BANDIT),
	BANSHEE(1d, NpcID.BANSHEE),
	BASILISK(1d, NpcID.BASILISK),
	BAT(1d, NpcID.BAT),
	BEAR_CUB(1d, NpcID.BEAR_CUB),
	BEDABIN_NOMAD_FIGHTER(1d, NpcID.BEDABIN_NOMAD_FIGHTER),
	BIG_WOLF(1d, NpcID.BIG_WOLF),
	BLACK_BEAR(1d, NpcID.BLACK_BEAR),
	BLACK_GUARD(1d, NpcID.BLACK_GUARD),
	BLACK_KNIGHT_TITAN(1.025d, NpcID.BLACK_KNIGHT_TITAN),
	BLACK_KNIGHT(1d, NpcID.BLACK_KNIGHT),
	BLACK_UNICORN(1d, NpcID.BLACK_UNICORN),
	BLUE_DRAGON(1.025d, NpcID.BLUE_DRAGON),
	BREE(1d, NpcID.BREE),
	BRINE_RAT(1d, NpcID.BRINE_RAT),
	BRUTAL_BLACK_DRAGON(1.075d, NpcID.BRUTAL_BLACK_DRAGON),
	BRUTAL_BLUE_DRAGON(1.05d, NpcID.BRUTAL_BLUE_DRAGON),
	BRUTAL_GREEN_DRAGON(1.05d, NpcID.BRUTAL_GREEN_DRAGON),
	BRUTAL_RED_DRAGON(1.075d, NpcID.BRUTAL_RED_DRAGON),
	CALLISTO(1.225d, NpcID.CALLISTO, NpcID.CALLISTO_6609),
	CAVE_CRAWLER(1d, NpcID.CAVE_CRAWLER),
	CAVE_HORROR(1d, NpcID.CAVE_HORROR),
	CAVE_KRAKEN(1d, NpcID.CAVE_KRAKEN),
	CERBERUS(1.15d, NpcID.CERBERUS, NpcID.CERBERUS_5863, NpcID.CERBERUS_5866),
	CHAOS_DRUID(1d, NpcID.CHAOS_DRUID),
	CHAOS_DWARF(1d, NpcID.CHAOS_DWARF),
	CHAOS_ELEMENTAL(1.075d, NpcID.CHAOS_ELEMENTAL, NpcID.CHAOS_ELEMENTAL_6505),
	CHAOS_FANATIC(1.125d, NpcID.CHAOS_FANATIC),
	COCKATRICE(1d, NpcID.COCKATRICE),
	COMMANDER_ZILYANA(1.375d, NpcID.COMMANDER_ZILYANA),
	CORPOREAL_BEAST(1.55d, NpcID.CORPOREAL_BEAST),
	COW_CALF(0.975d, NpcID.COW_CALF),
	COW(0.975d, NpcID.COW),
	CRAZY_ARCHAEOLOGIST(1.25d, NpcID.CRAZY_ARCHAEOLOGIST),
	DAD(1.05d, NpcID.DAD),
	DAGANNOTH_PRIME(1.3d, NpcID.DAGANNOTH_PRIME),
	DAGANNOTH_REX(1.3d, NpcID.DAGANNOTH_REX),
	DAGANNOTH_SUPREME(1d, NpcID.DAGANNOTH_SUPREME),
	DARK_BEAST(1.025d, NpcID.DARK_BEAST),
	DARK_WARRIOR(1.1d, NpcID.DARK_WARRIOR),
	DAWN(1d, NpcID.DAWN),
	DEADLY_RED_SPIDER(1d, NpcID.DEADLY_RED_SPIDER),
	DEMONIC_GORILLA(1.075d, NpcID.DEMONIC_GORILLA),
	DERANGED_ARCHAEOLOGIST(1.05d, NpcID.DERANGED_ARCHAEOLOGIST),
	DEVIANT_SPECTRE(1.025d, NpcID.DEVIANT_SPECTRE),
	DHAROK_THE_WRETCHED(1.15d, NpcID.DHAROK_THE_WRETCHED),
	DRAKE(1.075d, NpcID.DRAKE),
	DRUID(1d, NpcID.DRUID),
	DUCK(0.975d, NpcID.DUCK),
	DWARF(1d, NpcID.DWARF),
	EARTH_WARRIOR(1d, NpcID.EARTH_WARRIOR),
	ELDER_CHAOS_DRUID(1d, NpcID.ELDER_CHAOS_DRUID),
	ELF_WARRIOR(1.025d, NpcID.ELF_WARRIOR),
	ENT(1.025d, NpcID.ENT),
	FARMER(1d, NpcID.FARMER),
	FIRE_GIANT(1d, NpcID.FIRE_GIANT),
	FLIGHT_KILISA(1d, NpcID.FLIGHT_KILISA),
	FLOCKLEADER_GEERIN(1d, NpcID.FLOCKLEADER_GEERIN),
	FORTRESS_GUARD(1d, NpcID.FORTRESS_GUARD),
	GARGOYLE(1d, NpcID.GARGOYLE),
	GENERAL_GRAARDOR(1.325d, NpcID.GENERAL_GRAARDOR, NpcID.GENERAL_GRAARDOR_6494),
	GIANT_BAT(1d, NpcID.GIANT_BAT),
	GIANT_MOLE(1.075d, NpcID.GIANT_MOLE, NpcID.GIANT_MOLE_6499),
	GIANT_SCARAB(1.05d, NpcID.GIANT_SCARAB),
	GIANT_SPIDER(0.975d, NpcID.GIANT_SPIDER),
	GOBLIN(0.975d, NpcID.GOBLIN),
	GREAT_OLM__LEFT(1d, NpcID.GREAT_OLM_LEFT_CLAW, NpcID.GREAT_OLM_LEFT_CLAW_7555),
	GREAT_OLM_RIGHT(1.325d, NpcID.GREAT_OLM_RIGHT_CLAW, NpcID.GREAT_OLM_RIGHT_CLAW_7553),
	GREAT_OLM(1.575d, NpcID.GREAT_OLM),
	GREATER_NECHRYAEL(1.025d, NpcID.GREATER_NECHRYAEL),
	GREATER_SKELETON_HELLHOUND(1.05d, NpcID.GREATER_SKELETON_HELLHOUND),
	GRIZZLY_BEAR(1d, NpcID.GRIZZLY_BEAR),
	GROWLER(1d, NpcID.GROWLER),
	GUARD_DOG(1d, NpcID.GUARD_DOG),
	GUNTHOR_THE_BRAVE(1d, NpcID.GUNTHOR_THE_BRAVE),
	GUTHAN_THE_INFESTED(1.15d, NpcID.GUTHAN_THE_INFESTED),
	HERO(1.025d, NpcID.HERO),
	HILL_GIANT(1d, NpcID.HILL_GIANT),
	HOOP_SNAKE(1d, NpcID.HOOP_SNAKE),
	HYDRA(1.075d, NpcID.HYDRA),
	ICE_SPIDER(1d, NpcID.ICE_SPIDER),
	ICE_TROLL_KING(1.075d, NpcID.ICE_TROLL_KING),
	ICE_WARRIOR(1d, NpcID.ICE_WARRIOR),
	ICEFIEND(1d, NpcID.ICEFIEND),
	INFERNAL_MAGE(1d, NpcID.INFERNAL_MAGE),
	IRON_DRAGON(1.05d, NpcID.IRON_DRAGON),
	JAILER(1d, NpcID.JAILER),
	JALAK(1.025d, NpcID.JALAK),
	JALAKREKKET(1d, NpcID.JALAKREKKET),
	JALAKREKMEJ(1d, NpcID.JALAKREKMEJ),
	JALAKREKXIL(1d, NpcID.JALAKREKXIL),
	JALIMKOT(1d, NpcID.JALIMKOT),
	JALMEJJAK(1d, NpcID.JALMEJJAK),
	JALMEJRAH(1d, NpcID.JALMEJRAH),
	JALNIB(0.975d, NpcID.JALNIB),
	JALTOKJAD(1d, NpcID.JALTOKJAD),
	JALXIL(1d, NpcID.JALXIL),
	JALZEK(1d, NpcID.JALZEK),
	JELLY(1d, NpcID.JELLY),
	JOGRE(1d, NpcID.JOGRE),
	JUNGLE_DEMON(1.075d, NpcID.JUNGLE_DEMON),
	KALPHITE_GUARDIAN(1d, NpcID.KALPHITE_GUARDIAN),
	KALPHITE_QUEEN(1.05d, NpcID.KALPHITE_QUEEN, NpcID.KALPHITE_QUEEN_963, NpcID.KALPHITE_QUEEN_965, NpcID.KALPHITE_QUEEN_4303, NpcID.KALPHITE_QUEEN_4304, NpcID.KALPHITE_QUEEN_6500, NpcID.KALPHITE_QUEEN_6501),
	KALPHITE_SOLDIER(1d, NpcID.KALPHITE_SOLDIER),
	KALPHITE_WORKER(1d, NpcID.KALPHITE_WORKER),
	KARIL_THE_TAINTED(1d, NpcID.KARIL_THE_TAINTED),
	KETZEK(1d, NpcID.KETZEK),
	KING_BLACK_DRAGON(1.075d, NpcID.KING_BLACK_DRAGON, NpcID.KING_BLACK_DRAGON_2642, NpcID.KING_BLACK_DRAGON_6502),
	KING_SAND_CRAB(1d, NpcID.KING_SAND_CRAB),
	KING_SCORPION(1d, NpcID.KING_SCORPION),
	KNIGHT_OF_ARDOUGNE(1d, NpcID.KNIGHT_OF_ARDOUGNE),
	KOUREND_GUARD(1d, NpcID.KOUREND_GUARD),
	KOUREND_HEAD_GUARD(1d, NpcID.KOUREND_HEAD_GUARD),
	KRAKEN(1d, NpcID.KRAKEN),
	KREEARRA(1.4d, NpcID.KREEARRA),
	KRIL_TSUROTH(1.375d, NpcID.KRIL_TSUTSAROTH, NpcID.KRIL_TSUTSAROTH_6495),
	KRIL_TSUTSAROTH(1.375d, NpcID.KRIL_TSUTSAROTH),
	KURASK(1d, NpcID.KURASK),
	LAVA_DRAGON(1.075d, NpcID.LAVA_DRAGON),
	LIZARDMAN_BRUTE(1d, NpcID.LIZARDMAN_BRUTE),
	LIZARDMAN_SHAMAN(1.05d, NpcID.LIZARDMAN_SHAMAN),
	LOBSTROSITY(1d, NpcID.LOBSTROSITY),
	LONGTAILED_WYVERN(1.025d, NpcID.LONGTAILED_WYVERN),
	MAGIC_AXE(1d, NpcID.MAGIC_AXE),
	MAIDEN_OF_SUGADINT(1d, NpcID.THE_MAIDEN_OF_SUGADINTI, NpcID.THE_MAIDEN_OF_SUGADINTI_8361, NpcID.THE_MAIDEN_OF_SUGADINTI_8362, NpcID.THE_MAIDEN_OF_SUGADINTI_8363, NpcID.THE_MAIDEN_OF_SUGADINTI_8364, NpcID.THE_MAIDEN_OF_SUGADINTI_8365),
	MAMMOTH(1d, NpcID.MAMMOTH),
	MAN(1d, NpcID.MAN),
	MANIACAL_MONKEY(1d, NpcID.MANIACAL_MONKEY),
	MITHRIL_DRAGON(1.075d, NpcID.MITHRIL_DRAGON),
	MONK(1d, NpcID.MONK),
	MONKEY_GUARD(1.025d, NpcID.MONKEY_GUARD),
	MONKEY(1d, NpcID.MONKEY),
	MOSS_GIANT(1.025d, NpcID.MOSS_GIANT),
	MOURNER(1.025d, NpcID.MOURNER),
	MUGGER(1d, NpcID.MUGGER),
	MUTATED_BLOODVELD(1d, NpcID.MUTATED_BLOODVELD),
	NECHRYAEL(1d, NpcID.NECHRYAEL),
	NIGHT_BEAST(1.175d, NpcID.NIGHT_BEAST),
	NYLOCAS_MATOMENOS(1d, NpcID.NYLOCAS_MATOMENOS),
	NYLOCAS_VASILIAS(1.225d, NpcID.NYLOCAS_VASILIAS),
	OBOR(1.075d, NpcID.OBOR),
	OGRE(1d, NpcID.OGRE),
	ORK(1d, NpcID.ORK),
	PALADIN(1.025d, NpcID.PALADIN),
	PENGUIN(1d, NpcID.PENGUIN),
	PESTILENT_BLOAT(1.85d, NpcID.PESTILENT_BLOAT),
	PIRATE(1d, NpcID.PIRATE),
	POISON_SCORPION(1d, NpcID.POISON_SCORPION),
	POISON_SPIDER(1d, NpcID.POISON_SPIDER),
	POSSESSED_PICKAXE(1d, NpcID.POSSESSED_PICKAXE),
	PYREFIEND(1d, NpcID.PYREFIEND),
	RED_DRAGON(1.025d, NpcID.RED_DRAGON),
	REVENANT_CYCLOPS(1.075d, NpcID.REVENANT_CYCLOPS),
	REVENANT_DARK_BEAST(1.125d, NpcID.REVENANT_DARK_BEAST),
	REVENANT_DEMON(1.075d, NpcID.REVENANT_DEMON),
	REVENANT_DRAGON(1.2d, NpcID.REVENANT_DRAGON),
	REVENANT_GOBLIN(1d, NpcID.REVENANT_GOBLIN),
	REVENANT_HELLHOUND(1.075d, NpcID.REVENANT_HELLHOUND),
	REVENANT_HOBGOBLIN(1.025d, NpcID.REVENANT_HOBGOBLIN),
	REVENANT_IMP(1d, NpcID.REVENANT_IMP),
	REVENANT_KNIGHT(1.175d, NpcID.REVENANT_KNIGHT),
	REVENANT_ORK(1.1d, NpcID.REVENANT_ORK),
	REVENANT_PYREFIEND(1d, NpcID.REVENANT_PYREFIEND),
	ROBERT_THE_STRONG(1.05d, NpcID.ROBERT_THE_STRONG),
	ROCK_CRAB(1d, NpcID.ROCK_CRAB),
	ROCKSLUG(1d, NpcID.ROCKSLUG),
	ROGUE(1d, NpcID.ROGUE),
	RUNE_DRAGON(1.1d, NpcID.RUNE_DRAGON),
	SAND_CRAB(1d, NpcID.SAND_CRAB),
	SCARAB_MAGE(1.025d, NpcID.SCARAB_MAGE),
	SCARAB_SWARM(1d, NpcID.SCARAB_SWARM),
	SCARABS(1d, NpcID.SCARABS),
	SCORPIA(1.3d, NpcID.SCORPIA),
	SERGEANT_GRIMSPIKE(1d, NpcID.SERGEANT_GRIMSPIKE),
	SERGEANT_STEELWILL(1d, NpcID.SERGEANT_STEELWILL),
	SERGEANT_STRONGSTACK(1d, NpcID.SERGEANT_STRONGSTACK),
	SKELETAL_WYVERN(1.05d, NpcID.SKELETAL_WYVERN),
	SKELETON(1.025d, NpcID.SKELETON),
	SKOTIZO(1.375d, NpcID.SKOTIZO),
	SLAGILITH(1d, NpcID.SLAGILITH),
	SMOKE_DEVIL(1d, NpcID.SMOKE_DEVIL),
	SNAKE(1d, NpcID.SNAKE),
	SOTETSEG(1.675d, NpcID.SOTETSEG, NpcID.SOTETSEG_8388),
	SPIDER(1d, NpcID.SPIDER),
	SPINOLYP(1d, NpcID.SPINOLYP),
	SPIRITUAL_WARRIOR(1.025d, NpcID.SPIRITUAL_WARRIOR),
	SPITTING_WYVERN(1.025d, NpcID.SPITTING_WYVERN),
	STARLIGHT(1.05d, NpcID.STARLIGHT),
	STEEL_DRAGON(1.05d, NpcID.STEEL_DRAGON),
	SUIT_OF_ARMOUR(1d, NpcID.SUIT_OF_ARMOUR),
	SUQAH(1.025d, NpcID.SUQAH),
	TALONED_WYVERN(1.025d, NpcID.TALONED_WYVERN),
	TAR_MONSTER(1d, NpcID.TAR_MONSTER),
	THERMONUCLEAR_SMOKE_DEVIL(1d, NpcID.THERMONUCLEAR_SMOKE_DEVIL),
	THIEF(1d, NpcID.THIEF),
	THUG(1d, NpcID.THUG),
	TOKXIL(1d, NpcID.TOKXIL),
	TORAG_THE_CORRUPTED(1.125d, NpcID.TORAG_THE_CORRUPTED),
	TROLL_GENERAL(1.075d, NpcID.TROLL_GENERAL),
	TSTANON_KARLAK(1d, NpcID.TSTANON_KARLAK),
	TWISTED_BANSHEE(1d, NpcID.TWISTED_BANSHEE),
	TZHAARHUR(1d, NpcID.TZHAARHUR),
	TZHAARKET(1d, NpcID.TZHAARKET),
	TZHAARXIL(1d, NpcID.TZHAARXIL),
	TZKALZUK(1.575d, NpcID.TZKALZUK),
	TZKIH(1d, NpcID.TZKIH),
	TZTOKJAD(1d, NpcID.TZTOKJAD),
	UNICORN(1d, NpcID.UNICORN),
	VENENATIS(1.525d, NpcID.VENENATIS),
	VENETENATIS(1.4d, NpcID.VENENATIS, NpcID.VENENATIS_6610),
	VERAC_THE_DEFILED(1.125d, NpcID.VERAC_THE_DEFILED),
	VERZIK_SPIDER(1.85d, NpcID.VERZIK_VITUR_8375),
	VERZIK(1.425d, NpcID.VERZIK_VITUR),
	VETION(1.225d, NpcID.VETION, NpcID.VETION_REBORN),
	WARPED_JELLY(1d, NpcID.WARPED_JELLY),
	WARRIOR_WOMAN(1d, NpcID.WARRIOR_WOMAN),
	WATERFIEND(1d, NpcID.WATERFIEND),
	WINGMAN_SKREE(1.025d, NpcID.WINGMAN_SKREE),
	WOLF(1d, NpcID.WOLF),
	WYRM(1.025d, NpcID.WYRM),
	XARPUS(1d, NpcID.XARPUS),
	YAK(1d, NpcID.YAK),
	YTHURKOT(1d, NpcID.YTHURKOT),
	YTMEJKOT(1d, NpcID.YTMEJKOT),
	ZAKLN_GRITCH(1d, NpcID.ZAKLN_GRITCH);


	private final Set<Integer> ids;
	private final double modifier; // Some NPCs have a modifier to the experience a player receives.

	Boss(double modifier, Integer... ids)
	{
		this.modifier = modifier;
		this.ids = Sets.newHashSet(ids);
	}

	static Boss getBoss(int id)
	{
		for (Boss boss : values())
		{
			if (boss.ids.contains(id))
			{
				return boss;
			}
		}

		return null;
	}

}