/*
 * Copyright (c) 2016-2017, Seth <Sethtroll3@gmail.com>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */
package net.runelite.client.plugins.cluescrolls;

import java.util.HashMap;
import java.util.Map;
import static net.runelite.api.ItemID.*;
import static net.runelite.client.plugins.cluescrolls.ClueScrollType.ANAGRAM;
import static net.runelite.client.plugins.cluescrolls.ClueScrollType.CHALLENGE;
import static net.runelite.client.plugins.cluescrolls.ClueScrollType.CIPHER;
import static net.runelite.client.plugins.cluescrolls.ClueScrollType.CRYPTIC;
import static net.runelite.client.plugins.cluescrolls.ClueScrollType.EMOTE;

public enum ClueScroll
{
	CLUE1(new int[] { BLACK_AXE, COIF, RUBY_RING }, "Spin in the Varrock Castle courtyard. Equip a black axe, a coif and a ruby ring.", EMOTE),
	CLUE2(new int[] { STEEL_FULL_HELM, STEEL_PLATEBODY, IRON_PLATESKIRT }, "Dance in the Party Room. Equip a steel full helmet, steel platebody and an iron plateskirt.", EMOTE),
	CLUE3(new int[] { DRAGON_SQ_SHIELD, SPLITBARK_BODY, ORANGE_BOATER }, "Wave on the the nothern wall of the Castle Drakan. Beware of double agents! Wear a dragon sq shield, splitbark body and any boater.", EMOTE),
	CLUE4(new int[] { ADAMANT_SWORD, SAPPHIRE_AMULET, ADAMANT_PLATESKIRT }, "Cry in the Draynor Village jail. Jump for joy before you talk to me. Equip an adamant sword, a sapphire amulet and an adamant plateskirt.", EMOTE),
	CLUE5(new int[] { }, "Cheer at the games room. Have nothing equipped at all when you do.", EMOTE),
	CLUE6(new int[] { MYSTIC_FIRE_STAFF, DIAMOND_BRACELET, RUNE_BOOTS }, "Headbang at the exam center. Beware of double agents! Equip a mystic fire staff, a diamond bracelet and rune boots.", EMOTE),
	CLUE7(new int[] { COIF, IRON_PLATEBODY, LEATHER_GLOVES }, "Blow raspberries outside the entrance to Keep Le Faye. Equip a coif, an iron platebody and leather gloves", EMOTE),
	CLUE8(new int[] { BARROWS_GLOVES, AMULET_OF_GLORY, DRAGON_MED_HELM }, "Dance on the Fishing Platform. Equip barrows gloves, an amulet of glory and a dragon med helm.", EMOTE),
	CLUE9(new int[] { RUNE_CROSSBOW, CLIMBING_BOOTS, ANCIENT_MITRE }, "Cheer in the Shadow dungeon. Equip a rune crossbow, climbing boots and any mitre.", EMOTE),
	CLUE10(new int[] { MITHRIL_CHAINBODY, GREEN_DHIDE_CHAPS, RUBY_AMULET }, "Think in the centre of the Observatory. Spin before you talk to me. Equip a mithril chain body, green dragonhide chaps and a ruby amulet.", EMOTE),
	CLUE11(new int[] { IRON_PLATELEGS, EMERALD_AMULET, OAK_LONGBOW }, "Bow outside the entrance to the Legends' Guild. Equip iron platelegs, an emerald amulet and an oak longbow.", EMOTE),
	CLUE12(new int[] { GOLD_NECKLACE, GOLD_RING, BRONZE_SPEAR }, "Shrug in the mine near Rimmington. Equip a gold necklace, a gold ring and a bronze spear.", EMOTE),
	CLUE13(new int[] { BRUISE_BLUE_SNELM, STAFF_OF_AIR, BRONZE_SQ_SHIELD }, "Dance a jig under Shantay's Awning. Bow before you talk to me. Equip a pointed blue snail helmet, an air staff and a bronze square shield.", EMOTE),
	CLUE14(new int[] { }, "Dance a jig by the Barrow's reward chest. Beware of double agents! Equip any set of Barrows equipment.", EMOTE),
	CLUE15(new int[] { ZAMORAK_FULL_HELM, SHADOW_SWORD }, "Blow a kiss outside K'ril Tsutsaroth's chamber. Beware of double agents! Equip a Zamorak full helm and the shadow sword.", EMOTE),
	CLUE16(new int[] { COIF, STEEL_PLATESKIRT, SAPPHIRE_NECKLACE }, "Cheer for the monks at Port Sarim. Equip a coif, steel plateskirt and a sapphire necklace.", EMOTE),
	CLUE17(new int[] { DRAGON_2H_SWORD, BANDOS_BOOTS, OBSIDIAN_CAPE }, "Jump for joy in the centre of Zul-Andra. Beware of double agents! Equip a dragon 2h sword, bandos boots and an obsidian cape.", EMOTE),
	CLUE18(new int[] { IBANS_STAFF, MYSTIC_ROBE_TOP_DARK, MYSTIC_ROBE_BOTTOM_DARK }, "Dance in Iban's temple. Beware of double agents! Equip Iban's staff, a black mystic top, and a black mystic bottom.", EMOTE),
	CLUE19(new int[] { GREEN_DHIDE_BODY, GREEN_DHIDE_CHAPS, STEEL_SQ_SHIELD }, "Cheer in the Ogre Pen in the Training Camp. Show you are angry before you talk to me. Equip a green dragonhide body and chaps and a steel square shield.", EMOTE),
	CLUE20(new int[] { CRYSTAL_BOW_FULL_I }, "Bow near Lord Iorwerth. Beware of double agents! Equip a new imbued crystal bow.", EMOTE),
	CLUE21(new int[] { BROWN_APRON, LEATHER_BOOTS, LEATHER_GLOVES }, "Cheer in the Edgeville general store. Dance before you talk to me. Equip a brown apron, leather boots and leather gloves.", EMOTE),
	CLUE22(new int[] { DRAGON_PLATESKIRT, CLIMBING_BOOTS, DRAGON_CHAINBODY }, "Swing a bullroarer at the top of the watchtower. Beware of double agents! Equip a dragon plateskirt, climbing boots and a dragon chainbody.", EMOTE),
	CLUE23(new int[] { MAPLE_LONGBOW, GREEN_DHIDE_CHAPS, IRON_MED_HELM }, "Shrug in Catherby bank. Yawn before you talk to me. Equip a maple longbow, green dragonhide chaps and an iron med helm.", EMOTE),
	CLUE24(new int[] { DESERT_SHIRT, GREEN_ROBE_BOTTOMS, STEEL_AXE }, "Jump for joy at the beehives. Equip a desert shirt, green gnome robe bottoms and a steel axe.", EMOTE),
	CLUE25(new int[] { GRANITE_SHIELD, SPLITBARK_BODY, RUNE_HELM_H1 }, "Jump for joy in the Ancient Cavern. Equip a granite shield, splitbark body, and any rune heraldic helm.", EMOTE),
	CLUE26(new int[] { BLACK_DHIDE_BODY, BLACK_DHIDE_VAMB, BLACK_DRAGON_MASK }, "Dance in the King Black Dragon's lair. Beware of double agents! Equip a black dragonhide body, black dragonhide vambs and a black dragon mask.", EMOTE),
	CLUE27(new int[] { FIRE_CAPE, TOKTZXILUL }, "Cry in the Tzhaar gem shop. Beware of the double agents! Equip a fire cape and a Toktz-xil-ul.", EMOTE),
	CLUE28(new int[] { BLUE_ROBE_TOP, TURQUOISE_ROBE_BOTTOMS, OAK_SHORTBOW }, "Think in middle of the wheat field by the lumbridge mill. Equip a blue gnome robetop, a turquoise gnome robe bottom and an oak shortbow.", EMOTE),
	CLUE29(new int[] { STEEL_PLATEBODY, MAPLE_SHORTBOW, TEAM1_CAPE }, "Cheer in the Barbarian Agility Arena. Headbang before you talk to me. Equip a steel platebody, maple shortbow and a Wilderness cape.", EMOTE),
	CLUE30(new int[] { ELEMENTAL_SHIELD, BLUE_DHIDE_CHAPS, RUNE_WARHAMMER }, "Blow a raspberry in the Fishing Guild bank. Beware of double agents! Equip an elemental shield, blue dragonhide chaps and a rune warhammer.", EMOTE),
	CLUE31(new int[] { WIZARD_HAT, BRONZE_2H_SWORD, HAM_BOOTS }, "Cheer at the Druids' Circle. Equip a blue wizard hat, a bronze two-handed sword and HAM boots.", EMOTE),
	CLUE32(new int[] { FLARED_TROUSERS }, "Clap in the magic axe hut. Beware of double agents. Equip only flared trousers", EMOTE),
	CLUE33(new int[] { ABYSSAL_WHIP, CAPE_OF_LEGENDS, SPINED_CHAPS }, "Show your anger at the Wise old man. Beware of double agents! Equip an abyssal whip, a legend's cape and some spined chaps.", EMOTE),
	CLUE34(new int[] { IRON_MED_HELM, EMERALD_RING, WHITE_APRON }, "Clap on the causeway to the Wizards' Tower. Equip an iron med helm, emerald ring and a white apron.", EMOTE),
	CLUE35(new int[] { SPLITBARK_LEGS, DRAGON_BOOTS, RUNE_LONGSWORD }, "Laugh by the fountain of heroes. Equip splitbark legs, dragon boots and a Rune longsword.", EMOTE),
	CLUE36(new int[] { RUBY_AMULET, MITHRIL_SCIMITAR, TEAM1_CAPE }, "Yawn in the Castle Wars lobby. Shrug before you talk to me. Equip a ruby amulet, a mithril scimitar and a Wilderness cape.", EMOTE),
	CLUE37(new int[] { RUNE_FULL_HELM, BLUE_DHIDE_CHAPS, FIRE_BATTLESTAFF }, "Laugh in Jokul's tent in the Mountain Camp. Beware of double agents! Equip a rune full helmet, blue dragonhide chaps and a fire battlestaff.", EMOTE),
	CLUE38(new int[] { }, "Panic on the pier where you catch the Fishing trawler Have nothing equipped at all when you do.", EMOTE),
	CLUE39(new int[] { PURPLE_GLOVES, STEEL_KITESHIELD, MITHRIL_FULL_HELM }, "Spin on the bridge by the Barbarian Village. Salute before you talk to me. Equip purple gloves, a steel kiteshield and a mithril full helmet.", EMOTE),
	CLUE40(new int[] { PHARAOHS_SCEPTRE, MENAPHITE_PURPLE_HAT, MENAPHITE_PURPLE_TOP, MENAPHITE_PURPLE_ROBE }, "Yawn in the 7th room of Pyramid Plunder. Beware of double agents! Equip a pharoah sceptre and a full set of menaphite robes.", EMOTE),
	CLUE41(new int[] { ARCLIGHT, AMULET_OF_THE_DAMNED }, "Slap your head in the centre of the Kourend catacombs. Beware of double agents! Equip the arclight and an amulet of the damned.", EMOTE),
	CLUE42(new int[] { SEERCULL, COMBAT_BRACELET, HELM_OF_NEITIZNOT }, "Headbang at the top of Slayer Tower. Equip a seercull, a combat bracelet and helm of Neitiznot.", EMOTE),
	CLUE43(new int[] { }, "Panic in the heart of the Haunted Woods. Beware of double agents! Have no items equipped when you do.", EMOTE),
	CLUE44(new int[] { MITHRIL_PLATELEGS, RING_OF_LIFE, RUNE_AXE }, "Panic by the pilot on White Wolf Mountain. Beware of double agents! Equip mithril platelegs, a ring of life, and a rune axe.", EMOTE),
	CLUE45(new int[] { RUNE_PLATELEGS, IRON_PLATEBODY, BLUE_DHIDE_VAMB }, "Shrug in the Zamorak temple found in the Eastern Wilderness. Beware of double agents! Equip rune platelegs, an iron platebody and blue dragonhide vambraces.", EMOTE),
	CLUE46(new int[] { BLUE_HAT, HAM_ROBE, TIARA }, "Clap on the top level of the mill, north of East Ardougne. Equip a blue gnome robe top, HAM robe bottom and an unenchanted tiara.", EMOTE),
	CLUE47(new int[] { ADAMANT_PLATEBODY, ADAMANT_FULL_HELM, ADAMANT_PLATELEGS }, "Beckon in the combat ring of Shayzien. Show your anger before you talk to me. Equip an adamant platebody, adamant full helm and adamant platelegs.", EMOTE),
	CLUE48(new int[] { HARDLEATHER_BODY, LEATHER_CHAPS, BRONZE_AXE }, "Wave along the south fence of the Lumber Yard. Equip a hard leather body, leather chaps and a bronze axe.", EMOTE),
	CLUE49(new int[] { UNHOLY_BOOK, HOLY_BOOK, BOOK_OF_BALANCE }, "Bow upstairs in the Edgeville Monastery. Equip a completed prayer book.", EMOTE),
	CLUE50(new int[] { STEEL_LONGSWORD, BLUE_DHIDE_BODY, MYSTIC_GLOVES }, "Jump for joy in the TzHaar sword shop. Shrug before you talk to me. Equip a Steel longsword, Blue D'hide body and blue mystic gloves.", EMOTE),
	CLUE51(new int[] { BLUE_DHIDE_BODY, BLUE_DHIDE_VAMB }, "Bow at the top of the lighthouse. Beware of double agents! Equip a blue dragonhide body, blue dragonhide vambraces and no jewellery.", EMOTE),
	CLUE52(new int[] { STEEL_KITESHIELD, RING_OF_FORGING, GREEN_DHIDE_CHAPS }, "Cry on top of the western tree in the Gnome Agility Arena. Indicate 'no' before you talk to me. Equip a steel kiteshield, ring of forging, and green dragonhide chaps.", EMOTE),
	CLUE53(new int[] { IRON_CHAINBODY, LEATHER_CHAPS, COIF }, "Bow in the ticket office of the Duel Arena. Equip an iron chain body, leather chaps and coif.", EMOTE),
	CLUE54(new int[] { RUNE_SPEAR, RUNE_PLATELEGS, RUNE_HELM_H1 }, "Jig at Jiggig. Beware of double agents! Equip a Rune spear, rune platelegs and any rune heraldic helm.", EMOTE),
	CLUE55(new int[] { DESERT_SHIRT, LEATHER_GLOVES, LEATHER_BOOTS }, "Headbang in the mine north of Al Kharid. Equip a desert shirt, leather gloves and leather boots.", EMOTE),
	CLUE56(new int[] { BLACK_DHIDE_CHAPS, SPOTTED_CAPE, ROLLING_PIN }, "Blow a kiss in the heart of the lava maze. Equip black dragonhide chaps, a spotted cape and a rolling pin.", EMOTE),
	CLUE57(new int[] { BLACK_DHIDE_BODY, BLACK_DHIDE_CHAPS, BLACK_DHIDE_VAMB }, "Cheer in the Entrana church. Beware of double agents! Equip a set of full black dragonhide armour.", EMOTE),
	CLUE58(new int[] { BRONZE_DAGGER, IRON_FULL_HELM, GOLD_RING }, "Dance in the shack in Lumbridge Swamp. Equip a bronze dagger, iron full helmet and a gold ring.", EMOTE),
	CLUE59(new int[] { BRONZE_PLATELEGS, STEEL_PICKAXE, STEEL_MED_HELM }, "Panic in the Limestone Mine. Equip bronze platelegs, a steel pickaxe and a steel medium helmet.", EMOTE),
	CLUE60(new int[] { RUNE_HALBERD, RUNE_PLATEBODY, AMULET_OF_STRENGTH }, "Salute in the centre of the mess hall. Beware of double agents! Equip a rune halberd, rune platebody and an amulet of strength", EMOTE),
	CLUE61(new int[] { BLACK_CAPE, LEATHER_CHAPS, STEEL_MACE }, "Wave on Mudskipper Point. Equip a black cape, leather chaps and a steel mace.", EMOTE),
	CLUE62(new int[] { GREEN_ROBE_TOP, HAM_ROBE, IRON_WARHAMMER }, "Yawn in the Varrock library. Equip a green gnome robe top, HAM robe bottom and an iron warhammer.", EMOTE),
	CLUE63(new int[] { MITHRIL_PICKAXE, BLACK_PLATEBODY, IRON_KITESHIELD }, "Wave in the Falador gem store. Equip a Mithril pickaxe, Black platebody and an Iron Kiteshield.", EMOTE),
	CLUE64(new int[] { DRAGON_PICKAXE, HELM_OF_NEITIZNOT, RUNE_BOOTS }, "Spin in front of the Soul altar. Beware of double agents! Equip a dragon pickaxe, helm of neitiznot and a pair of rune boots.", EMOTE),
	CLUE65(new int[] { DRAGON_MED_HELM, TOKTZKETXIL, BRINE_SABRE, RUNE_PLATEBODY, AMULET_OF_GLORY }, "Panic by the big egg where no one dare goes and the ground is burnt. Beware of double agents! Equip a dragon med helm, a TokTz-Ket-Xil, a brine sabre, rune platebody and an uncharged amulet of glory.", EMOTE),
	CLUE66(new int[] { RUNE_BOOTS, PROSELYTE_HAUBERK, DRAGONSTONE_RING }, "Jump for joy at the Neitiznot rune rock. Equip rune boots, a proselyte hauberk and a dragonstone ring.", EMOTE),
	CLUE67(new int[] { GREEN_ROBE_TOP, MITHRIL_PLATELEGS, IRON_2H_SWORD }, "Dance in the centre of Canifis. Bow before you talk to me. Equip a green gnome robe top, mithril platelegs and an iron two-handed sword.", EMOTE),
	CLUE68(new int[] { LAVA_BATTLESTAFF, BLACK_DHIDE_VAMB, MIND_SHIELD }, "Yawn at the top of Trollheim. Equip a lava battlestaff, black dragonhide vambraces and a mind shield.", EMOTE),
	CLUE69(new int[] { STAFF_OF_AIR, BRONZE_FULL_HELM, AMULET_OF_POWER }, "Dance in the dark caves beneath Lumbridge Swamp. Blow a kiss before you talk to me. Equip an air staff, Bronze full helm and an Amulet of power.", EMOTE),
	CLUE70(new int[] { IRON_CHAINBODY, SAPPHIRE_RING, LONGBOW }, "Dance at the crossroads north of Draynor. Equip an iron chain body, a sapphire ring and a longbow.", EMOTE),
	CLUE71(new int[] { ADAMANT_SQ_SHIELD, BLUE_DHIDE_VAMB, RUNE_PICKAXE }, "Yawn in the rogues' general store. Beware of double agents! Equip an adamant square shield, blue dragon vambraces and a rune pickaxe.", EMOTE),
	CLUE72(new int[] { BANDOS_PLATEBODY, BANDOS_CLOAK, BANDOS_GODSWORD }, "Goblin Salute at the Goblin Village. Beware of double agents! Equip a Bandos platebody, Bandos cloak and Bandos godsword.", EMOTE),
	CLUE73(new int[] { DRAGON_AXE }, "Stamp in the Enchanted valley west of the waterfall. Beware of double agents! Equip a dragon axe.", EMOTE),
	CLUE74(new int[] { BLUE_BOOTS, HARDLEATHER_BODY, SILVER_SICKLE }, "Cry in the Catherby Ranging shop. Bow before you talk to me. Equip blue gnome boots, a hard leather body and an unblessed silver sickle.", EMOTE),
	CLUE75(new int[] { GREEN_HAT, SNAKESKIN_BOOTS, IRON_PICKAXE }, "Beckon in the Digsite, near the eastern winch. Bow before you talk to me Equip a green gnome hat, snakeskin boots and an iron pickaxe.", EMOTE),
	CLUE76(new int[] { MYSTIC_ROBE_TOP, RUNE_SHIELD_H1 }, "Cheer at the top of the agility pyramid. Beware of double agents! Equip a blue mystic robe top, and any rune heraldic shield.", EMOTE),
	CLUE77(new int[] { STUDDED_BODY, BRONZE_PLATELEGS, STAFF }, "Blow a raspberry at the monkey cage in Ardougne Zoo. Equip a studded leather body, bronze platelegs and a normal staff with no orb.", EMOTE),
	CLUE78(new int[] { DRAGON_BATTLEAXE, DRAGON_DEFENDER, SLAYER_HELMET }, "Do a push up at the bank of the Warrior's guild. Beware of double agents! Equip a dragon battleaxe, a dragon defender and a slayer helm of any kind.", EMOTE),
	CLUE79(new int[] { ADAMANT_SQ_SHIELD, BONE_DAGGER, MITHRIL_PLATEBODY }, "Cry on the shore of Catherby beach. Laugh before you talk to me, Equip an adamant sq shield, a bone dagger and mithril platebody.", EMOTE),
	CLUE80(new int[] { MITHRIL_PLATESKIRT, MAPLE_LONGBOW }, "Panic by the mausoleum in Morytania. Wave before you speak to me. Equip a mithril plate skirt, a maple longbow and no boots.", EMOTE),
	CLUE81(new int[] { AIR_TIARA, STAFF_OF_WATER }, "Do a jig in Varrock's rune store. Equip an air tiara and a staff of water.", EMOTE),
	CLUE82(new int[] { ZAMORAK_GODSWORD }, "Show your anger towards the Statue of Saradomin in Ellamaria's garden. Beware of double agents! Equip a Zamorak godsword.", EMOTE),
	CLUE83(new int[] { IRON_PLATEBODY, STUDDED_CHAPS, BRONZE_FULL_HELM }, "Spin in Draynor Manor by the fountain. Equip an iron platebody, studded leather chaps and a bronze full helmet.", EMOTE),
	CLUE84(new int[] { MYSTIC_HAT, BONE_SPEAR, RUNE_PLATEBODY }, "Blow a kiss between the tables in Shilo Village bank. Beware of double agents! Equip a blue mystic hat, bone spear and rune plate body.", EMOTE),
	CLUE85(new int[] { EMERALD_RING, SAPPHIRE_AMULET, BRONZE_CHAINBODY }, "Dance a jig by the entrance to the Fishing Guild. Equip an emerald ring, a sapphire amulet, and a bronze chain body.", EMOTE),
	CLUE86(new int[] { LEATHER_CHAPS, IRON_KITESHIELD, STEEL_LONGSWORD }, "Yawn in Draynor Marketplace. Equip studded leather chaps, an iron kiteshield and a steel longsword.", EMOTE),
	CLUE87(new int[] { ADAMANT_HALBERD, MYSTIC_ROBE_BOTTOM, DIAMOND_RING }, "Clap in Seers court house. Spin before you talk to me. Equip an adamant halberd, blue mystic robe bottom and a diamond ring.", EMOTE),
	CLUE88(new int[] { DRAGON_SPEAR, RED_DHIDE_CHAPS }, "Spin in West Ardougne Church. Equip a dragon spear and red dragonhide chaps.", EMOTE),
	CLUE89(new int[] { BLUE_DHIDE_VAMB, ADAMANT_BOOTS, ADAMANT_DAGGER }, "Yawn in the centre of Arceuus library. Nod your head before you talk to me. Equip blue dragonhide vambraces, adamant boots and an adamant dagger.", EMOTE),
	CLUE90(new int[] { PINK_SKIRT, PINK_ROBE_TOP, BODY_TIARA }, "Dance at the entrance to the Grand Exchange. Equip a pink skirt, pink robe top and a body tiara.", EMOTE),
	CLUE91(new int[] { LEATHER_COWL, BLUE_WIZARD_ROBE, IRON_SCIMITAR }, "Laugh at the crossroads south of the Sinclair Mansion. Equip a cowl, blue wizard robe top and an iron scimitar.", EMOTE),
	CLUE92(new int[] { DIAMOND_RING, AMULET_OF_POWER }, "Salute in the banana plantation. Beware of double agents! Equip a diamond ring, amulet of power, and nothing on your chest and legs.", EMOTE),
	CLUE93(new int[] { BROWN_APRON, ADAMANT_MED_HELM, SNAKESKIN_CHAPS }, "Jump for joy in Yanille bank.Dance a jig before you talk to me. Equip a brown apron, adamant med helm and snakeskin chaps.", EMOTE),
	CLUE94(new int[] { GREEN_HEADBAND, ANCIENT_CROZIER }, "Panic on the Wilderness volcano bridge. Beware of double agents! Equip any headband and crozier.", EMOTE),
	CLUE95(new int[] { GREEN_HAT, CREAM_ROBE_TOP, LEATHER_CHAPS }, "Spin at the crossroads north of Rimmington. Equip a green gnome hat, cream gnome top and leather chaps.", EMOTE),
	CLUE96(new int[] { BLACK_SALAMANDER }, "Salute in the warriors' guild bank. Equip only a black salamander.", EMOTE),
	CLUE97(new int[] { WHITE_APRON, GREEN_BOOTS, LEATHER_GLOVES }, "Clap in the main exam room in the Exam Centre. Equip a white apron, green gnome boots and leather gloves.", EMOTE),
	CLUE98(new int[] { DEATH_TIARA, CAPE_OF_LEGENDS, RING_OF_WEALTH }, "Flap at the death altar. Beware of double agents! Equip a death tiara, a legend's cape and any ring of wealth.", EMOTE),
	CLUE99(new int[] { GREEN_DHIDE_CHAPS, RING_OF_DUELING8, MITHRIL_MED_HELM }, "Beckon in Tai Bwo Wannai. Clap before you talk to me. Equip green dragonhide chaps, a ring of dueling and a mithril medium helmet.", EMOTE),
	CLUE100(new int[] { RING_OF_LIFE, AMULET_OF_GLORY, ADAMANT_2H_SWORD }, "Dance at the cat-doored pyramid in Sophanem. Beware of double agents! Equip a ring of life, an uncharged amulet of glory and an adamant two-handed sword.", EMOTE),
	CLUE101(new int[] { ANCIENT_STOLE, RUNE_SHIELD_H1 }, "Beckon on the east coast of the Kharazi Jungle. Beware of double agents! Equip any vestment stole and a heraldic rune shield.", EMOTE),
	CLUE102(new int[] { COIF, IRON_PLATEBODY, LEATHER_GLOVES}, "Blow raspberries outside the entrance to Keep Le Faye. Equip a coif, an iron platebody and leather gloves.", EMOTE),
	CLUE103("This anagram reveals who to speak to next: VEIL VEDA", "Evil Dave", "Doris' basement, Edgeville", "666", ANAGRAM),
	CLUE104("This anagram reveals who to speak to next: MUS KIL READER", "Radimus Erkle", "Legends' Guild", ANAGRAM),
	CLUE105("This anagram reveals who to speak to next: HIS PHOR", "Horphis", "Arceuus Library, Zeah", "1", ANAGRAM),
	CLUE106("This anagram reveals who to speak to next: QUIT HORRIBLE TYRANT", "Brother Tranquility", "Mos Le'Harmless or Harmony Island", "7", ANAGRAM),
	CLUE107("This anagram reveals who to speak to next: GOBLIN KERN", "King Bolren", "Tree Gnome Village", ANAGRAM),
	CLUE108("This anagram reveals who to speak to next: KAY SIR", "Sir Kay", "The courtyard in Camelot Castle", "6", ANAGRAM),
	CLUE109("This anagram reveals who to speak to next: MOLD LA RAN", "Old Man Ral", "Meiyerditch", ANAGRAM),
	CLUE110("This anagram reveals who to speak to next: DEKAGRAM", "Dark Mage", "Centre of the Abyss", "13", ANAGRAM),
	CLUE111("This anagram reveals who to speak to next: LARK IN DOG", "King Roald", "Ground floor of Varrock castle", "24", ANAGRAM),
	CLUE112("This anagram reveals who to speak to next: LOW LAG", "Gallow", "Vinery in the Great Kourend", "12", ANAGRAM),
	CLUE113("This anagram reveals who to speak to next: VESTE", "Steve", "Upstairs Wyvern Area or Stronghold Slayer Cave", "2", ANAGRAM),
	CLUE114("This anagram reveals who to speak to next: ERR CURE IT", "Recruiter", "West Ardougne centre square", "20", ANAGRAM),
	CLUE115("This anagram reveals who to speak to next: AT HERG", "Regath", "General Store, Arceuus, Zeah", "25", ANAGRAM),
	CLUE116("This anagram reveals who to speak to next: EL OW", "Lowe", "Varrock archery store", ANAGRAM),
	CLUE117("This anagram reveals who to speak to next: A ZEN SHE", "Zenesha", "Platebody Southern Ardougne centre square", ANAGRAM),
	CLUE118("This anagram reveals who to speak to next: ICY FE", "Fycie", "East Feldip Hills", ANAGRAM),
	CLUE119("This anagram reveals who to speak to next: ACE MATCH ELM", "Cam the Camel", "North of the glider in Al Kharid", ANAGRAM),
	CLUE120("This anagram reveals who to speak to next: IM N ZEZIM", "Immenizz", "The Imp inside Puro-Puro", ANAGRAM),
	CLUE121("This anagram reveals who to speak to next: DRAGONS LAMENT", "Strange Old Man", "Barrows", "40", ANAGRAM),
	CLUE122("This anagram reveals who to speak to next: A BAKER", "Baraek", "Varrock square", "5", ANAGRAM),
	CLUE123("This anagram reveals who to speak to next: SNAH", "Hans", "Lumbridge Castle courtyard", "None", ANAGRAM),
	CLUE124("This anagram reveals who to speak to next: ME IF", "Femi", "Gates of Tree Gnome Stronghold", "None", ANAGRAM),
	CLUE125("This anagram reveals who to speak to next: I FAFFY RUN", "Fairy Nuff", "North of the bank in Zanaris", ANAGRAM),
	CLUE126("This anagram reveals who to speak to next: GULAG RUN", "Uglug Nar", "West of Jiggig", ANAGRAM),
	CLUE127("This anagram reveals who to speak to next: DR WARDEN FUNK", "Drunken Dwarf", "East Side of Keldagrim", ANAGRAM),
	CLUE128("This anagram reveals who to speak to next: EEK ZERO OP", "Zookeeper", "Ardougne Zoo", "40", ANAGRAM),
	CLUE129("This anagram reveals who to speak to next: DR HITMAN OR DIM THARN", "Mandrith", "Wilderness Resource Area", "28 or Light boxor Puzzle box", ANAGRAM),
	CLUE130("This anagram reveals who to speak to next: I AM SIR", "Marisi", "Allotment patch, South coast Zeah", "5", ANAGRAM),
	CLUE131("This anagram reveals who to speak to next: HALT US", "Luthas", "Banana plantation, Karamja", "33 or 0", ANAGRAM),
	CLUE132("This anagram reveals who to speak to next: ARC O LINE", "Caroline", "North Witchaven next to the row boat", "11", ANAGRAM),
	CLUE133("This anagram reveals who to speak to next: C ON GAME HOC", "Gnome Coach", "Gnome Ball course", "6", ANAGRAM),
	CLUE134("This anagram reveals who to speak to next: PROFS LOSE WRONG PIE", "Professor Onglewip", "Ground floor Wizards Tower", ANAGRAM),
	CLUE135("This anagram reveals who to speak to next: TWENTY CURE IRON", "New recruit Tony", "Shayzien House's Graveyard", ANAGRAM),
	CLUE136("This anagram reveals who to speak to next: ARMCHAIR THE PELT", "Charlie the Tramp", "South entrance of Varrock", "0", ANAGRAM),
	CLUE137("This anagram reveals who to speak to next: CAREER IN MOON", "Oneiromancer", "Astral altar", "25", ANAGRAM),
	CLUE138("This anagram reveals who to speak to next: RAT MAT WITHIN", "Martin Thwait", "Rogues' Den", "2", ANAGRAM),
	CLUE139("This anagram reveals who to speak to next: FORLUN", "Runolf", "Miscellania & Etceteria Dungeon", ANAGRAM),
	CLUE140("This anagram reveals who to speak to next: MOTHERBOARD", "Brother Omad", "Monastery south of Ardougne", "129", ANAGRAM),
	CLUE141("This anagram reveals who to speak to next: THICKNO", "Hickton", "Catherby fletching shop", "2", ANAGRAM),
	CLUE142("This anagram reveals who to speak to next: SAND NUT", "Dunstan", "Anvil in north east Burthorpe", "8", ANAGRAM),
	CLUE143("This anagram reveals who to speak to next: PACINNG A TAIE", "Captain Ginea", "Building east of Shayzien combat ring", "113", ANAGRAM),
	CLUE144("This anagram reveals who to speak to next: DO SAY MORE", "Doomsayer", "East of Lumbridge Castle", "95", ANAGRAM),
	CLUE145("This anagram reveals who to speak to next: THEM CAL CAME", "Cam the Camel", "Just outside of the Duel Arena", ANAGRAM),
	CLUE146("This anagram reveals who to speak to next: I DOOM ICON INN", "Dominic Onion", "Nightmare Zone", "9,500", ANAGRAM),
	CLUE147("This anagram reveals who to speak to next: MAJORS LAVA BADS AIR", "Ambassador Alvijar", "Northeast Dorgesh-Kaan, upper floor", "2,505", ANAGRAM),
	CLUE148("This anagram reveals who to speak to next: SEQUIN DIRGE", "Queen Sigrid", "Throne room of Etceteria Castle.", ANAGRAM),
	CLUE149("This anagram reveals who to speak to next: QUE SIR", "Squire", "Falador Castle Courtyard", "654", ANAGRAM),
	CLUE150("This anagram reveals who to speak to next: HE DO POSE. IT IS CULTRRL, MK?", "Riki the sculptor's model", "East Keldagrim, south of kebab seller.", ANAGRAM),
	CLUE151("This anagram reveals who to speak to next: A BAS", "Saba", "Death Plateau", ANAGRAM),
	CLUE152("This anagram reveals who to speak to next: NOD MED", "Edmond", "Behind the most NW house in East Ardougne", "3", ANAGRAM),
	CLUE153("This anagram reveals who to speak to next: COOL NERD", "Old Crone", "East of the Slayer Tower", "619", ANAGRAM),
	CLUE154("This anagram reveals who to speak to next: AN PAINT TONIC", "Captain Ninto", "Bar under White Wolf Mountain", ANAGRAM),
	CLUE155("This anagram reveals who to speak to next: COPPER ORE CRYPTS", "Prospector Percy", "Motherlode Mine", "12", ANAGRAM),
	CLUE156("This anagram reveals who to speak to next: R AK MI", "Karim", "Al Kharid Kebab shop", "5", ANAGRAM),
	CLUE157("This anagram reveals who to speak to next: NO OWNER", "Oronwen", "Lletya Seamstress shop in Lletya", "20", ANAGRAM),
	CLUE158("This anagram reveals who to speak to next: OR ZINC FUMES WARD", "Wizard Frumscone", "Downstairs in the Wizards' Guild", ANAGRAM),
	CLUE159("This anagram reveals who to speak to next: O BIRDZ A ZANY EN PC", "Cap'n Izzy no Beard", "Brimhaven Agility Arena", "33", ANAGRAM),
	CLUE160("This anagram reveals who to speak to next: DT RUN B", "Brundt the Chieftain", "Rellekka, main hall", "4", ANAGRAM),
	CLUE161("This anagram reveals who to speak to next: BY LOOK", "Bolkoy", "Tree Gnome Village general store", "13", ANAGRAM),
	CLUE162("This anagram reveals who to speak to next: I EAT ITS CHART HINTS DO U", "Shiratti the Custodian", "North of fountain, Nardah", ANAGRAM),
	CLUE163("This anagram reveals who to speak to next: YAWNS GY", "Ysgawyn", "Lletya", ANAGRAM),
	CLUE164("This anagram reveals who to speak to next: OK CO", "Cook", "Ground floor of Lumbridge Castle", "9", ANAGRAM),
	CLUE165("This anagram reveals who to speak to next: TAMED ROCKS", "Dockmaster", "Piscarilius House, NE of General store", "5", ANAGRAM),
	CLUE166("This anagram reveals who to speak to next: BLUE BRIM GUIDED", "Lumbridge Guide", "Outside of Lumbridge Castle", ANAGRAM),
	CLUE167("This anagram reveals who to speak to next: LADDER MEMO GUV", "Guard Vemmeldo", "Gnome Stronghold Bank", "3", ANAGRAM),
	CLUE168("This anagram reveals who to speak to next: MAL IN TAU", "Luminata", "Near Burgh de Rott entrance", ANAGRAM),
	CLUE169("This anagram reveals who to speak to next: HEORIC", "Eohric", "Burthorpe Castle, top floor", "36", ANAGRAM),
	CLUE170("This anagram reveals who to speak to next: GOBLETS ODD TOES", "Otto Godblessed", "Otto's Grotto","2", ANAGRAM),
	CLUE171("This anagram reveals who to speak to next: LEAKEY", "Kaylee", "Rising Sun Inn in Falador", "18", ANAGRAM),
	CLUE172("This anagram reveals who to speak to next: WOO AN EGG KIWI", "Awowogei", "Ape Atoll", "24", ANAGRAM),
	CLUE173("This anagram reveals who to speak to next: ARE COL", "Oracle", "Ice Mountain West of Edgeville", "48", ANAGRAM),
	CLUE174("This anagram reveals who to speak to next: AREA CHEF TREK", "Father Aereck", "Lumbridge Church", "19", ANAGRAM),
	CLUE175("This anagram reveals who to speak to next: MACHETE CLAM", "Cam the Camel", "Outside Duel Arena", "6", ANAGRAM),
	CLUE176("This anagram reveals who to speak to next: RED ART TANS", "Trader Stan", "Port Sarim Charter ship", ANAGRAM),
	CLUE177("This anagram reveals who to speak to next: UNLEASH NIGHT MIST", "Sigli the Huntsman", "Rellekka", "302", ANAGRAM),
	CLUE178("This anagram reveals who to speak to next: ARR! SO I AM A CRUST, AND?", "Ramara du Croissant", "Piscatoris Fishing Colony", ANAGRAM),
	CLUE179("This anagram reveals who to speak to next: A HEART", "Aretha", "Soul altar", "2", ANAGRAM),
	CLUE180("This anagram reveals who to speak to next: DED WAR", "Edward", "Inside Rogue's Castle", ANAGRAM),
	CLUE181("This anagram reveals who to speak to next: PEAK REFLEX", "Flax keeper", "Flax field south of Seers Village", "676", ANAGRAM),
	CLUE182("This anagram reveals who to speak to next: SLAM DUSTER GRAIL", "Guildmaster Lars", "Woodcutting guild, Zeah", ANAGRAM),
	CLUE183("This anagram reveals who to speak to next: RATAI", "Taria", "Rimmington bush patch", "7", ANAGRAM),
	CLUE184("This anagram reveals who to speak to next: SLIDE WOMAN", "Wise Old Man", "Draynor Village", "28", ANAGRAM),
	CLUE185("This anagram reveals who to speak to next: BAIL TRIMS", "Brimstail", "West of Stronghold Slayer Cave", ANAGRAM),
	CLUE186("This anagram reveals who to speak to next: A BASIC ANTI POT", "Captain Tobias", "Port Sarim", "6", ANAGRAM),
	CLUE187("This anagram reveals who to speak to next: BAKER CLIMB", "Brambickle", "Trollweiss mountain", ANAGRAM),
	CLUE188("This anagram reveals who to speak to next: GOT A BOY", "Gabooty", "Centre of Tai Bwo Wannai", "11", ANAGRAM),
	CLUE189("This anagram reveals who to speak to next: AHA JAR", "Jaraah", "Duel Arena hosptial", ANAGRAM),
	CLUE190("This anagram reveals who to speak to next: CAR IF ICES", "Sacrifice", "Zul-Andra", ANAGRAM),
	CLUE191("This anagram reveals who to speak to next: OUR OWN NEEDS", "Nurse Wooned", "Shayzien House Infirmary", "52", ANAGRAM),
	CLUE192("This anagram reveals who to speak to next: TEN WIGS ON", "Wingstone", "Between Nardah & Agility Pyramid", ANAGRAM),
	CLUE193("This anagram reveals who to speak to next: I EVEN", "Nieve", "The slayer master in Gnome Stronghold", "2", ANAGRAM),
	CLUE194("This anagram reveals who to speak to next: ME AM THE CALC", "Cam the Camel", "Outside Duel Arena", ANAGRAM),
	CLUE195("This anagram reveals who to speak to next: SNAKES SO I SAIL", "Lisse Isaakson", "Neitiznot", "2", ANAGRAM),
	CLUE196("This anagram reveals who to speak to next: LAND DOOMD", "Odd Old Man", "Limestone mine northeast of Varrock", ANAGRAM),
	CLUE197("This anagram reveals who to speak to next: DUO PLUG", "Dugopul", "Graveyard on Ape Atoll", ANAGRAM),
	CLUE198("This anagram reveals who to speak to next: R SLICER", "Clerris", "Arceuus mine, Zeah", "738", ANAGRAM),
	CLUE199("This anagram reveals who to speak to next: MY MANGLE LAL", "Lammy Langle", "Hosidius House spirit tree patch", ANAGRAM),
	CLUE200("This anagram reveals who to speak to next: PEATY PERT", "Party Pete", "Falador Party Room", "None", ANAGRAM),
	CLUE201("Search the chest in Barbarian Village.", "The chest located in the house with a .", CRYPTIC),
	CLUE202("Search the crates in the outhouse of the long building in Taverley.", "Located in the small building attached by a fence to the main building. Climb over the stile.", CRYPTIC),
	CLUE203("Talk to Ermin.", "Ermin can be found on the 1st2nd floor[U.K. floor] of the tree house south-east of the Gnome Agility Course.", CRYPTIC),
	CLUE204("Aggie I see, Lonely and southern I feel I am neither inside nor outside the house yet no house would be complete without me. Your treasure lies beneath me.", "Dig outside the window of Aggies house in Draynor Village.", CRYPTIC),
	CLUE205("Ghostly bones.", "Kill an Ankou", CRYPTIC),
	CLUE206("Search through chests found in the upstairs of houses in eastern Falador.", "The house is located southwest of the Falador Party Room. There are two chests in the room, search the northern chest.", CRYPTIC),
	CLUE207("Let's hope you don't meet a watery death when you encounter this fiend.", "Kill a waterfiend.", CRYPTIC),
	CLUE208("The magic of 4 colours, an early experience you could learn. The large beast caged up top, rages, as his demised kin's loot now returns.", "Speak to Wizard Mizgog at the top of the Wizard's Tower south of Draynor.", CRYPTIC),
	CLUE209("Dobson is my last name, and with gardening I seek fame.", "Horacio, located in the garden of the Handelmort Mansion in East Ardougne.", CRYPTIC),
	CLUE210("This village has a problem with cartloads of the undead. Try checking the bookcase to find an answer.", "Search the bookcase by the doorway of the building just south east of the Shilo Village Gem Mine.", CRYPTIC),
	CLUE211("The cheapest water for miles around, but they react badly to religious icons.", "Search the crates in the General Store tent in the Bandit Camp", CRYPTIC),
	CLUE212("Try not to step on any aquatic nasties while searching this crate.", "Search the crate in Bailey's house on the Fishing Platform.", CRYPTIC),
	CLUE213("'See you in your dreams' said the vegetable man.", "Speak to Dominic Onion at the Nightmare Zone teleport spot.", CRYPTIC),
	CLUE214("Reflection is the weakness for these eyes of evil.", "Kill a basilisk", CRYPTIC),
	CLUE215("Search a bookcase in Lumbridge swamp.", "Located in Father Urhney's house.", CRYPTIC),
	CLUE216("Surround my bones in fire, ontop the wooden pyre. Finally lay me to rest, before my one last test.", "Kill a confused/lost barbarian to receive mangled bones. Construct and burn a pyre ship. Kill the ferocious barbarian spirit that spawns to receive a clue casket.", CRYPTIC),
	CLUE217("Between where the best are commemorated for a year, and a celebratory cup, not just for beer.", "Dig at the Clan Cup Trophy at Clan Wars.", CRYPTIC),
	CLUE218("Speak to Doric, who lives north of Falador.", "Doric is found north of Falador and east of the Taverley gate.", CRYPTIC),
	CLUE219("Speak to Arhein in Catherby.", "Arhein is just south of the Catherby bank.", CRYPTIC),
	CLUE220("Leader of the Yak City.", "Talk to Mawnis Burowgar in Neitiznot.", CRYPTIC),
	CLUE221("Search upstairs in the houses of Seers' Village for some drawers.", "Located in the house with the spinning wheel. South of the Seers' Village bank.", CRYPTIC),
	CLUE222("Surprising? I bet he is...", "Talk to Sir Prysin in Varrock Palace.", CRYPTIC),
	CLUE223("Fiendish cooks probably won’t dig the dirty dishes.", "Dig by the fire in the Rogues' Den.", CRYPTIC),
	CLUE224("My life was spared but these voices remain, now guarding these iron gates is my bane.", "Speak to the Key Master in Cerberus' Lair.", CRYPTIC),
	CLUE225("Search the boxes in one of the tents in Al Kharid.", "Search the crates in the tent east of the Silk trader.", CRYPTIC),
	CLUE226("Search the bookcase in the monastery.", "Search the southeastern bookcase at Edgeville Monastery.", CRYPTIC),
	CLUE227("One of several rhyming brothers, in business attire with an obsession for paper work.", "Speak to Piles in the Resource Area.", CRYPTIC),
	CLUE228("When you get tired of fighting, go deep, deep down until you need an antidote.", "Go to Yanille Agility dungeon and fall into the place with the poison spiders. Search the crate by the stairs leading up.", CRYPTIC),
	CLUE229("You'll have to plug your nose if you use this source of herbs.", "Kill an Aberrant spectre and pick up the casket", CRYPTIC),
	CLUE230("It seems to have reached the end of the line, and it's still empty.", "Search the carts in the northern part of the Dwarven Mine.", CRYPTIC),
	CLUE231("Someone watching the fights in the Duel Arena is your next destination.", "Talk to Jeed, found on the upper floors, at the Duel Arena.", CRYPTIC),
	CLUE232("Search the drawers on the first floor of a building overlooking Ardougne's Market.", "Climb the ladder in the house north of the market.", CRYPTIC),
	CLUE233("'A bag belt only?', he asked his balding brothers.", "Talk to Abbot Langley in the monastery", CRYPTIC),
	CLUE234("Search the bush at the digsite centre.", "The bush is on the east side of the first pathway towards the digsite from the Exam Centre.", CRYPTIC),
	CLUE235("Search the drawers upstairs in Falador's shield shop.", "Cassie's Shield Shop at the northern Falador entrance.", CRYPTIC),
	CLUE236("Generally speaking, his nose was very bent.", "Talk to General Bentnoze", CRYPTIC),
	CLUE237("Often sought out by scholars of histories past, find me where words of wisdom speak volumes.", "Speak to an examiner at the Exam Centre.", CRYPTIC),
	CLUE238("Go to this building to be illuminated, and check the drawers while you are there.", "The 2nd of the Lighthouse, Kill a Rellekka marketplace guard to obtain the key.", CRYPTIC),
	CLUE239("Talk to the barber in the Falador barber shop.", "The Hairdresser can be found in the barber shop, north of the west Falador bank.", CRYPTIC),
	CLUE240("Search the drawers in Falador's chain mail shop.", "Wayne's Chains - Chainmail Specialist store at the southern Falador walls.", CRYPTIC),
	CLUE241("Dig near some giant mushrooms behind the Grand Tree.", "Dig near the red mushrooms northwest of the Grand Tree.", CRYPTIC),
	CLUE242("If a man carried my burden, he would break his back. I am not rich, but leave silver in my track. Speak to the keeper of my trail.", "Speak to Gerrant in the fish shop in Port Sarim.", CRYPTIC),
	CLUE243("Speak to Gaius in Taverley.", "Gaius is found at the northwest corner in Taverley.", CRYPTIC),
	CLUE244("Speak to Jatix in Taverley.", "Jatix is found in the middle of Taverley.", CRYPTIC),
	CLUE245("My name is like a tree, yet it is spelt with a 'g'. Come see the fur which is right near me.", "Speak to Wilough, next to the Fur Merchant in Varrock Square.", CRYPTIC),
	CLUE246("AIR 2331", "Dig 2 steps East and 1 step south of the center of the fairy ring.", CRYPTIC),
	CLUE247("Pentagrams and demons, burnt bones and remains, I wonder what the blood contains.", "Dig under the blood rune spawn next the the Demonic Ruins.", CRYPTIC),
	CLUE248("Search the drawers above Varrock's shops.", "Located upstairs in Thessalia's Fine Clothes shop in Varrock.", CRYPTIC),
	CLUE249("Search the drawers in one of Gertrude's bedrooms.", "Kanel's bedroom (southeastern room), outside of west Varrock.", CRYPTIC),
	CLUE250("Surviving.", "Talk to Sir Vyvin on the 3rd floor of Falador castle.", CRYPTIC),
	CLUE251("There is no 'worthier' lord.", "Speak to Lord Iorwerth in the elven camp near Prifddinas", CRYPTIC),
	CLUE252("W marks the spot.", "Dig in the middle of the Warriors' Guild entrance hall", CRYPTIC),
	CLUE253("ALP 1140", "Dig 1 step east and 3 steps south of the center of the fairy ring.", CRYPTIC),
	CLUE254("Search the boxes in the goblin house near Lumbridge.", "Goblin house on the eastern side of the river.", CRYPTIC),
	CLUE255("Dig where the forces of Zamorak and Saradomin collide.", "Dig next to the law rift in the Abyss", CRYPTIC),
	CLUE256("Under a giant robotic bird that cannot fly.", "Dig next to the terrorbird display in the south exhibit of Varrock Museum's basement.", CRYPTIC),
	CLUE257("Great demons, dragons, and spiders protect this blue rock, beneath which, you may find what you seek.", "Dig by the runite rock in the Lava Maze Dungeon", CRYPTIC),
	CLUE258("The King's magic won't be wasted by me.", "Talk to the Guardian mummy inside the Pyramid Plunder minigame in Sophanem", CRYPTIC),
	CLUE259("Rotting next to a ditch. Dig next to the fish", "Dig next to a fishing spot on the south-east side of Burgh de Rott.", CRYPTIC),
	CLUE260("Speak to the Lady of the Lake.", "Talk to the Lady of the Lake in Taverley.", CRYPTIC),
	CLUE261("Search the crates in the Port Sarim Fishing shop.", "Search the crates, by the door, in Gerrant's Fishy Business in Port Sarim.", CRYPTIC),
	CLUE262("Read 'How to breed scorpions.' By O.W.Thathurt.", "Search the northern bookcase on the 1st2nd floor[U.K. floor] of the Sorcerer's Tower.", CRYPTIC),
	CLUE263("I wonder how many bronze swords he has handed out.", "Talk to Vannaka. He can be found in Edgeville Dungeon.", CRYPTIC),
	CLUE264("Must be full of railings.", "Search the boxes around the hut where the broken Dwarf Cannon is, close to the start of the Dwarf Cannon quest.", CRYPTIC),
	CLUE265("BLP 6200", "Dig 6 steps north and 2 steps east of the center of the fairy ring.", CRYPTIC),
	CLUE266("My giant guardians below the market streets would be fans of rock and roll, if only they could grab hold of it. Dig near my green bubbles!", "Dig near the cauldron by Moss Giants under Varrock Sewers", CRYPTIC),
	CLUE267("BJR 1123", "Dig 1 steps south and 2 steps west of the center of the fairy ring.", CRYPTIC),
	CLUE268("Speak to Hajedy.", "Hajedy is found by the cart, located just south of the Brimhaven docks.", CRYPTIC),
	CLUE269("Speak to Kangai Mau.", "Kangai Mau is found in the Shrimp and Parrot in Brimhaven.", CRYPTIC),
	CLUE270("Varrock is where I reside not the land of the dead, but I am so old, I should be there instead. Let's hope your reward is as good as it says, just 1 gold one and you can have it read.", "Talk to Gypsy Aris, West of varrock main square.", CRYPTIC),
	CLUE271("I am a token of the greatest love. I have no beginning or end. My eye is red, I can fit like a glove. Go to the place where it's money they lend, And dig by the gate to be my friend.", "Dig by the gate in the basement of the West Varrock bank.", CRYPTIC),
	CLUE272("Speak to a referee.", "Talk to a Gnome ball referee found on the Gnome ball field in the Gnome Stronghold.", CRYPTIC),
	CLUE273("This crate holds a better reward than a broken arrow.", "Inside the Ranging Guild. Search the crate behind the northern most building.", CRYPTIC),
	CLUE274("Speak to the staff of Sinclair mansion.", "Speak to Louisa, on the ground floor, found at the Sinclair Mansion.", CRYPTIC),
	CLUE275("Search the crates in a house in Yanille that has a piano.", "The house is located northwest of the bank.", CRYPTIC),
	CLUE276("When no weapons are at hand, now it is time to reflect, in Saradomin's name! Redemption draws closer...", "On Entrana, search the southern drawer in the house with the cooking range.", CRYPTIC),
	CLUE277("AIQ 0440", "Dig 4 steps east and 4 steps south of the center of the fairy ring.", CRYPTIC),
	CLUE278("CKP 0224", "Dig 2 steps south and 2 steps west of the center of the fairy ring.", CRYPTIC),
	CLUE279("Search the Coffin in Edgeville.", "Search the coffin located by the Wilderness teleport lever.", CRYPTIC),
	CLUE280("Search the drawers in the house next to the Port Sarim mage shop.", "House east of Betty's. Contains a cooking sink.", CRYPTIC),
	CLUE281("A great view - watch the rapidly drying hides get splashed. Check the box you are sitting on.", "Almera's House north of Baxtorian Falls, search boxes on the 2nd floor.", CRYPTIC),
	CLUE282("He knows just how easy it is to lose track of time.", "Speak to brother Kojo in the Clock Tower.", CRYPTIC),
	CLUE283("With a name like that, you'd expect a little more than just a few scimitars.", "Speak to Daga on Ape Atoll.", CRYPTIC),
	CLUE284("Strength potions with red spiders' eggs? He is quite a herbalist.", "Talk to Apothecary in the South-western Varrock. (the) apothecary is just north-west of the Varrock Swordshop.", CRYPTIC),
	CLUE285("Robin wishes to see your finest range equipment.", "Robin at the inn in Port Phasmatys. Speak to him with +182 in ranged attack bonus.", CRYPTIC),
	CLUE286("You will need to under-cook to solve this one.", "Search the crate in the Lumbridge basement.", CRYPTIC),
	CLUE287("Talk to a party-goer in Falador.", "Lucy is the bartender on the 1st2nd floor[U.K. floor] of the party room.", CRYPTIC),
	CLUE288("Search through some drawers found in Taverley's houses.", "The south-eastern most house, south of Jatix's Herblore Shop.", CRYPTIC),
	CLUE289("Green is the colour of my death as the winter-guise, I swoop towards the ground.", "Players need to slide down to where Trollweiss grows on Trollweiss Mountain.", CRYPTIC),
	CLUE290("46 is my number. My body is the colour of burnt orange and crawls among those with eight. Three mouths I have, yet I cannot eat. My blinking blue eye hides my grave.", "Sapphire respawn in the Spider's Nest, lvl 46 Wilderness. Dig under the sapphire spawn.", CRYPTIC),
	CLUE291("Anger Abbot Langley.", "Speak to Abbot Langley while you have a negative prayer bonus", CRYPTIC),
	CLUE292("Dig where only the skilled, the wealthy, or the brave can choose not to visit again.", "Dig at Lumbridge spawn", CRYPTIC),
	CLUE293("I live in a deserted crack collecting soles.", "Enter the crack west of Nardah Rug merchant, and talk to the Genie.", CRYPTIC),
	CLUE294("'Small shoe.' Often found with rod on mushroom.", "Talk to any Gnome trainer in the agility area of the Tree Gnome Stronghold.", CRYPTIC),
	CLUE295("Scattered coins and gems fill the floor. The chest you seek is in the north east.", "Kill the King Black Dragon for a key (elite), and then open the closed chest in the NE corner of the lair.", CRYPTIC),
	CLUE296("Search the crate in the left-hand tower of Lumbridge Castle.", "Located on the first floor of the southern tower at the Lumbridge Castle entrance.", CRYPTIC),
	CLUE297("A ring of water surrounds 4 powerful rings. Dig by the ladder that is located there.", "Dig by the ladder leading to the Dagannoth Kings room in the Waterbirth Island Dungeon.", CRYPTIC),
	CLUE298("If you look closely enough, it seems that the archers have lost more than their needles.", "Search the haystack by the south corner of the Rangers' Guild", CRYPTIC),
	CLUE299("This place sure is a mess.", "Ewesey is located in the Hosidius House mess hall in Great Kourend.", CRYPTIC),
	CLUE300("Probably filled with books on magic.", "Search the bookcase in the basement of Wizard's Tower.", CRYPTIC),
	CLUE301("Here, there are tears, but nobody is crying. Speak to the guardian and show off your alignment to balance.", "Talk to Juna while wearing three Guthix related items.", CRYPTIC),
	CLUE302("You might have to turn over a few stones to progress.", "Kill a rock crab and pick up the casket (elite) that it drops.", CRYPTIC),
	CLUE303("DKS 2310", "Dig 2 steps north, 3 steps east, and 1 step south of the center of the fairy ring.", CRYPTIC),
	CLUE304("Dig under Razorlor's toad batta.", "Dig on the toad batta spawn in Tarn's Lair.", CRYPTIC),
	CLUE305("Search through some drawers in the upstairs of a house in Rimmington.", "On the first floor of the house north of Hetty the Witch's house in Rimmington.", CRYPTIC),
	CLUE306("Four blades I have, yet draw no blood; Still I turn my prey to powder. If you are brave, come search my roof; It is there my blades are louder.", "Lumbridge windmill, search the crates on the top floor.", CRYPTIC),
	CLUE307("Talk to Cassie in Falador.", "Cassie is found just south-east of the northern Falador gate.", CRYPTIC),
	CLUE308("Faint sounds of 'Arr', fire giants found deep, the eastern tip of a lake, are the rewards you could reap.", "Dig south of the pillar at the end of the Deep Wilderness Dungeon.", CRYPTIC),
	CLUE309("If you're feeling brave, dig beneath the dragon's eye.", "Dig below the mossy rock under the Viyeldi caves.", CRYPTIC),
	CLUE310("In a town where the guards are armed with maces, search the upstairs rooms of the Public House.", "Search the drawers in the pub north of Ardougne Castle. Kill a Guard dog at Handelmort Mansion to obtain the key.", CRYPTIC),
	CLUE311("Search the tents in the Imperial Guard camp in Burthorpe for some boxes.", "Search in the tents in northwest corner of the camp.", CRYPTIC),
	CLUE312("Dig where 4 siblings and I all live with our evil overlord.", "Dig in the chicken pen inside the Champion's Guild", CRYPTIC),
	CLUE313("This crate is mine, all mine, even if it is in the middle of the desert.", "Center of desert Mining Camp. Search the crates. Requires the metal key from Tourist Trap to enter.", CRYPTIC),
	CLUE314("Buried beneath the ground, who knows where it's found. Lucky for you, A man called Jorral may have a clue.", "Speak to Jorral to receive a strange device.", CRYPTIC),
	CLUE315("A dwarf, approaching death, but very much in the light.", "Thorgel at the entrance to the Death altar", CRYPTIC),
	CLUE316("In a village made of bamboo, look for some crates under one of the houses.", "Search the crate by the house at the northern point of the broken jungle fence in Tai Bwo Wannai.", CRYPTIC),
	CLUE317("Search the boxes of Falador's general store.", "Falador general store.", CRYPTIC),
	CLUE318("You must be 100 to play with me.", "Speak to the Veteran boat squire at Pest Control", CRYPTIC),
	CLUE319("Three rule below and three sit at top. Come dig at my entrance.", "Dig in front of the entrance to the Waterbirth Island Dungeon.", CRYPTIC),
	CLUE320("Search the crates in the Barbarian Village helmet shop.", "Peska's Helmet Shop in Barbarian Village.", CRYPTIC),
	CLUE321("BIP 7013", "Dig 6 steps north and 3 steps west of the center of the fairy ring.", CRYPTIC),
	CLUE322("Search the drawers in the ground floor of a shop in Yanille.", "Search the drawers in Yanille's hunting shop.", CRYPTIC),
	CLUE323("Speak to Donovan, the Family Handyman.", "Donovan the Family Handyman is found on the 2nd floor of Sinclair Mansion.", CRYPTIC),
	CLUE324("Search the drawers of houses in Burthorpe.", "Inside Hild's house in the northeast corner of Burthorpe.", CRYPTIC),
	CLUE325("Where safe to speak, the man who offers the pouch of smallest size wishes to see your alignment.", "Speak to the Mage of Zamorak south of the Rune Shop in Varrock while wearing three zamorakian items", CRYPTIC),
	CLUE326("And so on, and so on, and so on. Walking from the land of many unimportant things leads to a choice of paths.", "Dig on Etceteria next to the Evergreen tree in front of the castle walls.", CRYPTIC),
	CLUE327("Search the crates in the guard house of the northern gate of East Ardougne.", "The guard house is northeast of the Handelmort Mansion.", CRYPTIC),
	CLUE328("Go to the village being attacked by trolls, search the drawers in one of the houses.", "Go to Dunstan's house in the northeast corner of Burthorpe. Kill Penda in the Toad and Chicken to obtain the key.", CRYPTIC),
	CLUE329("You'll get licked.", "Kill a Bloodveld.", CRYPTIC),
	CLUE330("She's small but can build both literally and figuratively, as long as you have their favour", "Speak to Lovada south of the Lovakengj House blast mine", CRYPTIC),
	CLUE331("Search for a crate in Varrock Castle.", "Search the crate in the corner of the kitchen in Varrock Castle.", CRYPTIC),
	CLUE332("Dig in front of the icy arena where 1 of 4 was fought.", "Where you fought Kamil from Desert Treasure.", CRYPTIC),
	CLUE333("Mine was the strangest birth under the sun. I left the crimson sack, yet life had not begun. Entered the world, and yet was seen by none.", "Inside Karamja Volcano, dig directly underneath the Red spiders' eggs respawn.", CRYPTIC),
	CLUE334("Talk to Ambassador Spanfipple in the White Knights Castle.", "Ambassador Spanfipple can be found roaming on the 2nd floor of the White Knights Castle.", CRYPTIC),
	CLUE335("You'll need to look for a town with a central fountain. Look for a locked chest in the town's chapel.", "Search the chest by the stairs in the Varrock church. Kill a Monk in Ardougne Monastery to obtain the key.", CRYPTIC),
	CLUE336("Speak to a Wyse man.", "Talk to Wyson the gardener at Falador Park.", CRYPTIC),
	CLUE337("Even the seers say this clue goes right over their heads.", "Search the crate on the Seers Agility Course in Seers Village", CRYPTIC),
	CLUE338("Speak to Roavar.", "Talk to Roavar in the Canifis tavern.", CRYPTIC),
	CLUE339("DIP 8511", "Dig 7 steps north and 4 steps east of the center of the fairy ring.", CRYPTIC),
	CLUE340("Search the drawers upstairs of houses in eastern part of Falador.", "House is located east of the eastern Falador bank and south of the fountain. The house is indicated by the icon on the minimap.", CRYPTIC),
	CLUE341("Search the drawers found upstairs in East Ardougne's houses.", "Upstairs of the pub north of the Ardougne Castle.", CRYPTIC),
	CLUE342("Probably filled with wizards socks.", "Search the drawers in the basement of the Wizard's Tower south of Draynor Village. Kill one of the Wizards for the key.", CRYPTIC),
	CLUE343("In a town where wizards are known to gather, search upstairs in a large house to the north.", "Search the chest, upstairs, in the house north of Yanille Wizards' Guild. Open the chest to receive the message: The chest is locked! An inscription on the chest reads: Stand by your man. Head downstairs to kill a Man.", CRYPTIC),
	CLUE344("I am the one who watches the giants. The giants in turn watch me. I watch with two while they watch with one. Come seek where I may be.", "Speak to Kamfreena on the top floor of the Warriors' Guild.", CRYPTIC),
	CLUE345("I have many arms but legs, I have just one, I have little family but my seed, You can grow on, I am not dead, yet I am but a spirit, and my power on your quests, you will earn the right to free it.", "Spirit Tree in Tree Gnome Village", CRYPTIC),
	CLUE346("Show this to Sherlock", "Sherlock can be found south of Seer's Village.", CRYPTIC),
	CLUE347("The far north eastern corner where 1 of 4 was defeated, the shadows still linger.", "Dig on the northeastern-most corner of the Shadow Dungeon. Bring a ring of visibility.", CRYPTIC),
	CLUE348("Search a wardrobe in Draynor.", "Go to Aggie's house and search the wardrobe in northern wall.", CRYPTIC),
	CLUE349("Speak to Rusty north of Falador", "Rusty can be found northeast of Falador on the way to the Mind altar.", CRYPTIC),
	CLUE350("Search the drawers in a house in Draynor Village.", "The drawer is located in northern house in Draynor Village.", CRYPTIC),
	CLUE351("Dig between some ominous stones in Falador.", "Three standing stones inside a walled area. East of the northern Falador gate.", CRYPTIC),
	CLUE352("I watch the sea. I watch you fish. I watch your tree.", "Speak to Ellena at Catherby fruit tree patch.", CRYPTIC),
	CLUE353("The mother of the reptilian sacrifice.", "Talk to Zul-Cheray in a house near the sacrificial boat at Zul-Andra.", CRYPTIC),
	CLUE354("In the city where merchants are said to have lived, talk to a man with a splendid cape, but a hat dropped by goblins.", "Talk to the Head chef in Cooks' Guild west of Varrock.", CRYPTIC),
	CLUE355("Search the boxes in a shop in Taverley.", "The box inside Gaius' Two Handed Shop.", CRYPTIC),
	CLUE356("I lie beneath the first descent to the holy encampment.", "Dig immediately after climbing down the first set of rocks towards Saradomin's encampment within the God Wars Dungeon.", CRYPTIC),
	CLUE357("I lie lonely and forgotten in mid wilderness, where the dead rise from their beds. Feel free to quarrel and wind me up and dig while you shoot their heads.", "Directly under the crossbow respawn in the Graveyard of Shadows in level 18 Wilderness.", CRYPTIC),
	CLUE358("Search the upstairs drawers of a house in a village where pirates are known to have a good time.", "The house in the southeast corner of Brimhaven, northeast of Davon's Amulet Store. Kill any Pirate located around Brimhaven to obtain the key.", CRYPTIC),
	CLUE359("Covered in shadows, the centre of the circle is where you will find the answer.", "Dig in the centre of Mort'ton, where the roads intersect", CRYPTIC),
	CLUE360("A crate found in the tower of a church is your next location.", "Climb the ladder and search the crates on the 1st floor in the Church in Ardougne", CRYPTIC),
	CLUE361("Search the crates in the Dwarven mine.", "Search the east of the Ice Mountain ladder entrance in the Drogo's Mining Emporium.", CRYPTIC),
	CLUE362("Search the chest in the Duke of Lumbridge's bedroom.", "The Duke's room is on the 2nd floor in Lumbridge Castle.", CRYPTIC),
	CLUE363("Talk to the Doomsayer.", "Doomsayer can be found just north of Lumbridge Castle entrance.", CRYPTIC),
	CLUE364("Search the crates in Canifis.", "Search inside the shop, Rufus' Meat Emporium.", CRYPTIC),
	CLUE365("Search the chests upstairs in Al Kharid Palace.", "The chest is located, in the northeast corner, on the first floor of the Al Kharid Palace", CRYPTIC),
	CLUE366("Speak to Hans to solve the clue.", "Hans can be found at Lumbridge Castle.", CRYPTIC),
	CLUE367("Speak to Ned in Draynor Village.", "Ned is found north or the Draynor bank.", CRYPTIC),
	CLUE368("Search the boxes just outside the Armour shop in East Ardounge.", "Outside Zenesha's Plate Mail Body Shop", CRYPTIC),
	CLUE369("Surrounded by white walls and gems.", "Talk to Herquin, the gem store owner in Falador.", CRYPTIC),
	CLUE370("Talk to the mother of a basement dwelling son.", "Evil Dave's mother, Doris is located in the house west of Edgeville bank.", CRYPTIC),
	CLUE371("THEY'RE EVERYWHERE!!!! But they were here first. Dig for treasure where the ground is rich with ore.", "Dig at Barbarian Village, next to the Stronghold of Security.", CRYPTIC),
	CLUE372("One of the sailors in Port Sarim is your next destination.", "Speak to Captain Tobias on the docks of Port Sarim.", CRYPTIC),
	CLUE373("His head might be hollow, but the crates nearby are filled with surprises.", "Search the crates near the Clay golem in the ruins of Uzer.", CRYPTIC),
	CLUE374("Monk's residence in the far west. See robe storage device.", "Search the drawers upstairs in the chapel found on the southern coast of Great Kourend's Hosidius House. Directly south of the player-owned house portal.", CRYPTIC),
	CLUE375("Search the drawers in Catherby's Archery shop.", "Hickton's Archery Emporium in Catherby.", CRYPTIC),
	CLUE376("The hand ain't listening.", "Talk to The Face located by the manhole just north of the Port Sarim fishing shop.", CRYPTIC),
	CLUE377("Search the chest in the left-hand tower of Camelot Castle.", "Located on the 2nd floor of the western tower of Camelot.", CRYPTIC),
	CLUE378("Search the boxes in the house near the south entrance to Varrock.", "The first house on the left when entering the city from the southern entrance.", CRYPTIC),
	CLUE379("A Guthixian ring lies between two peaks. Search the stones and you'll find what you seek.", "Search the stones several steps west of the Guthixian stone circle in Taverley", CRYPTIC),
	CLUE380("Kill the spiritual, magic and godly whilst representing their own god", "Kill a spiritual mage in the God Wars Dungeon", CRYPTIC),
	CLUE381("Search the crates near a cart in Varrock.", "South east of Varrock Palace, south of the tree farming patch.", CRYPTIC),
	CLUE382("Search the crates in Draynor Manor.", "Top floor of the manor", CRYPTIC),
	CLUE383("Anger those who adhere to Saradomin's edicts to prevent travel.", "Port Sarim Docks, try to charter a ship to Entrana with armour or weapons equipped.", CRYPTIC),
	CLUE384("South of a river in a town surrounded by the undead, what lies beneath the furnace?", "Dig in front of the Shilo Village furnace.", CRYPTIC),
	CLUE385("You were 3 and I was the 6th. Come speak to me.", "Speak to Vannaka in Edgeville Dungeon.", CRYPTIC),
	CLUE386("Look in the ground floor crates of houses in Falador.", "The house east of the east bank.", CRYPTIC),
	CLUE387("Come to the evil ledge, Yew know yew want to. Try not to get stung.", "Dig in Edgeville, just east of the Southern Yew tree.", CRYPTIC),
	CLUE388("My home is grey, and made of stone; A castle with a search for a meal. Hidden in some drawers I am, across from a wooden wheel.", "Open the drawers inside the room with the spinning wheel on the first floor of Lumbridge Castle.", CRYPTIC),
	CLUE389("The dead, red dragon watches over this chest. He must really dig the view.", "Search the chest underneath the Red Dragon's head in the Exam Centre. Kill a MALE Barbarian in Barbarian Village or Barbarian Outpost to receive the key.", CRYPTIC),
	CLUE390("Right on the blessed border, cursed by the evil ones. On the spot inaccessible by both; I will be waiting. The bugs imminent possession holds the answer.", "B I P. Dig right under the fairy ring.", CRYPTIC),
	CLUE391("Talk to the Squire in the White Knights' castle in Falador.", "The squire is located in the courtyard of the White Knights' Castle.", CRYPTIC),
	CLUE392("Thanks Grandma!", "Tynan can be found in the north-east corner of Piscarilius House in Great Kourend.", CRYPTIC),
	CLUE393("Search chests found in the upstairs of shops in Port Sarim.", "Search the chest in the upstairs of Wydin's Food Store, on the east wall.", CRYPTIC),
	CLUE394("In a town where everyone has perfect vision, seek some locked drawers in a house that sits opposite a workshop.", "The drawers is in Seers' Village in the house south of the Elemental Workshop entrance. Kill any Chicken to obtain a key.", CRYPTIC),
	CLUE395("Search the crate in the Toad and Chicken pub.", "The Toad and Chicken pub is located in Burthorpe.", CRYPTIC),
	CLUE396("I wouldn't wear this jean on my legs.", "Talk to father Jean in the Hosidius church", CRYPTIC),
	CLUE397("Search the crates in the shed just north of East Ardougne.", "The crates in the shed north of the northern Ardougne bank.", CRYPTIC),
	CLUE398("This aviator is at the peak of his profession.", "Captain Bleemadge, the gnome glider pilot, is found at the top of White Wolf Mountain.", CRYPTIC),
	CLUE399("The treasure is buried in a small building full of bones. Here is a hint: it's not near a graveyard.", "In the western building near the Limestone quarry east of Varrock. Dig south of the box of bones in the smaller building.", CRYPTIC),
	CLUE400("Speak to the bartender of the Blue Moon Inn in Varrock.", "Talk to the bartender in Blue Moon Inn in Varrock.", CRYPTIC),
	CLUE401("Search the crate near a cart in Port Khazard.", "Search by the southern Khazard General Store in Port Khazard.", CRYPTIC),
	CLUE402("Search the crates in East Ardougne's general store.", "Located south of the Ardounge church.", CRYPTIC),
	CLUE403("Come brave adventurer, your sense is on fire. If you talk to me, it's an old god you desire.", "Speak to Viggora", CRYPTIC),
	CLUE404("Stop crying! Talk to the head.", "Talk to the Head mourner in the mourner headquarters in West Ardougne", CRYPTIC),
	CLUE405("A town with a different sort of night-life is your destination. Search for some crates in one of the houses.", "Search the crate inside of the clothes shop in Canifis.", CRYPTIC),
	CLUE406("The beasts to my east snap claws and tails, The rest to my west can slide and eat fish. The force to my north will jump and they'll wail, Come dig by my fire and make a wish.", "Dig by the torch in the Ardougne Zoo, between the penguins and the scorpions.", CRYPTIC),
	CLUE407("2 musical birds. Dig in front of the spinning light.", "Dig in front of the spinning light in Ping and Pong's room inside the Iceberg", CRYPTIC),
	CLUE408("His bark is worse than his bite.", "Speak to the Barker at Canifis's Barkers' Haberdashery.", CRYPTIC),
	CLUE409("Search the wheelbarrow in Rimmington mine.", "The Rimmington mining site is located north of Rimmington.", CRYPTIC),
	CLUE410("In a town where thieves steal from stalls, search for some drawers in the upstairs of a house near the bank.", "Kill any Guard located around East Ardougne for a medium key. Then search the drawers in the upstairs hallway of Jerico's house, which is the house with pigeon cages located south of the northern East Ardougne bank.", CRYPTIC),
	CLUE411("Belladonna, my dear. If only I had gloves, then I could hold you at last.", "Talk to Tool Leprechaun at Draynor Manor", CRYPTIC),
	CLUE412("Impossible to make angry", "Speak to Abbot Langley", CRYPTIC),
	CLUE413("Identify the back of this over-acting brother. (He's a long way from home.)", "Talk to Hamid, the monk at the altar in the Duel Arena", CRYPTIC),
	CLUE414("Search the crates in Horvik's armoury.", "Horvik's in Varrock", CRYPTIC),
	CLUE415("Ghommal wishes to be impressed by how strong your equipment is.", "Talk to Ghommal at the Warrior's Guild while wearing sufficiently strong equipment", CRYPTIC),
	CLUE416("Find a crate close to the monks that like to paaarty!", "The crate is in the east side of the Kandarin monastery, near Brother Omad", CRYPTIC),
	CLUE417("Gold I see, yet gold I require. Give me 875 if death you desire.", "Speak to Saniboch at the Brimhaven Dungeon entrance.", CRYPTIC),
	CLUE418("Shhhh!", "Speak to Logosia in the Arceuus House Library's ground floor.", CRYPTIC),
	CLUE419("Speak to Sir Kay in Camelot Castle.", "Sir Kay can be found in the courtyard at Camelot castle.", CRYPTIC),
	CLUE420("Snah? I feel all confused, like one of those cakes...", "Talk to Hans roaming around Lumbridge Castle.", CRYPTIC),
	CLUE421("Search for a crate on the ground floor of a house in Seers' Village.", "Search inside Phantuwti Fanstuwi Farsight's house, located south of the pub in Seers' Village.", CRYPTIC),
	CLUE422("Salty Peter", "Talk to Konoo who is digging saltpeter in the Hosidius district in Zeah.", CRYPTIC),
	CLUE423("Talk to Zeke in Al Kharid.", "Zeke is the owner of the scimitar shop in Al Kharid.", CRYPTIC),
	CLUE424("Guthix left his mark in a fiery lake, dig at the tip of it.", "Dig at the tip of the lava lake that is shaped like a Guthixian symbol, west of the Mage Arena.", CRYPTIC),
	CLUE425("Search the drawers in the upstairs of a house in Catherby.", "Perdu's house in Catherby.", CRYPTIC),
	CLUE426("Speak to Sarah at Falador farm.", "Talk to Sarah at Falador farm, north of Port Sarim.", CRYPTIC),
	CLUE427("I burn between heroes and legends.", "Speak to the Candle maker in Catherby.", CRYPTIC),
	CLUE428("Citric cellar.", "Speak to Heckel Funch on the first floor in the Grand Tree.", CRYPTIC),
	CLUE429("Search a crate in the Haymaker's arms.", "Search the crate in the north-east corner of The Haymaker's Arms tavern east of the Woodcutting Guild.", CRYPTIC),
	CLUE430("Come have a cip with this great soot covered denizen.", "Talk to Miner Magnus east of the fairy ring CIP. Answer: 8", CRYPTIC),
	CLUE431("Desert insects is what I see, Taking care of them was my responsibility. Your solution is found by digging near me.", "Dig next to the Entomologist, Kalphite area, Stronghold Slayer Cave.", CRYPTIC),
	CLUE432("Search the crates in most north-western house in Al Kharid.", "Search the crates in the house, marked with a icon, southeast of the gem stall.", CRYPTIC),
	CLUE433("You will have to fly high where a sword cannot help you.", "Kill an Aviansie.", CRYPTIC),
	CLUE434("A massive battle rages beneath so be careful when you dig by the large broken crossbow.", "NE of the God Wars Dungeon entrance, climb the rocky handholds & dig by large crossbow.", CRYPTIC),
	CLUE435("Search a bookcase in the Wizards tower.", "The bookcase located on the ground floor.", CRYPTIC),
	CLUE436("Mix yellow with blue and add heat, make sure you bring protection.", "Kill a green dragon.", CRYPTIC),
	CLUE437("Speak to Ellis in Al Kharid.", "Ellis is tanner just north of Al Kharid bank.", CRYPTIC),
	CLUE438("Search the chests in the Dwarven Mine.", "The chest is on the western wall, where Hura's Crossbow Shop is, in the Dwarven Mine.", CRYPTIC),
	CLUE439("Falo the bard wants to see you.", "Speak to Falo the Bard", CRYPTIC),
	CLUE440("Search the crates in a bank in Varrock.", "Search in the basement of the West Varrock bank.", CRYPTIC),
	CLUE441("In a while...", "Kill a crocodile.", CRYPTIC),
	CLUE442("A chisel and hammer reside in his home, strange for one of magic. Impress him with your magical equipment.", "Wizard Cromperty NE, East Ardougne. +100 magic attack bonus needed", CRYPTIC),
	CLUE443("You have all of the elements available to solve this clue. Fortunately you do not have to go as far as to stand in a draft.", "Search the crate, west of the Air Elementals, inside the Elemental Workshop.", CRYPTIC),
	CLUE444("Search the bucket in the Port Sarim jail.", "Talk to Shantay & identify yourself as an outlaw, refuse to pay the 5gp fine twice and you will be sent to the Port Sarim jail.", CRYPTIC),
	CLUE445("A demon's best friend holds the next step of this clue.", "Kill a hellhound", CRYPTIC),
	CLUE446("A reck you say; let's pray there aren't any ghosts.", "Speak to Father Aereck in Lumbridge.", CRYPTIC),
	CLUE447("Search for a crate in a building in Hemenster.", "House north of the Fishing Contest quest area. West of Grandpa Jack.", CRYPTIC),
	CLUE448("Speak to Ulizius.", "Ulizius is the monk who guards the gate into Mort Myre Swamp.", CRYPTIC),
	CLUE449("Dig in the centre of a great city of 5 districts.", "Dig in front of the large statue in the centre of Great Kourend.", CRYPTIC),
	CLUE450("Hopefully this set of armor will help you to keep surviving.", "Speak to Sir Vyvin while wearing a white full helm, platebody, and platelegs.", CRYPTIC),
	CLUE451("North of the best monkey restaurant on Karamja, look for the centre of the triangle of boats and search there", "The crate on the dock to the west of the fishing site on the Northern shore of Karamja.", CRYPTIC),
	CLUE452("The beasts retreat, for their Queen is gone; the song of this town still plays on. Dig near the birthplace of a blade, be careful not to melt your spade.", "Dig in front of the small furnace in the Piscatoris Fishing Colony.", CRYPTIC),
	CLUE453("CIS 0009", "Dig 9 steps west of the center of the fairy ring.", CRYPTIC),
	CLUE454("Darkness wanders around me, but fills my mind with knowledge.", "Speak to Biblia on the Arceuus House Library's top floor.", CRYPTIC),
	CLUE455("The keeper of Melzars...Spare? Skeleton? Anar?", "Speak to Oziach in Edgeville", CRYPTIC),
	CLUE456("I would make a chemistry joke, but I'm afraid I wouldn't get a reaction.", "Talk to Chemist in Rimmington", CRYPTIC),
	CLUE457("Talk to the bartender of the Rusty Anchor in Port Sarim.", "The Rusty Anchor is located in the north of Port Sarim.", CRYPTIC),
	CLUE458("How many Banana Trees are there in the plantation?", "33", CHALLENGE),
	CLUE459("White knights are superior to black knights. 2 white knights can handle 3 black knights. How many knights do we need for an army of 981 black knights?", "654", CHALLENGE),
	CLUE460("How many round tables can be found on this floor of the library?", "9", CHALLENGE),
	CLUE461("If I have 1014 flax, and I spin a third of them into bowstring, how many flax do I have left?", "676", CHALLENGE),
	CLUE462("How many arctic logs are required to make a large fremennik round shield?", "2", CHALLENGE),
	CLUE463("What is the next number? 12, 13, 15, 17, 111, 113, 117, 119, 123....?", "129", CHALLENGE),
	CLUE464("Please solve this for x: 7x - 28 = 21", "7", CHALLENGE),
	CLUE465("SIX LEGS! All of them have six! There are 25 of them! How many legs?", "150", CHALLENGE),
	CLUE466("If I have 303 bananas, and share them between 31 friends evenly, only handing out full bananas. How many will I have left over?", "24", CHALLENGE),
	CLUE467("How many houses have a cross on the door?", "20", CHALLENGE),
	CLUE468("How many ships are there docked at Port Sarim currently?", "6", CHALLENGE),
	CLUE469("How many animals are in the Ardougne Zoo?", "40", CHALLENGE),
	CLUE470("How many injured soldiers are in the tents?", "52", CHALLENGE),
	CLUE471("How many flowers are in the clearing below this platform?", "13", CHALLENGE),
	CLUE472("What is the next number in the sequence? 1, 11, 21, 1211, 111221, 312211", "13112221", CHALLENGE),
	CLUE473("Double the miles before the initial Dorgeshuun veteran.", "2,505", CHALLENGE),
	CLUE474("How many cannons are on this here castle?", "5", CHALLENGE),
	CLUE475("How many rifts are found here in the abyss?", "13", CHALLENGE),
	CLUE476("How many fishermen are there on the fishing platform?", "11", CHALLENGE),
	CLUE477("What is 40 divided by 1/2 plus 15?", "95", CHALLENGE),
	CLUE478("How many items can carry water in RuneScape?", "6", CHALLENGE),
	CLUE479("How many reward points does a herb box cost?", "9,500", CHALLENGE),
	CLUE480("How many Suqah inhabit Lunar isle?", "25", CHALLENGE),
	CLUE481("How many snakeskins are needed in order to craft 44 boots, 29 vambraces and 34 bandanas?", "666", CHALLENGE),
	CLUE482("How many gravestones are in the church graveyard?", "19", CHALLENGE),
	CLUE483("How many natural fires burn in the Rogue's Den?", "2", CHALLENGE),
	CLUE484("How many scorpions live under the pit?", "28", CHALLENGE),
	CLUE485("How many coins would you need to purchase 133 kebabs from me?", "399", CHALLENGE),
	CLUE486("How much smithing experience does one receive for smelting a blurite bar?", "8", CHALLENGE),
	CLUE487("How many types of dragon are there beneath the whirlpool's cavern?", "2", CHALLENGE),
	CLUE488("How many vine patches can you find in this vinery?", "12", CHALLENGE),
	CLUE489("How many buildings in the village?", "11", CHALLENGE),
	CLUE490("How many stalls are there in Varrock Square?", "5", CHALLENGE),
	CLUE491("If I have 49 bottles of rum to share between 7 pirates, how many would each pirate get?", "7", CHALLENGE),
	CLUE492("I have 16 kebabs, I eat one myself and share the rest equally between 3 friends. How many do they have each?", "5", CHALLENGE),
	CLUE493("How many coins would I have if I had 0 coins and attempted to buy 3 loaves of bread?", "0", CHALLENGE),
	CLUE494("King Arthur and Merlin sit down at the Round Table with 8 knights. How many degrees does each get?", "36", CHALLENGE),
	CLUE495("How many bookcases are there in the Varrock palace library?", "24", CHALLENGE),
	CLUE496("How many farming patches are there in Gnome stronghold?", "2", CHALLENGE),
	CLUE497("What is 333 multiplied by 2?", "666", CHALLENGE),
	CLUE498("How many ranges are there in the Catherby?", "2", CHALLENGE),
	CLUE499("How many fountains are there within the grounds of Camelot castle.", "6", CHALLENGE),
	CLUE500("How many coal rocks are around here?", "8", CHALLENGE),
	CLUE501("How many bookcases are in the Wise Old Man's house?", "28", CHALLENGE),
	CLUE502("What is the combined combat level of each species that live in Slayer tower?", "619", CHALLENGE),
	CLUE503("If I have 1000 blood runes, and cast 131 ice barrage spells, how many blood runes do I have left?", "738", CHALLENGE),
	CLUE504("What is the cube root of 125?", "5", CHALLENGE),
	CLUE505("What is 57 x 89 + 23?", "5096", CHALLENGE),
	CLUE506("How many pyre sites are found around this lake?", "3", CHALLENGE),
	CLUE507("On a scale of 1-10, how helpful is Logosia?", "1", CHALLENGE),
	CLUE508("How many air runes would I need to cast 630 wind waves?", "3,150", CHALLENGE),
	CLUE509("How many people are waiting for the next bard to perform?", "4", CHALLENGE),
	CLUE510("How many pigeon cages are there around the back of Jerico's house?", "3", CHALLENGE),
	CLUE511("If x is 15 and y is 3, what is 3x + y?", "48", CHALLENGE),
	CLUE512("One pipe fills a barrel in 1 hour while another pipe can fill the same barrel in 2 hours. How many minutes will it take to fill the take if both pipes are used?", "40", CHALLENGE),
	CLUE513("On a clock, how many times a day does the minute hand and the hour hand overlap?", "22", CHALLENGE),
	CLUE514("During a party, everyone shook hands with everyone else. There were 66 handshakes. How many people were at the party?", "12", CHALLENGE),
	CLUE515("A question on elven crystal math. I have 5 and 3 crystals, large and small respectively. A large crystal is worth 10,000 coins and a small is worth but 1,000. How much are all my crystals worth?", "53,000", CHALLENGE),
	CLUE516("32 - 5x = 22, what is x?", "2", CHALLENGE),
	CLUE517("How many buildings are there in Rimmington?", "7", CHALLENGE),
	CLUE518("How many gnomes on the Gnome ball field have red patches on their uniforms?", "6", CHALLENGE),
	CLUE519("What is the minimum amount of quest points required to reach Lletya?", "20", CHALLENGE),
	CLUE520("How many districts form the city of Great Kourend?", "5", CHALLENGE),
	CLUE521("How many cannons does Lumbridge Castle have?", "9", CHALLENGE),
	CLUE522("What is 19 to the power of 3?", "6859", CHALLENGE),
	CLUE523("There are 3 inputs and 4 letters on each ring How many total individual fairy ring codes are possible?", "64", CHALLENGE),
	CLUE524("How many fishing cranes can you find around here?", "5", CHALLENGE),
	CLUE525("How many chairs are there in the Rising Sun?", "18", CHALLENGE),
	CLUE526("What is the combined slayer requirement of every monster in the slayer cave?", "302", CHALLENGE),
	CLUE527("The cipher reveals who to speak to next: BMJ UIF LFCBC TFMMFS", "Ali the Kebab seller", "Pollnivneach", "399", CIPHER),
	CLUE528("The cipher reveals who to speak to next: GUHCHO", "Drezel", "Paterdomus", "7", CIPHER),
	CLUE529("The cipher reveals who to speak to next: ZCZL", "Adam", "Outside Lumbridge castle", "666", CIPHER),
	CLUE530("The cipher reveals who to speak to next: ZHLUG ROG PDQ", "Weird Old Man", "Kalphite Lair entrance", "150", CIPHER),
	CLUE531("The cipher reveals who to speak to next: ECRVCKP MJCNGF", "Captain Khaled", "Large eastern building in Piscarilius House", "5", CIPHER),
	CLUE532("The cipher reveals who to speak to next: OVEXON", "Eluned", "Outside Lletya", "53,000", CIPHER),
	CLUE533("The cipher reveals who to speak to next: VTYR APCNTGLW", "King Percival", "Fisher Realm", "5", CIPHER),
	CLUE534("The cipher reveals who to speak to next: UZZU MUJHRKYYKJ", "Otto Godblessed", "Otto's Grotto", "3", CIPHER),
	CLUE535("The cipher reveals who to speak to next: USBJCPSO", "Traiborn", "Wizard's Tower, 2nd floor", "3150", CIPHER),
	CLUE536("The cipher reveals who to speak to next: HCKTA IQFHCVJGT", "Fairy Godfather", "Zanaris throne room", "64", CIPHER),
	CLUE537("The cipher reveals who to speak to next: ZSBKDO ZODO", "Pirate Pete", "Dock northeast of the Ectofunctus", CIPHER),
	CLUE538("The cipher reveals who to speak to next: GBJSZ RVFFO", "Fairy Queen", "Fairy Resistance Hideout", CIPHER),
	CLUE539("The cipher reveals who to speak to next: QSPGFTTPS HSBDLMFCPOF", "Professor Gracklebone", "Arceuus House Library, ground floor", "9", CIPHER);

	private static final Map<String, ClueScroll> clues = new HashMap<>();

	private int[] ids;
	private String text;
	private String npc;
	private String location;
	private String answer;
	private ClueScrollType type;

	static
	{
		for (ClueScroll s : values())
		{
			clues.put(s.getText().toLowerCase(), s);
		}
	}

	ClueScroll(int[] ids, String text, String npc, String location, String answer, ClueScrollType type)
	{
		this.ids = ids;
		this.text = text;
		this.npc = npc;
		this.location = location;
		this.answer = answer;
		this.type = type;
	}

	ClueScroll(String text, String npc, String location, String answer, ClueScrollType type)
	{
		this(null, text, npc, location, answer, type);
	}

	ClueScroll(String text, String npc, String location, ClueScrollType type)
	{
		this(null, text, npc, location, null, type);
	}

	ClueScroll(String text, String answer, ClueScrollType type)
	{
		this(null, text, null, null, answer, type);
	}

	ClueScroll(int[] ids, String text, ClueScrollType type)
	{
		this(ids, text, null, null, null, type);
	}

	public int[] getIds()
	{
		return ids;
	}

	public String getText()
	{
		return text;
	}

	public String getNpc()
	{
		return npc;
	}

	public String getLocation()
	{
		return location;
	}

	public String getAnswer()
	{
		return answer;
	}

	public ClueScrollType getType()
	{
		return type;
	}

	public static ClueScroll forText(String text)
	{
		return clues.get(text);
	}
}
