/*
 * This file is generated by jOOQ.
 */
package net.runelite.client.database.data.tables.records;


import java.util.UUID;
import javax.annotation.Generated;
import net.runelite.client.database.data.tables.Loottrackerloot;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.11.12"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class LoottrackerlootRecord extends UpdatableRecordImpl<LoottrackerlootRecord> implements Record3<UUID, Integer, Integer>
{

	private static final long serialVersionUID = -1894768090;

	/**
	 * Setter for <code>PUBLIC.LOOTTRACKERLOOT.UNIQUEID</code>.
	 */
	public void setUniqueid(UUID value)
	{
		set(0, value);
	}

	/**
	 * Getter for <code>PUBLIC.LOOTTRACKERLOOT.UNIQUEID</code>.
	 */
	public UUID getUniqueid()
	{
		return (UUID) get(0);
	}

	/**
	 * Setter for <code>PUBLIC.LOOTTRACKERLOOT.ITEMID</code>.
	 */
	public void setItemid(Integer value)
	{
		set(1, value);
	}

	/**
	 * Getter for <code>PUBLIC.LOOTTRACKERLOOT.ITEMID</code>.
	 */
	public Integer getItemid()
	{
		return (Integer) get(1);
	}

	/**
	 * Setter for <code>PUBLIC.LOOTTRACKERLOOT.QUANTITY</code>.
	 */
	public void setQuantity(Integer value)
	{
		set(2, value);
	}

	/**
	 * Getter for <code>PUBLIC.LOOTTRACKERLOOT.QUANTITY</code>.
	 */
	public Integer getQuantity()
	{
		return (Integer) get(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<UUID> key()
	{
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<UUID, Integer, Integer> fieldsRow()
	{
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<UUID, Integer, Integer> valuesRow()
	{
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<UUID> field1()
	{
		return Loottrackerloot.LOOTTRACKERLOOT.UNIQUEID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2()
	{
		return Loottrackerloot.LOOTTRACKERLOOT.ITEMID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3()
	{
		return Loottrackerloot.LOOTTRACKERLOOT.QUANTITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UUID component1()
	{
		return getUniqueid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer component2()
	{
		return getItemid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer component3()
	{
		return getQuantity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UUID value1()
	{
		return getUniqueid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2()
	{
		return getItemid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3()
	{
		return getQuantity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LoottrackerlootRecord value1(UUID value)
	{
		setUniqueid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LoottrackerlootRecord value2(Integer value)
	{
		setItemid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LoottrackerlootRecord value3(Integer value)
	{
		setQuantity(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LoottrackerlootRecord values(UUID value1, Integer value2, Integer value3)
	{
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached LoottrackerlootRecord
	 */
	public LoottrackerlootRecord()
	{
		super(Loottrackerloot.LOOTTRACKERLOOT);
	}

	/**
	 * Create a detached, initialised LoottrackerlootRecord
	 */
	public LoottrackerlootRecord(UUID uniqueid, Integer itemid, Integer quantity)
	{
		super(Loottrackerloot.LOOTTRACKERLOOT);

		set(0, uniqueid);
		set(1, itemid);
		set(2, quantity);
	}
}
