/*
 * This file is generated by jOOQ.
 */
package net.runelite.client.database.data.tables.records;


import javax.annotation.processing.Generated;
import net.runelite.client.database.data.tables.TmorphSets;
import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.12.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TmorphSetsRecord extends TableRecordImpl<TmorphSetsRecord> implements Record10<String, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer>
{

	private static final long serialVersionUID = 546214401;

	/**
	 * Setter for <code>PUBLIC.TMORPH_SETS.SET_NAME</code>.
	 */
	public void setSetName(String value)
	{
		set(0, value);
	}

	/**
	 * Getter for <code>PUBLIC.TMORPH_SETS.SET_NAME</code>.
	 */
	public String getSetName()
	{
		return (String) get(0);
	}

	/**
	 * Setter for <code>PUBLIC.TMORPH_SETS.HELMET</code>.
	 */
	public void setHelmet(Integer value)
	{
		set(1, value);
	}

	/**
	 * Getter for <code>PUBLIC.TMORPH_SETS.HELMET</code>.
	 */
	public Integer getHelmet()
	{
		return (Integer) get(1);
	}

	/**
	 * Setter for <code>PUBLIC.TMORPH_SETS.CAPE</code>.
	 */
	public void setCape(Integer value)
	{
		set(2, value);
	}

	/**
	 * Getter for <code>PUBLIC.TMORPH_SETS.CAPE</code>.
	 */
	public Integer getCape()
	{
		return (Integer) get(2);
	}

	/**
	 * Setter for <code>PUBLIC.TMORPH_SETS.AMULET</code>.
	 */
	public void setAmulet(Integer value)
	{
		set(3, value);
	}

	/**
	 * Getter for <code>PUBLIC.TMORPH_SETS.AMULET</code>.
	 */
	public Integer getAmulet()
	{
		return (Integer) get(3);
	}

	/**
	 * Setter for <code>PUBLIC.TMORPH_SETS.WEAPON</code>.
	 */
	public void setWeapon(Integer value)
	{
		set(4, value);
	}

	/**
	 * Getter for <code>PUBLIC.TMORPH_SETS.WEAPON</code>.
	 */
	public Integer getWeapon()
	{
		return (Integer) get(4);
	}

	/**
	 * Setter for <code>PUBLIC.TMORPH_SETS.TORSO</code>.
	 */
	public void setTorso(Integer value)
	{
		set(5, value);
	}

	/**
	 * Getter for <code>PUBLIC.TMORPH_SETS.TORSO</code>.
	 */
	public Integer getTorso()
	{
		return (Integer) get(5);
	}

	/**
	 * Setter for <code>PUBLIC.TMORPH_SETS.SHIELD</code>.
	 */
	public void setShield(Integer value)
	{
		set(6, value);
	}

	/**
	 * Getter for <code>PUBLIC.TMORPH_SETS.SHIELD</code>.
	 */
	public Integer getShield()
	{
		return (Integer) get(6);
	}

	/**
	 * Setter for <code>PUBLIC.TMORPH_SETS.LEGS</code>.
	 */
	public void setLegs(Integer value)
	{
		set(7, value);
	}

	/**
	 * Getter for <code>PUBLIC.TMORPH_SETS.LEGS</code>.
	 */
	public Integer getLegs()
	{
		return (Integer) get(7);
	}

	/**
	 * Setter for <code>PUBLIC.TMORPH_SETS.HANDS</code>.
	 */
	public void setHands(Integer value)
	{
		set(8, value);
	}

	/**
	 * Getter for <code>PUBLIC.TMORPH_SETS.HANDS</code>.
	 */
	public Integer getHands()
	{
		return (Integer) get(8);
	}

	/**
	 * Setter for <code>PUBLIC.TMORPH_SETS.BOOTS</code>.
	 */
	public void setBoots(Integer value)
	{
		set(9, value);
	}

	/**
	 * Getter for <code>PUBLIC.TMORPH_SETS.BOOTS</code>.
	 */
	public Integer getBoots()
	{
		return (Integer) get(9);
	}

	// -------------------------------------------------------------------------
	// Record10 type implementation
	// -------------------------------------------------------------------------

	@Override
	public Row10<String, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer> fieldsRow()
	{
		return (Row10) super.fieldsRow();
	}

	@Override
	public Row10<String, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer> valuesRow()
	{
		return (Row10) super.valuesRow();
	}

	@Override
	public Field<String> field1()
	{
		return TmorphSets.TMORPH_SETS.SET_NAME;
	}

	@Override
	public Field<Integer> field2()
	{
		return TmorphSets.TMORPH_SETS.HELMET;
	}

	@Override
	public Field<Integer> field3()
	{
		return TmorphSets.TMORPH_SETS.CAPE;
	}

	@Override
	public Field<Integer> field4()
	{
		return TmorphSets.TMORPH_SETS.AMULET;
	}

	@Override
	public Field<Integer> field5()
	{
		return TmorphSets.TMORPH_SETS.WEAPON;
	}

	@Override
	public Field<Integer> field6()
	{
		return TmorphSets.TMORPH_SETS.TORSO;
	}

	@Override
	public Field<Integer> field7()
	{
		return TmorphSets.TMORPH_SETS.SHIELD;
	}

	@Override
	public Field<Integer> field8()
	{
		return TmorphSets.TMORPH_SETS.LEGS;
	}

	@Override
	public Field<Integer> field9()
	{
		return TmorphSets.TMORPH_SETS.HANDS;
	}

	@Override
	public Field<Integer> field10()
	{
		return TmorphSets.TMORPH_SETS.BOOTS;
	}

	@Override
	public String component1()
	{
		return getSetName();
	}

	@Override
	public Integer component2()
	{
		return getHelmet();
	}

	@Override
	public Integer component3()
	{
		return getCape();
	}

	@Override
	public Integer component4()
	{
		return getAmulet();
	}

	@Override
	public Integer component5()
	{
		return getWeapon();
	}

	@Override
	public Integer component6()
	{
		return getTorso();
	}

	@Override
	public Integer component7()
	{
		return getShield();
	}

	@Override
	public Integer component8()
	{
		return getLegs();
	}

	@Override
	public Integer component9()
	{
		return getHands();
	}

	@Override
	public Integer component10()
	{
		return getBoots();
	}

	@Override
	public String value1()
	{
		return getSetName();
	}

	@Override
	public Integer value2()
	{
		return getHelmet();
	}

	@Override
	public Integer value3()
	{
		return getCape();
	}

	@Override
	public Integer value4()
	{
		return getAmulet();
	}

	@Override
	public Integer value5()
	{
		return getWeapon();
	}

	@Override
	public Integer value6()
	{
		return getTorso();
	}

	@Override
	public Integer value7()
	{
		return getShield();
	}

	@Override
	public Integer value8()
	{
		return getLegs();
	}

	@Override
	public Integer value9()
	{
		return getHands();
	}

	@Override
	public Integer value10()
	{
		return getBoots();
	}

	@Override
	public TmorphSetsRecord value1(String value)
	{
		setSetName(value);
		return this;
	}

	@Override
	public TmorphSetsRecord value2(Integer value)
	{
		setHelmet(value);
		return this;
	}

	@Override
	public TmorphSetsRecord value3(Integer value)
	{
		setCape(value);
		return this;
	}

	@Override
	public TmorphSetsRecord value4(Integer value)
	{
		setAmulet(value);
		return this;
	}

	@Override
	public TmorphSetsRecord value5(Integer value)
	{
		setWeapon(value);
		return this;
	}

	@Override
	public TmorphSetsRecord value6(Integer value)
	{
		setTorso(value);
		return this;
	}

	@Override
	public TmorphSetsRecord value7(Integer value)
	{
		setShield(value);
		return this;
	}

	@Override
	public TmorphSetsRecord value8(Integer value)
	{
		setLegs(value);
		return this;
	}

	@Override
	public TmorphSetsRecord value9(Integer value)
	{
		setHands(value);
		return this;
	}

	@Override
	public TmorphSetsRecord value10(Integer value)
	{
		setBoots(value);
		return this;
	}

	@Override
	public TmorphSetsRecord values(String value1, Integer value2, Integer value3, Integer value4, Integer value5, Integer value6, Integer value7, Integer value8, Integer value9, Integer value10)
	{
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TmorphSetsRecord
	 */
	public TmorphSetsRecord()
	{
		super(TmorphSets.TMORPH_SETS);
	}

	/**
	 * Create a detached, initialised TmorphSetsRecord
	 */
	public TmorphSetsRecord(String setName, Integer helmet, Integer cape, Integer amulet, Integer weapon, Integer torso, Integer shield, Integer legs, Integer hands, Integer boots)
	{
		super(TmorphSets.TMORPH_SETS);

		set(0, setName);
		set(1, helmet);
		set(2, cape);
		set(3, amulet);
		set(4, weapon);
		set(5, torso);
		set(6, shield);
		set(7, legs);
		set(8, hands);
		set(9, boots);
	}
}
