/*
 * This file is generated by jOOQ.
 */
package net.runelite.client.database.data.tables.records;


import java.util.UUID;
import javax.annotation.Generated;
import net.runelite.client.database.data.tables.User;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.11.12"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class UserRecord extends UpdatableRecordImpl<UserRecord> implements Record2<UUID, String>
{

	private static final long serialVersionUID = 628808107;

	/**
	 * Setter for <code>PUBLIC.USER.UNIQUEID</code>.
	 */
	public void setUniqueid(UUID value)
	{
		set(0, value);
	}

	/**
	 * Getter for <code>PUBLIC.USER.UNIQUEID</code>.
	 */
	public UUID getUniqueid()
	{
		return (UUID) get(0);
	}

	/**
	 * Setter for <code>PUBLIC.USER.USERNAME</code>.
	 */
	public void setUsername(String value)
	{
		set(1, value);
	}

	/**
	 * Getter for <code>PUBLIC.USER.USERNAME</code>.
	 */
	public String getUsername()
	{
		return (String) get(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<UUID> key()
	{
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<UUID, String> fieldsRow()
	{
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<UUID, String> valuesRow()
	{
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<UUID> field1()
	{
		return User.USER.UNIQUEID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2()
	{
		return User.USER.USERNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UUID component1()
	{
		return getUniqueid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String component2()
	{
		return getUsername();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UUID value1()
	{
		return getUniqueid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2()
	{
		return getUsername();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value1(UUID value)
	{
		setUniqueid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value2(String value)
	{
		setUsername(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord values(UUID value1, String value2)
	{
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UserRecord
	 */
	public UserRecord()
	{
		super(User.USER);
	}

	/**
	 * Create a detached, initialised UserRecord
	 */
	public UserRecord(UUID uniqueid, String username)
	{
		super(User.USER);

		set(0, uniqueid);
		set(1, username);
	}
}
