package net.runelite.client.plugins.skillcalculator.skills;

import lombok.AllArgsConstructor;
import lombok.Getter;
import net.runelite.api.gameval.ItemID;
import net.runelite.client.game.ItemManager;

@AllArgsConstructor
@Getter
public enum SailingAction implements NamedSkillAction
{
    SMALL_SHIPWRECK_SORTING("Small Shipwreck Sorting", 15, 5, ItemID.SAILING_SMALL_SHIPWRECK_SALVAGE),
    SMALL_SHIPWRECK_SALVAGE("Small Shipwreck Salvage", 15, 10, ItemID.SAILING_SMALL_SHIPWRECK_SALVAGE),

    FISHY_SHIPWRECK_SORTING("Fishy Shipwreck Sorting", 26, 9, ItemID.SAILING_FISHERMAN_SHIPWRECK_SALVAGE),
    FISHY_SHIPWRECK_SALVAGE("Fishy Shipwreck Salvage", 26, 17, ItemID.SAILING_FISHERMAN_SHIPWRECK_SALVAGE),

    TEMPEST_TRIAL_UNRANKED("Unranked Tempor Trial", 30, 150f, ItemID.RALPHS_FABRIC_ROLL),
    TEMPEST_TRIAL_SWORDFISH("Swordfish Tempor Trial", 30, 385f, ItemID.RALPHS_FABRIC_ROLL),
    TEMPEST_TRIAL_SHARK("Shark Tempor Trial", 30, 650f, ItemID.RALPHS_FABRIC_ROLL),
    TEMPEST_TRIAL_MARLIN("Marlin Tempor Trial", 30, 1250f, ItemID.RALPHS_FABRIC_ROLL),
    BULL_SHARK_BOUNTY("Bull Shark Bounty", 30, 1790f, ItemID.SAILING_BULL_SHARK_JAW),
    EAGLE_RAY_BOUNTY("Eagle Ray Bounty", 30, 1790f, ItemID.SAILING_EAGLE_RAY_SKIN),
    MOGRE_BOUNTY("Mogre Bounty", 30, 1790f, ItemID.SAILING_SEA_MOGRE_MACE),
    OSPREY_BOUNTY("Osprey Bounty", 30, 1790f, ItemID.SAILING_OSPREY_FEATHER),
    TERN_BOUNTY("Tern Bounty", 30, 1790f, ItemID.SAILING_TERN_FEATHER),

    BARRACUDA_SHIPWRECK_SORTING("Barracuda Shipwreck Sorting", 35, 15.5f, ItemID.SAILING_BARRACUDA_SHIPWRECK_SALVAGE),
    BARRACUDA_SHIPWRECK_SALVAGE("Barracuda Shipwreck Salvage", 35, 31, ItemID.SAILING_BARRACUDA_SHIPWRECK_SALVAGE),

    BULL_SHARK_BOUNTY_38("Bull Shark Bounty", 38, 2020f, ItemID.SAILING_BULL_SHARK_JAW),
    EAGLE_RAY_BOUNTY_38("Eagle Ray Bounty", 38, 2020f, ItemID.SAILING_EAGLE_RAY_SKIN),
    OSPREY_BOUNTY_38("Osprey Bounty", 38, 2020f, ItemID.SAILING_OSPREY_FEATHER),
    TERN_BOUNTY_38("Tern Bounty", 38, 2020f, ItemID.SAILING_TERN_FEATHER),

    BUTTERFLY_RAY_BOUNTY("Butterfly Ray Bounty", 40, 3400f, ItemID.SAILING_BUTTERFLY_RAY_SKIN),
    HAMMERHEAD_SHARK_BOUNTY("Hammerhead Shark Bounty", 40, 3400f, ItemID.SAILING_HAMMERHEAD_SHARK_JAW),
    MOGRE_BOUNTY_40("Mogre Bounty", 40, 3400f, ItemID.SAILING_SEA_MOGRE_MACE),
    OSPREY_BOUNTY_40("Osprey Bounty", 40, 3400f, ItemID.SAILING_OSPREY_FEATHER),

    BUTTERFLY_RAY_BOUNTY_45("Butterfly Ray Bounty", 45, 3650f, ItemID.SAILING_BUTTERFLY_RAY_SKIN),
    EAGLE_RAY_BOUNTY_45("Eagle Ray Bounty", 45, 3650f, ItemID.SAILING_EAGLE_RAY_SKIN),

    BUTTERFLY_RAY_BOUNTY_46("Butterfly Ray Bounty", 46, 3650f, ItemID.SAILING_BUTTERFLY_RAY_SKIN),
    HAMMERHEAD_SHARK_BOUNTY_46("Hammerhead Shark Bounty", 46, 3650f, ItemID.SAILING_HAMMERHEAD_SHARK_JAW),
    OSPREY_BOUNTY_46("Osprey Bounty", 46, 3650f, ItemID.SAILING_OSPREY_FEATHER),

    BULL_SHARK_BOUNTY_48("Bull Shark Bounty", 48, 3650f, ItemID.SAILING_BULL_SHARK_JAW),
    BUTTERFLY_RAY_BOUNTY_48("Butterfly Ray Bounty", 48, 3650f, ItemID.SAILING_BUTTERFLY_RAY_SKIN),
    EAGLE_RAY_BOUNTY_48("Eagle Ray Bounty", 48, 3650f, ItemID.SAILING_EAGLE_RAY_SKIN),
    HAMMERHEAD_SHARK_BOUNTY_48("Hammerhead Shark Bounty", 48, 3650f, ItemID.SAILING_HAMMERHEAD_SHARK_JAW),

    EAGLE_RAY_BOUNTY_50("Eagle Ray Bounty", 50, 4390f, ItemID.SAILING_EAGLE_RAY_SKIN),
    FRIGATEBIRD_BOUNTY("Frigatebird Bounty", 50, 4390f, ItemID.SAILING_FRIGATEBIRD_FEATHER),
    HAMMERHEAD_SHARK_BOUNTY_50("Hammerhead Shark Bounty", 50, 4390f, ItemID.SAILING_HAMMERHEAD_SHARK_JAW),
    OSPREY_BOUNTY_50("Osprey Bounty", 50, 4390f, ItemID.SAILING_OSPREY_FEATHER),
    STINGRAY_BOUNTY("Stingray Bounty", 50, 4390f, ItemID.SAILING_STINGRAY_SKIN),
    TERN_BOUNTY_50("Tern Bounty", 50, 4390f, ItemID.SAILING_TERN_FEATHER),

    LARGE_SHIPWRECK_SORTING("Large Shipwreck Sorting", 53, 24, ItemID.SAILING_LARGE_SHIPWRECK_SALVAGE),
    LARGE_SHIPWRECK_SALVAGE("Large Shipwreck Salvage", 53, 48, ItemID.SAILING_LARGE_SHIPWRECK_SALVAGE),
    JIVE_TRIAL_UNRANKED("Unranked Jubbly Jive Trial", 55, 1000f, ItemID.GURTOBS_FABRIC_ROLL),
    JIVE_TRIAL_SWORDFISH("Swordfish Jubbly Jive Trial", 55, 1700f, ItemID.GURTOBS_FABRIC_ROLL),
    JIVE_TRIAL_SHARK("Shark Jubbly Jive Trial", 55, 5500f, ItemID.GURTOBS_FABRIC_ROLL),
    JIVE_TRIAL_MARLIN("Marlin Jubbly Jive Trial", 55, 6200f, ItemID.GURTOBS_FABRIC_ROLL),
    ALBATROSS_BOUNTY("Albatross Bounty", 55, 6360f, ItemID.SAILING_ALBATROSS_FEATHER),
    PYGMY_KRAKEN_BOUNTY("Pygmy Kraken Bounty", 55, 6360f, ItemID.SAILING_PYGMY_KRAKEN_TENTACLE),

    TIGER_SHARK_BOUNTY("Tiger Shark Bounty", 60, 6760f, ItemID.SAILING_TIGER_SHARK_JAW),

    ALBATROSS_BOUNTY_62("Albatross Bounty", 62, 6760f, ItemID.SAILING_ALBATROSS_FEATHER),
    HAMMERHEAD_SHARK_BOUNTY_62("Hammerhead Shark Bounty", 62, 6760f, ItemID.SAILING_HAMMERHEAD_SHARK_JAW),
    NARWHAL_BOUNTY("Narwhal Bounty", 62, 6760f, ItemID.SAILING_NARWHAL_TUSK),

    PLUNDERED_SHIPWRECK_SORTING("Plundered Shipwreck Sorting", 64, 31.5f, ItemID.SAILING_PIRATE_SHIPWRECK_SALVAGE),
    PLUNDERED_SHIPWRECK_SALVAGE("Plundered Shipwreck Salvage", 64, 63, ItemID.SAILING_PIRATE_SHIPWRECK_SALVAGE),

    ALBATROSS_BOUNTY_65("Albatross Bounty", 65, 7500f, ItemID.SAILING_ALBATROSS_FEATHER),
    MANTA_RAY_BOUNTY("Manta Ray Bounty", 65, 7500f, ItemID.SAILING_MANTA_RAY_SKIN),
    NARWHAL_BOUNTY_65("Narwhal Bounty", 65, 7500f, ItemID.SAILING_NARWHAL_TUSK),

    BULL_SHARK_BOUNTY_66("Bull Shark Bounty", 66, 7500f, ItemID.SAILING_BULL_SHARK_JAW),
    BUTTERFLY_RAY_BOUNTY_66("Butterfly Ray Bounty", 66, 7500f, ItemID.SAILING_BUTTERFLY_RAY_SKIN),
    HAMMERHEAD_SHARK_BOUNTY_66("Hammerhead Shark Bounty", 66, 7500f, ItemID.SAILING_HAMMERHEAD_SHARK_JAW),
    MANTA_RAY_BOUNTY_66("Manta Ray Bounty", 66, 7500f, ItemID.SAILING_MANTA_RAY_SKIN),
    PYGMY_KRAKEN_BOUNTY_66("Pygmy Kraken Bounty", 66, 7500f, ItemID.SAILING_PYGMY_KRAKEN_TENTACLE),

    EAGLE_RAY_BOUNTY_67("Eagle Ray Bounty", 67, 7500f, ItemID.SAILING_EAGLE_RAY_SKIN),
    FRIGATEBIRD_BOUNTY_67("Frigatebird Bounty", 67, 7500f, ItemID.SAILING_FRIGATEBIRD_FEATHER),
    HAMMERHEAD_SHARK_BOUNTY_67("Hammerhead Shark Bounty", 67, 7500f, ItemID.SAILING_HAMMERHEAD_SHARK_JAW),
    OSPREY_BOUNTY_67("Osprey Bounty", 67, 7500f, ItemID.SAILING_OSPREY_FEATHER),
    STINGRAY_BOUNTY_67("Stingray Bounty", 67, 7500f, ItemID.SAILING_STINGRAY_SKIN),
    TIGER_SHARK_BOUNTY_67("Tiger Shark Bounty", 67, 7500f, ItemID.SAILING_TIGER_SHARK_JAW),

    HAMMERHEAD_SHARK_BOUNTY_70("Hammerhead Shark Bounty", 70, 7730f, ItemID.SAILING_HAMMERHEAD_SHARK_JAW),
    MANTA_RAY_BOUNTY_70("Manta Ray Bounty", 70, 7730f, ItemID.SAILING_MANTA_RAY_SKIN),
    OSPREY_BOUNTY_70("Osprey Bounty", 70, 7730f, ItemID.SAILING_OSPREY_FEATHER),
    PYGMY_KRAKEN_BOUNTY_70("Pygmy Kraken Bounty", 70, 7730f, ItemID.SAILING_PYGMY_KRAKEN_TENTACLE),
    SPINED_KRAKEN_BOUNTY("Spined Kraken Bounty", 70, 7730f, ItemID.SAILING_SPINED_KRAKEN_TENTACLE),

    GLIDE_TRIAL_UNRANKED("Unranked Gwenith Glide Trial", 72, 2050f, ItemID.GWYNAS_FABRIC_ROLL),
    GLIDE_TRIAL_SWORDFISH("Swordfish Gwenith Glide Trial", 72, 3050f, ItemID.GWYNAS_FABRIC_ROLL),
    GLIDE_TRIAL_SHARK("Shark Gwenith Glide Trial", 72, 7250f, ItemID.GWYNAS_FABRIC_ROLL),
    GLIDE_TRIAL_MARLIN("Marlin Gwenith Glide Trial", 72, 14800f, ItemID.GWYNAS_FABRIC_ROLL),

    MARTIAL_SHIPWRECK_SORTING("Martial Shipwreck Sorting", 73, 63.5f, ItemID.SAILING_MERCENARY_SHIPWRECK_SALVAGE),
    MARTIAL_SHIPWRECK_SALVAGE("Martial Shipwreck Salvage", 73, 127, ItemID.SAILING_MERCENARY_SHIPWRECK_SALVAGE),
    CRYSTAL_EXTRACTOR("Crystal Extractor Harvest", 73, 600, ItemID.SAILING_SKILLGUIDE_CRYSTAL_EXTRACTOR),

    GREAT_WHITE_SHARK_BOUNTY("Great White Shark Bounty", 75, 8540f, ItemID.SAILING_GREAT_WHITE_SHARK_JAW),

    ALBATROSS_BOUNTY_76("Albatross Bounty", 76, 8450f, ItemID.SAILING_ALBATROSS_FEATHER),
    NARWHAL_BOUNTY_76("Narwhal Bounty", 76, 8450f, ItemID.SAILING_NARWHAL_TUSK),

    FREMENNIK_SHIPWRECK_SORTING("Fremennik Shipwreck Sorting", 80, 75, ItemID.SAILING_FREMENNIK_SHIPWRECK_SALVAGE),
    FREMENNIK_SHIPWRECK_SALVAGE("Fremennik Shipwreck Salvage", 80, 150, ItemID.SAILING_FREMENNIK_SHIPWRECK_SALVAGE),
    ARMOURED_KRAKEN_BOUNTY("Armoured Kraken Bounty", 80, 9540f, ItemID.SAILING_ARMOURED_KRAKEN_TENTACLE),
    ORCA_BOUNTY("Orca Bounty", 80, 9540f, ItemID.SAILING_ORCA_BLUBBER),
    VAMPYRE_KRAKEN_BOUNTY("Vampyre Kraken Bounty", 80, 9540f, ItemID.SAILING_VAMPYRE_KRAKEN_INK_SAC),

    OPULENT_SHIPWRECK_SORTING("Opulent Shipwreck Sorting", 87, 95, ItemID.SAILING_MERCHANT_SHIPWRECK_SALVAGE),
    OPULENT_SHIPWRECK_SALVAGE("Opulent Shipwreck Salvage", 87, 190, ItemID.SAILING_MERCHANT_SHIPWRECK_SALVAGE),

    ;

    private final String name;
    private final int level;
    private final float xp;
    private final int icon;

    @Override
    public boolean isMembers(final ItemManager itemManager)
    {
        return true;
    }
}