/*
 * Copyright (c) 2021, Jordan Atwood <nightfirecat@protonmail.com>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package net.runelite.client.plugins.skillcalculator.skills;

import lombok.AllArgsConstructor;
import lombok.Getter;
import net.runelite.api.ItemID;

@AllArgsConstructor
@Getter
public enum SmithingAction implements SkillAction
{
	BRONZE_BAR("Bronze bar", 1, 6.3f, ItemID.BRONZE_BAR),
	BRONZE_AXE("Bronze axe", 1, 12.5f, ItemID.BRONZE_AXE),
	BRONZE_DAGGER("Bronze dagger", 1, 12.5f, ItemID.BRONZE_DAGGER),
	BRONZE_MACE("Bronze mace", 2, 12.5f, ItemID.BRONZE_MACE),
	BRONZE_MED_HELM("Bronze med helm", 3, 12.5f, ItemID.BRONZE_MED_HELM),
	BRONZE_BOLTS_UNF("Bronze bolts (unf)", 3, 12.5f, ItemID.BRONZE_BOLTS_UNF),
	BRONZE_NAILS("Bronze nails", 4, 12.5f, ItemID.BRONZE_NAILS),
	BRONZE_SWORD("Bronze sword", 4, 12.5f, ItemID.BRONZE_SWORD),
	BRONZE_WIRE("Bronze wire", 4, 12.5f, ItemID.BRONZE_WIRE),
	BRONZE_DART_TIP("Bronze dart tip", 4, 12.5f, ItemID.BRONZE_DART_TIP),
	BRONZE_ARROWTIPS("Bronze arrowtips", 5, 12.5f, ItemID.BRONZE_ARROWTIPS),
	BRONZE_SCIMITAR("Bronze scimitar", 5, 25, ItemID.BRONZE_SCIMITAR),
	BRONZE_HASTA("Bronze hasta", 5, 25, ItemID.BRONZE_HASTA),
	BRONZE_SPEAR("Bronze spear", 5, 25, ItemID.BRONZE_SPEAR),
	BRONZE_JAVELIN_HEADS("Bronze javelin heads", 6, 12.5f, ItemID.BRONZE_JAVELIN_HEADS),
	BRONZE_LONGSWORD("Bronze longsword", 6, 25, ItemID.BRONZE_LONGSWORD),
	BRONZE_LIMBS("Bronze limbs", 6, 12.5f, ItemID.BRONZE_LIMBS),
	BRONZE_KNIFE("Bronze knife", 7, 12.5f, ItemID.BRONZE_KNIFE),
	BRONZE_FULL_HELM("Bronze full helm", 7, 25, ItemID.BRONZE_FULL_HELM),
	BRONZE_SQ_SHIELD("Bronze sq shield", 8, 25, ItemID.BRONZE_SQ_SHIELD),
	BRONZE_WARHAMMER("Bronze warhammer", 9, 37.5f, ItemID.BRONZE_WARHAMMER),
	BRONZE_BATTLEAXE("Bronze battleaxe", 10, 37.5f, ItemID.BRONZE_BATTLEAXE),
	BRONZE_CHAINBODY("Bronze chainbody", 11, 37.5f, ItemID.BRONZE_CHAINBODY),
	BRONZE_KITESHIELD("Bronze kiteshield", 12, 37.5f, ItemID.BRONZE_KITESHIELD),
	BRONZE_CLAWS("Bronze claws", 13, 25, ItemID.BRONZE_CLAWS),
	BRONZE_2H_SWORD("Bronze 2h sword", 14, 37.5f, ItemID.BRONZE_2H_SWORD),
	BARRONITE_DEPOSITS("Barronite deposits", 14, 30, ItemID.BARRONITE_DEPOSIT),
	IRON_BAR("Iron bar", 15, 12.5f, ItemID.IRON_BAR),
	IRON_DAGGER("Iron dagger", 15, 25, ItemID.IRON_DAGGER),
	IRON_AXE("Iron axe", 16, 25, ItemID.IRON_AXE),
	BRONZE_PLATELEGS("Bronze platelegs", 16, 37.5f, ItemID.BRONZE_PLATELEGS),
	BRONZE_PLATESKIRT("Bronze plateskirt", 16, 37.5f, ItemID.BRONZE_PLATESKIRT),
	IRON_SPIT("Iron spit", 17, 25, ItemID.IRON_SPIT),
	IRON_MACE("Iron mace", 17, 25, ItemID.IRON_MACE),
	IRON_BOLTS_UNF("Iron bolts (unf)", 18, 25, ItemID.IRON_BOLTS_UNF),
	BRONZE_PLATEBODY("Bronze platebody", 18, 62.5f, ItemID.BRONZE_PLATEBODY),
	IRON_MED_HELM("Iron med helm", 18, 25, ItemID.IRON_MED_HELM),
	IRON_NAILS("Iron nails", 19, 25, ItemID.IRON_NAILS),
	IRON_DART_TIP("Iron dart tip", 19, 25, ItemID.IRON_DART_TIP),
	IRON_SWORD("Iron sword", 19, 25, ItemID.IRON_SWORD),
	SILVER_BAR("Silver bar", 20, 13.7f, ItemID.SILVER_BAR),
	IRON_ARROWTIPS("Iron arrowtips", 20, 25, ItemID.IRON_ARROWTIPS),
	IRON_SCIMITAR("Iron scimitar", 20, 50, ItemID.IRON_SCIMITAR),
	IRON_HASTA("Iron hasta", 20, 50, ItemID.IRON_HASTA),
	IRON_SPEAR("Iron spear", 20, 50, ItemID.IRON_SPEAR),
	IRON_LONGSWORD("Iron longsword", 21, 50, ItemID.IRON_LONGSWORD),
	IRON_JAVELIN_HEADS("Iron javelin heads", 21, 25, ItemID.IRON_JAVELIN_HEADS),
	IRON_FULL_HELM("Iron full helm", 22, 50, ItemID.IRON_FULL_HELM),
	IRON_KNIFE("Iron knife", 22, 25, ItemID.IRON_KNIFE),
	IRON_LIMBS("Iron limbs", 23, 25, ItemID.IRON_LIMBS),
	IRON_SQ_SHIELD("Iron sq shield", 23, 50, ItemID.IRON_SQ_SHIELD),
	IRON_WARHAMMER("Iron warhammer", 24, 75, ItemID.IRON_WARHAMMER),
	IRON_BATTLEAXE("Iron battleaxe", 25, 75, ItemID.IRON_BATTLEAXE),
	OIL_LANTERN_FRAME("Oil lantern frame", 26, 25, ItemID.OIL_LANTERN_FRAME),
	IRON_CHAINBODY("Iron chainbody", 26, 75, ItemID.IRON_CHAINBODY),
	IRON_KITESHIELD("Iron kiteshield", 27, 75, ItemID.IRON_KITESHIELD),
	IRON_CLAWS("Iron claws", 28, 50, ItemID.IRON_CLAWS),
	IRON_2H_SWORD("Iron 2h sword", 29, 75, ItemID.IRON_2H_SWORD),
	STEEL_DAGGER("Steel dagger", 30, 37.5f, ItemID.STEEL_DAGGER),
	STEEL_BAR("Steel bar", 30, 17.5f, ItemID.STEEL_BAR),
	IRON_PLATESKIRT("Iron plateskirt", 31, 75, ItemID.IRON_PLATESKIRT),
	IRON_PLATELEGS("Iron platelegs", 31, 75, ItemID.IRON_PLATELEGS),
	STEEL_AXE("Steel axe", 31, 37.5f, ItemID.STEEL_AXE),
	STEEL_MACE("Steel mace", 32, 37.5f, ItemID.STEEL_MACE),
	IRON_PLATEBODY("Iron platebody", 33, 125, ItemID.IRON_PLATEBODY),
	STEEL_MED_HELM("Steel med helm", 33, 37.5f, ItemID.STEEL_MED_HELM),
	STEEL_BOLTS_UNF("Steel bolts (unf)", 33, 37.5f, ItemID.STEEL_BOLTS_UNF),
	STEEL_DART_TIP("Steel dart tip", 34, 37.5f, ItemID.STEEL_DART_TIP),
	STEEL_NAILS("Steel nails", 34, 37.5f, ItemID.STEEL_NAILS),
	STEEL_SWORD("Steel sword", 34, 37.5f, ItemID.STEEL_SWORD),
	CANNONBALL("Cannonball", 35, 25.6f, ItemID.CANNONBALL),
	STEEL_SCIMITAR("Steel scimitar", 35, 75, ItemID.STEEL_SCIMITAR),
	STEEL_ARROWTIPS("Steel arrowtips", 35, 37.5f, ItemID.STEEL_ARROWTIPS),
	STEEL_HASTA("Steel hasta", 35, 75, ItemID.STEEL_HASTA),
	STEEL_SPEAR("Steel spear", 35, 75, ItemID.STEEL_SPEAR),
	STEEL_LIMBS("Steel limbs", 36, 37.5f, ItemID.STEEL_LIMBS),
	STEEL_STUDS("Steel studs", 36, 37.5f, ItemID.STEEL_STUDS),
	STEEL_LONGSWORD("Steel longsword", 36, 75, ItemID.STEEL_LONGSWORD),
	STEEL_JAVELIN_HEADS("Steel javelin heads", 36, 37.5f, ItemID.STEEL_JAVELIN_HEADS),
	STEEL_KNIFE("Steel knife", 37, 37.5f, ItemID.STEEL_KNIFE),
	STEEL_FULL_HELM("Steel full helm", 37, 75, ItemID.STEEL_FULL_HELM),
	STEEL_SQ_SHIELD("Steel sq shield", 38, 75, ItemID.STEEL_SQ_SHIELD),
	STEEL_WARHAMMER("Steel warhammer", 39, 112.5f, ItemID.STEEL_WARHAMMER),
	STEEL_BATTLEAXE("Steel battleaxe", 40, 112.5f, ItemID.STEEL_BATTLEAXE),
	GOLD_BAR_GOLDSMITH_GAUNTLETS("Gold bar (Goldsmith gauntlets)", 40, 56.2f, ItemID.GOLD_BAR),
	GOLD_BAR("Gold bar", 40, 22.5f, ItemID.GOLD_BAR),
	STEEL_CHAINBODY("Steel chainbody", 41, 112.5f, ItemID.STEEL_CHAINBODY),
	STEEL_KITESHIELD("Steel kiteshield", 42, 112.5f, ItemID.STEEL_KITESHIELD),
	STEEL_CLAWS("Steel claws", 43, 75, ItemID.STEEL_CLAWS),
	STEEL_2H_SWORD("Steel 2h sword", 44, 112.5f, ItemID.STEEL_2H_SWORD),
	STEEL_PLATELEGS("Steel platelegs", 46, 112.5f, ItemID.STEEL_PLATELEGS),
	STEEL_PLATESKIRT("Steel plateskirt", 46, 112.5f, ItemID.STEEL_PLATESKIRT),
	STEEL_PLATEBODY("Steel platebody", 48, 187.5f, ItemID.STEEL_PLATEBODY),
	BULLSEYE_LANTERN_UNF("Bullseye lantern (unf)", 49, 37, ItemID.BULLSEYE_LANTERN_UNF),
	MITHRIL_DAGGER("Mithril dagger", 50, 50, ItemID.MITHRIL_DAGGER),
	MITHRIL_BAR("Mithril bar", 50, 30, ItemID.MITHRIL_BAR),
	MITHRIL_AXE("Mithril axe", 51, 50, ItemID.MITHRIL_AXE),
	MITHRIL_MACE("Mithril mace", 52, 50, ItemID.MITHRIL_MACE),
	MITHRIL_MED_HELM("Mithril med helm", 53, 50, ItemID.MITHRIL_MED_HELM),
	MITHRIL_BOLTS_UNF("Mithril bolts (unf)", 53, 50, ItemID.MITHRIL_BOLTS_UNF),
	MITHRIL_SWORD("Mithril sword", 54, 50, ItemID.MITHRIL_SWORD),
	MITHRIL_DART_TIP("Mithril dart tip", 54, 50, ItemID.MITHRIL_DART_TIP),
	MITHRIL_NAILS("Mithril nails", 54, 50, ItemID.MITHRIL_NAILS),
	MITHRIL_ARROWTIPS("Mithril arrowtips", 55, 50, ItemID.MITHRIL_ARROWTIPS),
	MITHRIL_SCIMITAR("Mithril scimitar", 55, 100, ItemID.MITHRIL_SCIMITAR),
	MITHRIL_HASTA("Mithril hasta", 55, 100, ItemID.MITHRIL_HASTA),
	MITHRIL_SPEAR("Mithril spear", 55, 100, ItemID.MITHRIL_SPEAR),
	MITHRIL_LONGSWORD("Mithril longsword", 56, 100, ItemID.MITHRIL_LONGSWORD),
	MITHRIL_JAVELIN_HEADS("Mithril javelin heads", 56, 50, ItemID.MITHRIL_JAVELIN_HEADS),
	MITHRIL_LIMBS("Mithril limbs", 56, 50, ItemID.MITHRIL_LIMBS),
	MITHRIL_FULL_HELM("Mithril full helm", 57, 100, ItemID.MITHRIL_FULL_HELM),
	MITHRIL_KNIFE("Mithril knife", 57, 50, ItemID.MITHRIL_KNIFE),
	MITHRIL_SQ_SHIELD("Mithril sq shield", 58, 100, ItemID.MITHRIL_SQ_SHIELD),
	MITH_GRAPPLE_TIP("Mith grapple tip", 59, 50, ItemID.MITH_GRAPPLE_TIP),
	MITHRIL_WARHAMMER("Mithril warhammer", 59, 150, ItemID.MITHRIL_WARHAMMER),
	DRAGON_SQ_SHIELD("Dragon sq shield", 60, 75, ItemID.DRAGON_SQ_SHIELD),
	MITHRIL_BATTLEAXE("Mithril battleaxe", 60, 150, ItemID.MITHRIL_BATTLEAXE),
	MITHRIL_CHAINBODY("Mithril chainbody", 61, 150, ItemID.MITHRIL_CHAINBODY),
	MITHRIL_KITESHIELD("Mithril kiteshield", 62, 150, ItemID.MITHRIL_KITESHIELD),
	MITHRIL_CLAWS("Mithril claws", 63, 100, ItemID.MITHRIL_CLAWS),
	MITHRIL_2H_SWORD("Mithril 2h sword", 64, 150, ItemID.MITHRIL_2H_SWORD),
	MITHRIL_PLATESKIRT("Mithril plateskirt", 66, 150, ItemID.MITHRIL_PLATESKIRT),
	MITHRIL_PLATELEGS("Mithril platelegs", 66, 150, ItemID.MITHRIL_PLATELEGS),
	MITHRIL_PLATEBODY("Mithril platebody", 68, 250, ItemID.MITHRIL_PLATEBODY),
	ADAMANT_DAGGER("Adamant dagger", 70, 62.5f, ItemID.ADAMANT_DAGGER),
	ADAMANTITE_BAR("Adamantite bar", 70, 37.5f, ItemID.ADAMANTITE_BAR),
	ADAMANT_AXE("Adamant axe", 71, 62.5f, ItemID.ADAMANT_AXE),
	ADAMANT_MACE("Adamant mace", 72, 62.5f, ItemID.ADAMANT_MACE),
	ADAMANT_BOLTS_UNF("Adamant bolts (unf)", 73, 62.5f, ItemID.ADAMANT_BOLTSUNF),
	ADAMANT_MED_HELM("Adamant med helm", 73, 62.5f, ItemID.ADAMANT_MED_HELM),
	ADAMANT_DART_TIP("Adamant dart tip", 74, 62.5f, ItemID.ADAMANT_DART_TIP),
	ADAMANT_SWORD("Adamant sword", 74, 62.5f, ItemID.ADAMANT_SWORD),
	ADAMANTITE_NAILS("Adamantite nails", 74, 62.5f, ItemID.ADAMANTITE_NAILS),
	ADAMANT_ARROWTIPS("Adamant arrowtips", 75, 62.5f, ItemID.ADAMANT_ARROWTIPS),
	ADAMANT_SCIMITAR("Adamant scimitar", 75, 125, ItemID.ADAMANT_SCIMITAR),
	ADAMANT_HASTA("Adamant hasta", 75, 125, ItemID.ADAMANT_HASTA),
	ADAMANT_SPEAR("Adamant spear", 75, 125, ItemID.ADAMANT_SPEAR),
	ADAMANTITE_LIMBS("Adamantite limbs", 76, 62.5f, ItemID.ADAMANTITE_LIMBS),
	ADAMANT_LONGSWORD("Adamant longsword", 76, 125, ItemID.ADAMANT_LONGSWORD),
	ADAMANT_JAVELIN_HEADS("Adamant javelin heads", 76, 62.5f, ItemID.ADAMANT_JAVELIN_HEADS),
	ADAMANT_FULL_HELM("Adamant full helm", 77, 125, ItemID.ADAMANT_FULL_HELM),
	ADAMANT_KNIFE("Adamant knife", 77, 62.5f, ItemID.ADAMANT_KNIFE),
	ADAMANT_SQ_SHIELD("Adamant sq shield", 78, 125, ItemID.ADAMANT_SQ_SHIELD),
	ADAMANT_WARHAMMER("Adamant warhammer", 79, 187.5f, ItemID.ADAMANT_WARHAMMER),
	ADAMANT_BATTLEAXE("Adamant battleaxe", 80, 187.5f, ItemID.ADAMANT_BATTLEAXE),
	ADAMANT_CHAINBODY("Adamant chainbody", 81, 187.5f, ItemID.ADAMANT_CHAINBODY),
	ADAMANT_KITESHIELD("Adamant kiteshield", 82, 187.5f, ItemID.ADAMANT_KITESHIELD),
	ADAMANT_CLAWS("Adamant claws", 83, 125, ItemID.ADAMANT_CLAWS),
	ADAMANT_2H_SWORD("Adamant 2h sword", 84, 187.5f, ItemID.ADAMANT_2H_SWORD),
	RUNITE_BAR("Runite bar", 85, 50, ItemID.RUNITE_BAR),
	RUNE_DAGGER("Rune dagger", 85, 75, ItemID.RUNE_DAGGER),
	RUNE_AXE("Rune axe", 86, 75, ItemID.RUNE_AXE),
	ADAMANT_PLATESKIRT("Adamant plateskirt", 86, 187.5f, ItemID.ADAMANT_PLATESKIRT),
	ADAMANT_PLATELEGS("Adamant platelegs", 86, 187.5f, ItemID.ADAMANT_PLATELEGS),
	RUNE_MACE("Rune mace", 87, 75, ItemID.RUNE_MACE),
	RUNITE_BOLTS_UNF("Runite bolts (unf)", 88, 75, ItemID.RUNITE_BOLTS_UNF),
	RUNE_MED_HELM("Rune med helm", 88, 75, ItemID.RUNE_MED_HELM),
	ADAMANT_PLATEBODY("Adamant platebody", 88, 312.5f, ItemID.ADAMANT_PLATEBODY),
	RUNE_SWORD("Rune sword", 89, 75, ItemID.RUNE_SWORD),
	RUNE_NAILS("Rune nails", 89, 75, ItemID.RUNE_NAILS),
	RUNE_DART_TIP("Rune dart tip", 89, 75, ItemID.RUNE_DART_TIP),
	RUNE_ARROWTIPS("Rune arrowtips", 90, 75, ItemID.RUNE_ARROWTIPS),
	RUNE_SCIMITAR("Rune scimitar", 90, 150, ItemID.RUNE_SCIMITAR),
	RUNE_HASTA("Rune hasta", 90, 150, ItemID.RUNE_HASTA),
	RUNE_SPEAR("Rune spear", 90, 150, ItemID.RUNE_SPEAR),
	DRAGONFIRE_SHIELD("Dragonfire shield", 90, 2000, ItemID.DRAGONFIRE_SHIELD),
	RUNE_LONGSWORD("Rune longsword", 91, 150, ItemID.RUNE_LONGSWORD),
	RUNE_JAVELIN_HEADS("Rune javelin heads", 91, 75, ItemID.RUNE_JAVELIN_HEADS),
	RUNITE_LIMBS("Runite limbs", 91, 75, ItemID.RUNITE_LIMBS),
	RUNE_KNIFE("Rune knife", 92, 75, ItemID.RUNE_KNIFE),
	RUNE_FULL_HELM("Rune full helm", 92, 150, ItemID.RUNE_FULL_HELM),
	RUNE_SQ_SHIELD("Rune sq shield", 93, 150, ItemID.RUNE_SQ_SHIELD),
	RUNE_WARHAMMER("Rune warhammer", 94, 225, ItemID.RUNE_WARHAMMER),
	RUNE_BATTLEAXE("Rune battleaxe", 95, 225, ItemID.RUNE_BATTLEAXE),
	RUNE_CHAINBODY("Rune chainbody", 96, 225, ItemID.RUNE_CHAINBODY),
	RUNE_KITESHIELD("Rune kiteshield", 97, 225, ItemID.RUNE_KITESHIELD),
	RUNE_CLAWS("Rune claws", 98, 150, ItemID.RUNE_CLAWS),
	RUNE_PLATEBODY("Rune platebody", 99, 375, ItemID.RUNE_PLATEBODY),
	RUNE_PLATESKIRT("Rune plateskirt", 99, 225, ItemID.RUNE_PLATESKIRT),
	RUNE_PLATELEGS("Rune platelegs", 99, 225, ItemID.RUNE_PLATELEGS),
	RUNE_2H_SWORD("Rune 2h sword", 99, 225, ItemID.RUNE_2H_SWORD),
	;

	private final String name;
	private final int level;
	private final float xp;
	private final int icon;
}
