/*
 * This file is generated by jOOQ.
 */
package net.runelite.client.database.data.tables;


import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import javax.annotation.processing.Generated;
import net.runelite.client.database.data.Indexes;
import net.runelite.client.database.data.Keys;
import net.runelite.client.database.data.Public;
import net.runelite.client.database.data.tables.records.LoottrackerlinkRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.12.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Loottrackerlink extends TableImpl<LoottrackerlinkRecord>
{

	private static final long serialVersionUID = -1694278583;

	/**
	 * The reference instance of <code>PUBLIC.LOOTTRACKERLINK</code>
	 */
	public static final Loottrackerlink LOOTTRACKERLINK = new Loottrackerlink();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<LoottrackerlinkRecord> getRecordType()
	{
		return LoottrackerlinkRecord.class;
	}

	/**
	 * The column <code>PUBLIC.LOOTTRACKERLINK.LINKUNIQUEID</code>.
	 */
	public final TableField<LoottrackerlinkRecord, UUID> LINKUNIQUEID = createField(DSL.name("LINKUNIQUEID"), org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.LOOTTRACKERLINK.EVENTUNIQUEID</code>.
	 */
	public final TableField<LoottrackerlinkRecord, UUID> EVENTUNIQUEID = createField(DSL.name("EVENTUNIQUEID"), org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.LOOTTRACKERLINK.DROPUNIQUEID</code>.
	 */
	public final TableField<LoottrackerlinkRecord, UUID> DROPUNIQUEID = createField(DSL.name("DROPUNIQUEID"), org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.LOOTTRACKERLINK.USERUNIQUEID</code>.
	 */
	public final TableField<LoottrackerlinkRecord, UUID> USERUNIQUEID = createField(DSL.name("USERUNIQUEID"), org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * Create a <code>PUBLIC.LOOTTRACKERLINK</code> table reference
	 */
	public Loottrackerlink()
	{
		this(DSL.name("LOOTTRACKERLINK"), null);
	}

	/**
	 * Create an aliased <code>PUBLIC.LOOTTRACKERLINK</code> table reference
	 */
	public Loottrackerlink(String alias)
	{
		this(DSL.name(alias), LOOTTRACKERLINK);
	}

	/**
	 * Create an aliased <code>PUBLIC.LOOTTRACKERLINK</code> table reference
	 */
	public Loottrackerlink(Name alias)
	{
		this(alias, LOOTTRACKERLINK);
	}

	private Loottrackerlink(Name alias, Table<LoottrackerlinkRecord> aliased)
	{
		this(alias, aliased, null);
	}

	private Loottrackerlink(Name alias, Table<LoottrackerlinkRecord> aliased, Field<?>[] parameters)
	{
		super(alias, null, aliased, parameters, DSL.comment(""));
	}

	public <O extends Record> Loottrackerlink(Table<O> child, ForeignKey<O, LoottrackerlinkRecord> key)
	{
		super(child, key, LOOTTRACKERLINK);
	}

	@Override
	public Schema getSchema()
	{
		return Public.PUBLIC;
	}

	@Override
	public List<Index> getIndexes()
	{
		return Arrays.<Index>asList(Indexes.FK_LOOTTRACKERDROP_INDEX_6, Indexes.FK_LOOTTRACKEREVENT_INDEX_6, Indexes.FK_USER_INDEX_6);
	}

	@Override
	public List<ForeignKey<LoottrackerlinkRecord, ?>> getReferences()
	{
		return Arrays.<ForeignKey<LoottrackerlinkRecord, ?>>asList(Keys.FK_LOOTTRACKEREVENT, Keys.FK_LOOTTRACKERDROP, Keys.FK_USER);
	}

	public Loottrackerevents loottrackerevents()
	{
		return new Loottrackerevents(this, Keys.FK_LOOTTRACKEREVENT);
	}

	public Loottrackerloot loottrackerloot()
	{
		return new Loottrackerloot(this, Keys.FK_LOOTTRACKERDROP);
	}

	public User user()
	{
		return new User(this, Keys.FK_USER);
	}

	@Override
	public Loottrackerlink as(String alias)
	{
		return new Loottrackerlink(DSL.name(alias), this);
	}

	@Override
	public Loottrackerlink as(Name alias)
	{
		return new Loottrackerlink(alias, this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Loottrackerlink rename(String name)
	{
		return new Loottrackerlink(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Loottrackerlink rename(Name name)
	{
		return new Loottrackerlink(name, null);
	}

	// -------------------------------------------------------------------------
	// Row4 type methods
	// -------------------------------------------------------------------------

	@Override
	public Row4<UUID, UUID, UUID, UUID> fieldsRow()
	{
		return (Row4) super.fieldsRow();
	}
}
