/*
 * This file is generated by jOOQ.
 */
package net.runelite.client.database.data.tables;


import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import javax.annotation.Generated;
import net.runelite.client.database.data.Indexes;
import net.runelite.client.database.data.Keys;
import net.runelite.client.database.data.Public;
import net.runelite.client.database.data.tables.records.LoottrackerlootRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.11.12"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Loottrackerloot extends TableImpl<LoottrackerlootRecord>
{

	private static final long serialVersionUID = 1952959378;

	/**
	 * The reference instance of <code>PUBLIC.LOOTTRACKERLOOT</code>
	 */
	public static final Loottrackerloot LOOTTRACKERLOOT = new Loottrackerloot();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<LoottrackerlootRecord> getRecordType()
	{
		return LoottrackerlootRecord.class;
	}

	/**
	 * The column <code>PUBLIC.LOOTTRACKERLOOT.UNIQUEID</code>.
	 */
	public final TableField<LoottrackerlootRecord, UUID> UNIQUEID = createField("UNIQUEID", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.LOOTTRACKERLOOT.ITEMID</code>.
	 */
	public final TableField<LoottrackerlootRecord, Integer> ITEMID = createField("ITEMID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.LOOTTRACKERLOOT.QUANTITY</code>.
	 */
	public final TableField<LoottrackerlootRecord, Integer> QUANTITY = createField("QUANTITY", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>PUBLIC.LOOTTRACKERLOOT</code> table reference
	 */
	public Loottrackerloot()
	{
		this(DSL.name("LOOTTRACKERLOOT"), null);
	}

	/**
	 * Create an aliased <code>PUBLIC.LOOTTRACKERLOOT</code> table reference
	 */
	public Loottrackerloot(String alias)
	{
		this(DSL.name(alias), LOOTTRACKERLOOT);
	}

	/**
	 * Create an aliased <code>PUBLIC.LOOTTRACKERLOOT</code> table reference
	 */
	public Loottrackerloot(Name alias)
	{
		this(alias, LOOTTRACKERLOOT);
	}

	private Loottrackerloot(Name alias, Table<LoottrackerlootRecord> aliased)
	{
		this(alias, aliased, null);
	}

	private Loottrackerloot(Name alias, Table<LoottrackerlootRecord> aliased, Field<?>[] parameters)
	{
		super(alias, null, aliased, parameters, DSL.comment(""));
	}

	public <O extends Record> Loottrackerloot(Table<O> child, ForeignKey<O, LoottrackerlootRecord> key)
	{
		super(child, key, LOOTTRACKERLOOT);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Schema getSchema()
	{
		return Public.PUBLIC;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<Index> getIndexes()
	{
		return Arrays.<Index>asList(Indexes.PRIMARY_KEY_6);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<LoottrackerlootRecord> getPrimaryKey()
	{
		return Keys.PK_LOOTUNIQUEID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<LoottrackerlootRecord>> getKeys()
	{
		return Arrays.<UniqueKey<LoottrackerlootRecord>>asList(Keys.PK_LOOTUNIQUEID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Loottrackerloot as(String alias)
	{
		return new Loottrackerloot(DSL.name(alias), this);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Loottrackerloot as(Name alias)
	{
		return new Loottrackerloot(alias, this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Loottrackerloot rename(String name)
	{
		return new Loottrackerloot(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Loottrackerloot rename(Name name)
	{
		return new Loottrackerloot(name, null);
	}
}
