/*
 * Copyright (c) 2019, Hydrox6 <ikada@protonmail.ch>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package net.runelite.client.plugins.itemidentification;

import com.google.common.collect.ImmutableMap;
import java.util.Map;
import java.util.function.Predicate;
import lombok.AllArgsConstructor;
import net.runelite.api.ItemID;

enum ItemIdentification
{
	//Seeds
	GUAM_SEED(Type.SEED, false, "Guam", "G", ItemID.GUAM_SEED),
	MARRENTILL_SEED(Type.SEED, false, "Marren", "M", ItemID.MARRENTILL_SEED),
	TARROMIN_SEED(Type.SEED, false, "Tarro", "TAR", ItemID.TARROMIN_SEED),
	HARRALANDER_SEED(Type.SEED, false, "Harra", "H", ItemID.HARRALANDER_SEED),
	RANARR_SEED(Type.SEED, false, "Ranarr", "R", ItemID.RANARR_SEED),
	TOADFLAX_SEED(Type.SEED, false, "Toad", "TOA", ItemID.TOADFLAX_SEED),
	IRIT_SEED(Type.SEED, false, "Irit", "I", ItemID.IRIT_SEED),
	AVANTOE_SEED(Type.SEED, false, "Avan", "A", ItemID.AVANTOE_SEED),
	KWUARM_SEED(Type.SEED, false, "Kwuarm", "K", ItemID.KWUARM_SEED),
	SNAPDRAGON_SEED(Type.SEED, false, "Snap", "S", ItemID.SNAPDRAGON_SEED),
	CADANTINE_SEED(Type.SEED, false, "Cadan", "C", ItemID.CADANTINE_SEED),
	LANTADYME_SEED(Type.SEED, false, "Lanta", "L", ItemID.LANTADYME_SEED),
	DWARF_WEED_SEED(Type.SEED, false, "Dwarf", "D", ItemID.DWARF_WEED_SEED),
	TORSTOL_SEED(Type.SEED, false, "Torstol", "TOR", ItemID.TORSTOL_SEED),

	POISON_IVY_SEED(Type.SEED, false, "Ivy", "I", ItemID.POISON_IVY_SEED),
	WHITEBERRY_SEED(Type.SEED, false, "White", "W", ItemID.WHITEBERRY_SEED),
	SEAWEED_SPORE(Type.SEED, true, "Seaweed", "SW", ItemID.SEAWEED_SPORE),

	HESPORI_SEED(Type.SEED, true, "Hespori", "HES", ItemID.HESPORI_SEED),
	KRONOS_SEED(Type.SEED, true, "Kronos", "KRO", ItemID.KRONOS_SEED),
	IASOR_SEED(Type.SEED, true, "Iasor", "IA", ItemID.IASOR_SEED),
	ATTAS_SEED(Type.SEED, true, "Attas", "AT", ItemID.ATTAS_SEED),
	CELASTRUS_SEED(Type.SEED, true, "Celas", "CEL", ItemID.CELASTRUS_SEED),
	SPIRIT_SEED(Type.SEED, true, "Spirit", "SPI", ItemID.SPIRIT_SEED),
	CALQUAT_SEED(Type.SEED, true, "Calquat", "CAL", ItemID.CALQUAT_TREE_SEED),

	ACORN(Type.SEED, true, "Oak", "OAK", ItemID.ACORN),
	WILLOW_SEED(Type.SEED, true, "Willow", "WIL", ItemID.WILLOW_SEED),
	MAPLE_SEED(Type.SEED, true, "Maple", "MAP", ItemID.MAPLE_SEED),
	YEW_SEED(Type.SEED, true, "Yew", "YEW", ItemID.YEW_SEED),
	MAGIC_SEED(Type.SEED, true, "Magic", "MAG", ItemID.MAGIC_SEED),
	REDWOOD_SEED(Type.SEED, true, "Red", "RED", ItemID.REDWOOD_TREE_SEED),
	TEAK_SEED(Type.SEED, true, "Teak", "TEAK", ItemID.TEAK_SEED),
	MAHOGANY_SEED(Type.SEED, true, "Mahog", "MAH", ItemID.MAHOGANY_SEED),
	CRYSTAL_ACORN(Type.SEED, true, "Crystal", "CRY", ItemID.CRYSTAL_ACORN),

	//Sacks
	SACK(Type.SACK, false, "Empty", "EMP", ItemID.EMPTY_SACK),
	CABBAGE_SACK(Type.SACK, false, "Cabbage", "CAB", ItemID.CABBAGES1, ItemID.CABBAGES2, ItemID.CABBAGES3, ItemID.CABBAGES4, ItemID.CABBAGES5, ItemID.CABBAGES6, ItemID.CABBAGES7, ItemID.CABBAGES8, ItemID.CABBAGES9, ItemID.CABBAGES10),
	ONION_SACK(Type.SACK, false, "Onion", "ONI", ItemID.ONIONS1, ItemID.ONIONS2, ItemID.ONIONS3, ItemID.ONIONS4, ItemID.ONIONS5, ItemID.ONIONS6, ItemID.ONIONS7, ItemID.ONIONS8, ItemID.ONIONS9, ItemID.ONIONS10),
	POTATO_SACK(Type.SACK, false, "Potato", "POT", ItemID.POTATOES1, ItemID.POTATOES2, ItemID.POTATOES3, ItemID.POTATOES4, ItemID.POTATOES5, ItemID.POTATOES6, ItemID.POTATOES7, ItemID.POTATOES8, ItemID.POTATOES9, ItemID.POTATOES10),

	//Herbs
	GUAM(Type.HERB, false, "Guam", "G", ItemID.GUAM_LEAF, ItemID.GRIMY_GUAM_LEAF),
	MARRENTILL(Type.HERB, true, "Marren", "M", ItemID.MARRENTILL, ItemID.GRIMY_MARRENTILL),
	TARROMIN(Type.HERB, true, "Tarro", "TAR", ItemID.TARROMIN, ItemID.GRIMY_TARROMIN),
	HARRALANDER(Type.HERB, true, "Harra", "H", ItemID.HARRALANDER, ItemID.GRIMY_HARRALANDER),
	RANARR(Type.HERB, true, "Ranarr", "R", ItemID.RANARR_WEED, ItemID.GRIMY_RANARR_WEED),
	TOADFLAX(Type.HERB, true, "Toad", "TOA", ItemID.TOADFLAX, ItemID.GRIMY_TOADFLAX),
	IRIT(Type.HERB, true, "Irit", "I", ItemID.IRIT_LEAF, ItemID.GRIMY_IRIT_LEAF),
	AVANTOE(Type.HERB, true, "Avan", "A", ItemID.AVANTOE, ItemID.GRIMY_AVANTOE),
	KWUARM(Type.HERB, false, "Kwuarm", "K", ItemID.KWUARM, ItemID.GRIMY_KWUARM),
	SNAPDRAGON(Type.HERB, true, "Snap", "S", ItemID.SNAPDRAGON, ItemID.GRIMY_SNAPDRAGON),
	CADANTINE(Type.HERB, false, "Cadan", "C", ItemID.CADANTINE, ItemID.GRIMY_CADANTINE),
	LANTADYME(Type.HERB, true, "Lanta", "L", ItemID.LANTADYME, ItemID.GRIMY_LANTADYME),
	DWARF_WEED(Type.HERB, true, "Dwarf", "D", ItemID.DWARF_WEED, ItemID.GRIMY_DWARF_WEED),
	TORSTOL(Type.HERB, false, "Torstol", "TOR", ItemID.TORSTOL, ItemID.GRIMY_TORSTOL),

	ARDRIGAL(Type.HERB, true, "Ardrig", "ARD", ItemID.ARDRIGAL, ItemID.GRIMY_ARDRIGAL),
	ROGUES_PURSE(Type.HERB, false, "Rogue", "ROG", ItemID.ROGUES_PURSE, ItemID.GRIMY_ROGUES_PURSE),
	SITO_FOIL(Type.HERB, false, "Sito", "SF", ItemID.SITO_FOIL, ItemID.GRIMY_SITO_FOIL),
	SNAKE_WEED(Type.HERB, true, "Snake", "SW", ItemID.SNAKE_WEED, ItemID.GRIMY_SNAKE_WEED),
	VOLENCIA_MOSS(Type.HERB, false, "Volenc", "V", ItemID.VOLENCIA_MOSS, ItemID.GRIMY_VOLENCIA_MOSS),
	
	//Logs
	RED_LOGS(Type.LOGS, true, "Red", "RED", ItemID.RED_LOGS),
	GREEN_LOGS(Type.LOGS, true, "Green", "GRE", ItemID.GREEN_LOGS),
	BLUE_LOGS(Type.LOGS, true, "Blue", "BLU", ItemID.BLUE_LOGS),
	WHITE_LOGS(Type.LOGS, true, "White", "WHI", ItemID.WHITE_LOGS),
	PURPLE_LOGS(Type.LOGS, true, "Purple", "PUR", ItemID.PURPLE_LOGS),

	SCRAPEY_TREE_LOGS(Type.LOGS, true, "Scrapey", "SCRAP", ItemID.SCRAPEY_TREE_LOGS),

	LOG(Type.LOGS, true, "Log", "LOG", ItemID.LOGS),
	ACHEY_TREE_LOG(Type.LOGS, true, "Achey", "ACH", ItemID.ACHEY_TREE_LOGS),
	OAK_LOG(Type.LOGS, true, "Oak", "OAK", ItemID.OAK_LOGS),
	WILLOW_LOG(Type.LOGS, true, "Willow", "WIL", ItemID.WILLOW_LOGS),
	TEAK_LOG(Type.LOGS, true, "Teak", "TEAK", ItemID.TEAK_LOGS),
	JUNIPER_LOG(Type.LOGS, true, "Juniper", "JUN", ItemID.JUNIPER_LOGS),
	MAPLE_LOG(Type.LOGS, true, "Maple", "MAP", ItemID.MAPLE_LOGS),
	MAHOGANY_LOG(Type.LOGS, true, "Mahog", "MAH", ItemID.MAHOGANY_LOGS),
	ARCTIC_PINE_LOG(Type.LOGS, true, "Arctic", "ARC", ItemID.ARCTIC_PINE_LOGS),
	YEW_LOG(Type.LOGS, true, "Yew", "YEW", ItemID.YEW_LOGS),
	BLISTERWOOD_LOG(Type.LOGS, true, "Blister", "BLI", ItemID.BLISTERWOOD_LOGS),
	MAGIC_LOG(Type.LOGS, true, "Magic", "MAG", ItemID.MAGIC_LOGS),
	REDWOOD_LOG(Type.LOGS, true, "Red", "RED", ItemID.REDWOOD_LOGS),

	PYRE_LOGS(Type.LOGS, true, "Pyre", "P", ItemID.PYRE_LOGS),
	ARCTIC_PYRE_LOGS(Type.LOGS, true, "Art P", "AP", ItemID.ARCTIC_PYRE_LOGS),
	OAK_PYRE_LOGS(Type.LOGS, true, "Oak P", "OAKP", ItemID.OAK_PYRE_LOGS),
	WILLOW_PYRE_LOGS(Type.LOGS, true, "Wil P", "WILP", ItemID.WILLOW_PYRE_LOGS),
	TEAK_PYRE_LOGS(Type.LOGS, true, "Teak P", "TEAKP", ItemID.TEAK_PYRE_LOGS),
	MAPLE_PYRE_LOGS(Type.LOGS, true, "Map P", "MAPP", ItemID.MAPLE_PYRE_LOGS),
	MAHOGANY_PYRE_LOGS(Type.LOGS, true, "Mah P", "MAHP", ItemID.MAHOGANY_PYRE_LOGS),
	YEW_PYRE_LOGS(Type.LOGS, true, "Yew P", "YEWP", ItemID.YEW_PYRE_LOGS),
	MAGIC_PYRE_LOGS(Type.LOGS, true, "Mag P", "MAGP", ItemID.MAGIC_PYRE_LOGS),
	REDWOOD_PYRE_LOGS(Type.LOGS, true, "Red P", "REDP", ItemID.REDWOOD_PYRE_LOGS),

	//Planks
	PLANK(Type.PLANK, true, "Plank", "PLANK", ItemID.PLANK),
	OAK_PLANK(Type.PLANK, true, "Oak", "OAK", ItemID.OAK_PLANK),
	TEAK_PLANK(Type.PLANK, true, "Teak", "TEAK", ItemID.TEAK_PLANK),
	MAHOGANY_PLANK(Type.PLANK, true, "Mahog", "MAH", ItemID.MAHOGANY_PLANK),
	WAXWOOD_PLANK(Type.PLANK, true, "Wax", "WAX", ItemID.WAXWOOD_PLANK),
	MALLIGNUM_ROOT_PLANK(Type.PLANK, true, "Mallig", "MALL", ItemID.MALLIGNUM_ROOT_PLANK),

	//Saplings
	OAK_SAPLING(Type.SAPLING, false, "Oak", "OAK", ItemID.OAK_SAPLING, ItemID.OAK_SEEDLING, ItemID.OAK_SEEDLING_W),
	WILLOW_SAPLING(Type.SAPLING, false, "Willow", "WIL", ItemID.WILLOW_SAPLING, ItemID.WILLOW_SEEDLING, ItemID.WILLOW_SEEDLING_W),
	MAPLE_SAPLING(Type.SAPLING, false, "Maple", "MAP", ItemID.MAPLE_SAPLING, ItemID.MAPLE_SEEDLING, ItemID.MAPLE_SEEDLING_W),
	YEW_SAPLING(Type.SAPLING, false, "Yew", "YEW", ItemID.YEW_SAPLING, ItemID.YEW_SEEDLING, ItemID.YEW_SEEDLING_W),
	MAGIC_SAPLING(Type.SAPLING, false, "Magic", "MAG", ItemID.MAGIC_SAPLING, ItemID.MAGIC_SEEDLING, ItemID.MAGIC_SEEDLING_W),
	REDWOOD_SAPLING(Type.SAPLING, false, "Red", "RED", ItemID.REDWOOD_SAPLING, ItemID.REDWOOD_SEEDLING, ItemID.REDWOOD_SEEDLING_W),
	SPIRIT_SAPLING(Type.SAPLING, false, "Spirit", "SPI", ItemID.SPIRIT_SAPLING, ItemID.SPIRIT_SEEDLING, ItemID.SPIRIT_SEEDLING_W),
	CRYSTAL_SAPLING(Type.SAPLING, false, "Crystal", "CRY", ItemID.CRYSTAL_SAPLING, ItemID.CRYSTAL_SEEDLING, ItemID.CRYSTAL_SEEDLING_W),

	APPLE_SAPLING(Type.SAPLING, false, "Apple", "APP", ItemID.APPLE_SAPLING, ItemID.APPLE_SEEDLING, ItemID.APPLE_SEEDLING_W),
	BANANA_SAPLING(Type.SAPLING, false, "Banana", "BAN", ItemID.BANANA_SAPLING, ItemID.BANANA_SEEDLING, ItemID.BANANA_SEEDLING_W),
	ORANGE_SAPLING(Type.SAPLING, false, "Orange", "ORA", ItemID.ORANGE_SAPLING, ItemID.ORANGE_SEEDLING, ItemID.ORANGE_SEEDLING_W),
	CURRY_SAPLING(Type.SAPLING, false, "Curry", "CUR", ItemID.CURRY_SAPLING, ItemID.CURRY_SEEDLING, ItemID.CURRY_SEEDLING_W),
	PINEAPPLE_SAPLING(Type.SAPLING, false, "Pine", "PINE", ItemID.PINEAPPLE_SAPLING, ItemID.PINEAPPLE_SEEDLING, ItemID.PINEAPPLE_SEEDLING_W),
	PAPAYA_SAPLING(Type.SAPLING, false, "Papaya", "PAP", ItemID.PAPAYA_SAPLING, ItemID.PAPAYA_SEEDLING, ItemID.PAPAYA_SEEDLING_W),
	PALM_SAPLING(Type.SAPLING, false, "Palm", "PALM", ItemID.PALM_SAPLING, ItemID.PALM_SEEDLING, ItemID.PALM_SEEDLING_W),
	DRAGONFRUIT_SAPLING(Type.SAPLING, false, "Dragon", "DRAG", ItemID.DRAGONFRUIT_SAPLING, ItemID.DRAGONFRUIT_SEEDLING, ItemID.DRAGONFRUIT_SEEDLING_W),

	TEAK_SAPLING(Type.SAPLING, false, "Teak", "TEAK", ItemID.TEAK_SAPLING, ItemID.TEAK_SEEDLING, ItemID.TEAK_SEEDLING_W),
	MAHOGANY_SAPLING(Type.SAPLING, false, "Mahog", "MAHOG", ItemID.MAHOGANY_SAPLING, ItemID.MAHOGANY_SEEDLING, ItemID.MAHOGANY_SEEDLING_W),
	CALQUAT_SAPLING(Type.SAPLING, false, "Calquat", "CALQ", ItemID.CALQUAT_SAPLING, ItemID.CALQUAT_SEEDLING, ItemID.CALQUAT_SEEDLING_W),
	CELASTRUS_SAPLING(Type.SAPLING, false, "Celas", "CEL", ItemID.CELASTRUS_SAPLING, ItemID.CELASTRUS_SEEDLING, ItemID.CELASTRUS_SEEDLING_W),

	//Compost
	COMPOST(Type.COMPOST, false, "Compost", "COM", ItemID.COMPOST),
	SUPERCOMPOST(Type.COMPOST, false, "Sup Com", "SCOM", ItemID.SUPERCOMPOST),
	ULTRACOMPOST(Type.COMPOST, false, "Ult Com", "UCOM", ItemID.ULTRACOMPOST),

	//Ores
	COPPER_ORE(Type.ORE, true, "Copper", "COP", ItemID.COPPER_ORE),
	TIN_ORE(Type.ORE, true, "Tin", "TIN", ItemID.TIN_ORE),
	IRON_ORE(Type.ORE, true, "Iron", "IRO", ItemID.IRON_ORE),
	SILVER_ORE(Type.ORE, true, "Silver", "SIL", ItemID.SILVER_ORE),
	COAL_ORE(Type.ORE, true, "Coal", "COA", ItemID.COAL),
	GOLD_ORE(Type.ORE, true, "Gold", "GOL", ItemID.GOLD_ORE),
	MITHRIL_ORE(Type.ORE, true, "Mithril", "MIT", ItemID.MITHRIL_ORE),
	ADAMANTITE_ORE(Type.ORE, true, "Adaman", "ADA", ItemID.ADAMANTITE_ORE),
	RUNITE_ORE(Type.ORE, true, "Runite", "RUN", ItemID.RUNITE_ORE),

	RUNE_ESSENCE(Type.ORE, true, "R.Ess", "R.E.", ItemID.RUNE_ESSENCE),
	PURE_ESSENCE(Type.ORE, true, "P.Ess", "P.E.", ItemID.PURE_ESSENCE),

	PAYDIRT(Type.ORE, true, "Paydirt", "PAY", ItemID.PAYDIRT),
	AMETHYST(Type.ORE, true, "Amethy", "AME", ItemID.AMETHYST),
	LOVAKITE_ORE(Type.ORE, true, "Lovakit", "LOV", ItemID.LOVAKITE_ORE),
	BLURITE_ORE(Type.ORE, true, "Blurite", "BLU", ItemID.BLURITE_ORE),
	ELEMENTAL_ORE(Type.ORE, true, "Element", "ELE", ItemID.ELEMENTAL_ORE),
	DAEYALT_ORE(Type.ORE, true, "Daeyalt", "DAE", ItemID.DAEYALT_ORE),
	LUNAR_ORE(Type.ORE, true, "Lunar", "LUN", ItemID.LUNAR_ORE),

	//Bars
	BRONZE_BAR(Type.BAR, true, "Bronze", "BRO", ItemID.BRONZE_BAR),
	IRON_BAR(Type.BAR, true, "Iron", "IRO", ItemID.IRON_BAR),
	SILVER_BAR(Type.BAR, true, "Silver", "SIL", ItemID.SILVER_BAR),
	STEEL_BAR(Type.BAR, true, "Steel", "STE", ItemID.STEEL_BAR),
	GOLD_BAR(Type.BAR, true, "Gold", "GOL", ItemID.GOLD_BAR),
	MITHRIL_BAR(Type.BAR, true, "Mithril", "MIT", ItemID.MITHRIL_BAR),
	ADAMANTITE_BAR(Type.BAR, true, "Adaman", "ADA", ItemID.ADAMANTITE_BAR),
	RUNITE_BAR(Type.BAR, true, "Runite", "RUN", ItemID.RUNITE_BAR),

	//Gems
	SAPPHIRE(Type.GEM, true, "Sapphir", "S", ItemID.UNCUT_SAPPHIRE, ItemID.SAPPHIRE),
	EMERALD(Type.GEM, true, "Emerald", "E", ItemID.UNCUT_EMERALD, ItemID.EMERALD),
	RUBY(Type.GEM, true, "Ruby", "R", ItemID.UNCUT_RUBY, ItemID.RUBY),
	DIAMOND(Type.GEM, true, "Diamon", "DI", ItemID.UNCUT_DIAMOND, ItemID.DIAMOND),
	OPAL(Type.GEM, false, "Opal", "OP", ItemID.UNCUT_OPAL, ItemID.OPAL),
	JADE(Type.GEM, false, "Jade", "J", ItemID.UNCUT_JADE, ItemID.JADE),
	RED_TOPAZ(Type.GEM, true, "Topaz", "T", ItemID.UNCUT_RED_TOPAZ, ItemID.RED_TOPAZ),
	DRAGONSTONE(Type.GEM, true, "Dragon", "DR", ItemID.UNCUT_DRAGONSTONE, ItemID.DRAGONSTONE),
	ONYX(Type.GEM, true, "Onyx", "ON", ItemID.UNCUT_ONYX, ItemID.ONYX),
	ZENYTE(Type.GEM, true, "Zenyte", "Z", ItemID.UNCUT_ZENYTE, ItemID.ZENYTE),

	// Potions
	ATTACK(Type.POTION, false, "Att", "A", ItemID.ATTACK_POTION4, ItemID.ATTACK_POTION3, ItemID.ATTACK_POTION2, ItemID.ATTACK_POTION1),
	STRENGTH(Type.POTION, false, "Str", "S", ItemID.STRENGTH_POTION4, ItemID.STRENGTH_POTION3, ItemID.STRENGTH_POTION2, ItemID.STRENGTH_POTION1),
	DEFENCE(Type.POTION, false, "Def", "D", ItemID.DEFENCE_POTION4, ItemID.DEFENCE_POTION3, ItemID.DEFENCE_POTION2, ItemID.DEFENCE_POTION1),
	COMBAT(Type.POTION, true, "Com", "C", ItemID.COMBAT_POTION4, ItemID.COMBAT_POTION3, ItemID.COMBAT_POTION2, ItemID.COMBAT_POTION1),
	MAGIC(Type.POTION, true, "Magic", "M", ItemID.MAGIC_POTION4, ItemID.MAGIC_POTION3, ItemID.MAGIC_POTION2, ItemID.MAGIC_POTION1),
	RANGING(Type.POTION, false, "Range", "R", ItemID.RANGING_POTION4, ItemID.RANGING_POTION3, ItemID.RANGING_POTION2, ItemID.RANGING_POTION1),
	BASTION(Type.POTION, true, "Bastion", "B", ItemID.BASTION_POTION4, ItemID.BASTION_POTION3, ItemID.BASTION_POTION2, ItemID.BASTION_POTION1),
	BATTLEMAGE(Type.POTION, false, "BatMage", "B.M", ItemID.BATTLEMAGE_POTION4, ItemID.BATTLEMAGE_POTION3, ItemID.BATTLEMAGE_POTION2, ItemID.BATTLEMAGE_POTION1),

	SUPER_ATTACK(Type.POTION, true, "S.Att", "S.A", ItemID.SUPER_ATTACK4, ItemID.SUPER_ATTACK3, ItemID.SUPER_ATTACK2, ItemID.SUPER_ATTACK1),
	SUPER_STRENGTH(Type.POTION, true, "S.Str", "S.S", ItemID.SUPER_STRENGTH4, ItemID.SUPER_STRENGTH3, ItemID.SUPER_STRENGTH2, ItemID.SUPER_STRENGTH1),
	SUPER_DEFENCE(Type.POTION, false, "S.Def", "S.D", ItemID.SUPER_DEFENCE4, ItemID.SUPER_DEFENCE3, ItemID.SUPER_DEFENCE2, ItemID.SUPER_DEFENCE1),
	SUPER_COMBAT(Type.POTION, true, "S.Com", "S.C", ItemID.SUPER_COMBAT_POTION4, ItemID.SUPER_COMBAT_POTION3, ItemID.SUPER_COMBAT_POTION2, ItemID.SUPER_COMBAT_POTION1),
	SUPER_RANGING(Type.POTION, false, "S.Range", "S.Ra", ItemID.SUPER_RANGING_4, ItemID.SUPER_RANGING_3, ItemID.SUPER_RANGING_2, ItemID.SUPER_RANGING_1),
	SUPER_MAGIC(Type.POTION, false, "S.Magic", "S.M", ItemID.SUPER_MAGIC_POTION_4, ItemID.SUPER_MAGIC_POTION_3, ItemID.SUPER_MAGIC_POTION_2, ItemID.SUPER_MAGIC_POTION_1),

	DIVINE_SUPER_ATTACK(Type.POTION, true, "S.Att", "S.A", ItemID.DIVINE_SUPER_ATTACK_POTION4, ItemID.DIVINE_SUPER_ATTACK_POTION3, ItemID.DIVINE_SUPER_ATTACK_POTION2, ItemID.DIVINE_SUPER_ATTACK_POTION1),
	DIVINE_SUPER_DEFENCE(Type.POTION, false, "S.Def", "S.D", ItemID.DIVINE_SUPER_DEFENCE_POTION4, ItemID.DIVINE_SUPER_DEFENCE_POTION3, ItemID.DIVINE_SUPER_DEFENCE_POTION2, ItemID.DIVINE_SUPER_DEFENCE_POTION1),
	DIVINE_SUPER_STRENGTH(Type.POTION, true, "S.Str", "S.S", ItemID.DIVINE_SUPER_STRENGTH_POTION4, ItemID.DIVINE_SUPER_STRENGTH_POTION3, ItemID.DIVINE_SUPER_STRENGTH_POTION2, ItemID.DIVINE_SUPER_STRENGTH_POTION1),
	DIVINE_SUPER_COMBAT(Type.POTION, true, "S.Com", "S.C", ItemID.DIVINE_SUPER_COMBAT_POTION4, ItemID.DIVINE_SUPER_COMBAT_POTION3, ItemID.DIVINE_SUPER_COMBAT_POTION2, ItemID.DIVINE_SUPER_COMBAT_POTION1),
	DIVINE_RANGING(Type.POTION, true, "Range", "R", ItemID.DIVINE_RANGING_POTION4, ItemID.DIVINE_RANGING_POTION3, ItemID.DIVINE_RANGING_POTION2, ItemID.DIVINE_RANGING_POTION1),
	DIVINE_MAGIC(Type.POTION, true, "Magic", "M", ItemID.DIVINE_MAGIC_POTION4, ItemID.DIVINE_MAGIC_POTION3, ItemID.DIVINE_MAGIC_POTION2, ItemID.DIVINE_MAGIC_POTION1),
	DIVINE_BASTION(Type.POTION, true, "Bastion", "B", ItemID.DIVINE_BASTION_POTION4, ItemID.DIVINE_BASTION_POTION3, ItemID.DIVINE_BASTION_POTION2, ItemID.DIVINE_BASTION_POTION1),
	DIVINE_BATTLEMAGE(Type.POTION, false, "BatMage", "B.M", ItemID.DIVINE_BATTLEMAGE_POTION4, ItemID.DIVINE_BATTLEMAGE_POTION3, ItemID.DIVINE_BATTLEMAGE_POTION2, ItemID.DIVINE_BATTLEMAGE_POTION1),

	RESTORE(Type.POTION, true, "Restore", "Re", ItemID.RESTORE_POTION4, ItemID.RESTORE_POTION3, ItemID.RESTORE_POTION2, ItemID.RESTORE_POTION1),
	GUTHIX_BALANCE(Type.POTION, false, "GuthBal", "G.B.", ItemID.GUTHIX_BALANCE4, ItemID.GUTHIX_BALANCE3, ItemID.GUTHIX_BALANCE2, ItemID.GUTHIX_BALANCE1),
	SUPER_RESTORE(Type.POTION, true, "S.Rest", "S.Re", ItemID.SUPER_RESTORE4, ItemID.SUPER_RESTORE3, ItemID.SUPER_RESTORE2, ItemID.SUPER_RESTORE1),
	PRAYER(Type.POTION, false, "Prayer", "P", ItemID.PRAYER_POTION4, ItemID.PRAYER_POTION3, ItemID.PRAYER_POTION2, ItemID.PRAYER_POTION1),
	ENERGY(Type.POTION, false, "Energy", "En", ItemID.ENERGY_POTION4, ItemID.ENERGY_POTION3, ItemID.ENERGY_POTION2, ItemID.ENERGY_POTION1),
	SUPER_ENERGY(Type.POTION, true, "S.Energ", "S.En", ItemID.SUPER_ENERGY4, ItemID.SUPER_ENERGY3, ItemID.SUPER_ENERGY2, ItemID.SUPER_ENERGY1),
	STAMINA(Type.POTION, true, "Stamina", "St", ItemID.STAMINA_POTION4, ItemID.STAMINA_POTION3, ItemID.STAMINA_POTION2, ItemID.STAMINA_POTION1),
	OVERLOAD(Type.POTION, true, "Overloa", "OL", ItemID.OVERLOAD_4, ItemID.OVERLOAD_3, ItemID.OVERLOAD_2, ItemID.OVERLOAD_1),
	ABSORPTION(Type.POTION, true, "Absorb", "Ab", ItemID.ABSORPTION_4, ItemID.ABSORPTION_3, ItemID.ABSORPTION_2, ItemID.ABSORPTION_1),

	ZAMORAK_BREW(Type.POTION, false, "ZammyBr", "Za", ItemID.ZAMORAK_BREW4, ItemID.ZAMORAK_BREW3, ItemID.ZAMORAK_BREW2, ItemID.ZAMORAK_BREW1),
	SARADOMIN_BREW(Type.POTION, false, "SaraBr", "Sa", ItemID.SARADOMIN_BREW4, ItemID.SARADOMIN_BREW3, ItemID.SARADOMIN_BREW2, ItemID.SARADOMIN_BREW1),

	ANTIPOISON(Type.POTION, false, "AntiP", "AP", ItemID.ANTIPOISON4, ItemID.ANTIPOISON3, ItemID.ANTIPOISON2, ItemID.ANTIPOISON1),
	SUPERANTIPOISON(Type.POTION, true, "S.AntiP", "S.AP", ItemID.SUPERANTIPOISON4, ItemID.SUPERANTIPOISON3, ItemID.SUPERANTIPOISON2, ItemID.SUPERANTIPOISON1),
	ANTIDOTE_P(Type.POTION, true, "Antid+", "A+", ItemID.ANTIDOTE4, ItemID.ANTIDOTE3, ItemID.ANTIDOTE2, ItemID.ANTIDOTE1),
	ANTIDOTE_PP(Type.POTION, true, "Antid++", "A++", ItemID.ANTIDOTE4_5952, ItemID.ANTIDOTE3_5954, ItemID.ANTIDOTE2_5956, ItemID.ANTIDOTE1_5958),
	ANTIVENOM(Type.POTION, true, "Anti-V", "AV", ItemID.ANTIVENOM4, ItemID.ANTIVENOM3, ItemID.ANTIVENOM2, ItemID.ANTIVENOM1),
	ANTIVENOM_P(Type.POTION, false, "Anti-V+", "AV+", ItemID.ANTIVENOM4_12913, ItemID.ANTIVENOM3_12915, ItemID.ANTIVENOM2_12917, ItemID.ANTIVENOM1_12919),

	RELICYMS_BALM(Type.POTION, true, "Relicym", "R.B", ItemID.RELICYMS_BALM4, ItemID.RELICYMS_BALM3, ItemID.RELICYMS_BALM2, ItemID.RELICYMS_BALM1),
	SANFEW_SERUM(Type.POTION, false, "Sanfew", "Sf", ItemID.SANFEW_SERUM4, ItemID.SANFEW_SERUM3, ItemID.SANFEW_SERUM2, ItemID.SANFEW_SERUM1),
	ANTIFIRE(Type.POTION, true, "Antif", "Af", ItemID.ANTIFIRE_POTION4, ItemID.ANTIFIRE_POTION3, ItemID.ANTIFIRE_POTION2, ItemID.ANTIFIRE_POTION1),
	EXTENDED_ANTIFIRE(Type.POTION, true, "E.Antif", "E.Af", ItemID.EXTENDED_ANTIFIRE4, ItemID.EXTENDED_ANTIFIRE3, ItemID.EXTENDED_ANTIFIRE2, ItemID.EXTENDED_ANTIFIRE1),
	SUPER_ANTIFIRE(Type.POTION, true, "S.Antif", "S.Af", ItemID.SUPER_ANTIFIRE_POTION4, ItemID.SUPER_ANTIFIRE_POTION3, ItemID.SUPER_ANTIFIRE_POTION2, ItemID.SUPER_ANTIFIRE_POTION1),
	EXTENDED_SUPER_ANTIFIRE(Type.POTION, true, "ES.Antif", "ES.Af", ItemID.EXTENDED_SUPER_ANTIFIRE4, ItemID.EXTENDED_SUPER_ANTIFIRE3, ItemID.EXTENDED_SUPER_ANTIFIRE2, ItemID.EXTENDED_SUPER_ANTIFIRE1),

	SERUM_207(Type.POTION, true, "Ser207", "S7", ItemID.SERUM_207_4, ItemID.SERUM_207_3, ItemID.SERUM_207_2, ItemID.SERUM_207_1),
	SERUM_208(Type.POTION, false, "Ser208", "S8", ItemID.SERUM_208_4, ItemID.SERUM_208_3, ItemID.SERUM_208_2, ItemID.SERUM_208_1),
	COMPOST_POTION(Type.POTION, true, "Compost", "COM", ItemID.COMPOST_POTION4, ItemID.COMPOST_POTION3, ItemID.COMPOST_POTION2, ItemID.COMPOST_POTION1),

	AGILITY(Type.POTION, true, "Agility", "Ag", ItemID.AGILITY_POTION4, ItemID.AGILITY_POTION3, ItemID.AGILITY_POTION2, ItemID.AGILITY_POTION1),
	FISHING(Type.POTION, false, "Fishing", "Fi", ItemID.FISHING_POTION4, ItemID.FISHING_POTION3, ItemID.FISHING_POTION2, ItemID.FISHING_POTION1),
	HUNTER(Type.POTION, true, "Hunter", "Hu", ItemID.HUNTER_POTION4, ItemID.HUNTER_POTION3, ItemID.HUNTER_POTION2, ItemID.HUNTER_POTION1),

	// Unfinished Potions
	GUAM_POTION(Type.POTION, true, "Guam", "G", ItemID.GUAM_POTION_UNF),
	MARRENTILL_POTION(Type.POTION, true, "Marren", "M", ItemID.MARRENTILL_POTION_UNF),
	TARROMIN_POTION(Type.POTION, true, "Tarro", "TAR", ItemID.TARROMIN_POTION_UNF),
	HARRALANDER_POTION(Type.POTION, true, "Harra", "H", ItemID.HARRALANDER_POTION_UNF),
	RANARR_POTION(Type.POTION, true, "Ranarr", "R", ItemID.RANARR_POTION_UNF),
	TOADFLAX_POTION(Type.POTION, true, "Toad", "TOA", ItemID.TOADFLAX_POTION_UNF),
	IRIT_POTION(Type.POTION, true, "Irit", "I", ItemID.IRIT_POTION_UNF),
	AVANTOE_POTION(Type.POTION, true, "Avan", "A", ItemID.AVANTOE_POTION_UNF),
	KWUARM_POTION(Type.POTION, true, "Kwuarm", "K", ItemID.KWUARM_POTION_UNF),
	SNAPDRAGON_POTION(Type.POTION, true, "Snap", "S", ItemID.SNAPDRAGON_POTION_UNF),
	CADANTINE_POTION(Type.POTION, true, "Cadan", "C", ItemID.CADANTINE_POTION_UNF),
	LANTADYME_POTION(Type.POTION, true, "Lanta", "L", ItemID.LANTADYME_POTION_UNF),
	DWARF_WEED_POTION(Type.POTION, true, "Dwarf", "D", ItemID.DWARF_WEED_POTION_UNF),
	TORSTOL_POTION(Type.POTION, true, "Torstol", "TOR", ItemID.TORSTOL_POTION_UNF),

	// Impling jars
	BABY_IMPLING(Type.IMPLING_JAR, true, "Baby", "B", ItemID.BABY_IMPLING_JAR),
	YOUNG_IMPLING(Type.IMPLING_JAR, true, "Young", "Y", ItemID.YOUNG_IMPLING_JAR),
	GOURMET_IMPLING(Type.IMPLING_JAR, true, "Gourmet", "G", ItemID.GOURMET_IMPLING_JAR),
	EARTH_IMPLING(Type.IMPLING_JAR, true, "Earth", "EAR", ItemID.EARTH_IMPLING_JAR),
	ESSENCE_IMPLING(Type.IMPLING_JAR, true, "Essen", "ESS", ItemID.ESSENCE_IMPLING_JAR),
	ECLECTIC_IMPLING(Type.IMPLING_JAR, true, "Eclect", "ECL", ItemID.ECLECTIC_IMPLING_JAR),
	NATURE_IMPLING(Type.IMPLING_JAR, true, "Nature", "NAT", ItemID.NATURE_IMPLING_JAR),
	MAGPIE_IMPLING(Type.IMPLING_JAR, true, "Magpie", "M", ItemID.MAGPIE_IMPLING_JAR),
	NINJA_IMPLING(Type.IMPLING_JAR, true, "Ninja", "NIN", ItemID.NINJA_IMPLING_JAR),
	CRYSTAL_IMPLING(Type.IMPLING_JAR, true, "Crystal", "C", ItemID.CRYSTAL_IMPLING_JAR),
	DRAGON_IMPLING(Type.IMPLING_JAR, true, "Dragon", "D", ItemID.DRAGON_IMPLING_JAR),
	LUCKY_IMPLING(Type.IMPLING_JAR, true, "Lucky", "L", ItemID.LUCKY_IMPLING_JAR),

	// Tablets
	VARROCK_TELEPORT(Type.TABLET, true, "Varro", "VAR", ItemID.VARROCK_TELEPORT),
	LUMBRIDGE_TELEPORT(Type.TABLET, true, "Lumbr", "LUM", ItemID.LUMBRIDGE_TELEPORT),
	FALADOR_TELEPORT(Type.TABLET, true, "Fala", "FAL", ItemID.FALADOR_TELEPORT),
	CAMELOT_TELEPORT(Type.TABLET, true, "Cammy", "CAM", ItemID.CAMELOT_TELEPORT),
	ARDOUGNE_TELEPORT(Type.TABLET, true, "Ardoug", "ARD", ItemID.ARDOUGNE_TELEPORT),
	WATCHTOWER_TELEPORT(Type.TABLET, true, "W.tow", "WT", ItemID.WATCHTOWER_TELEPORT),
	TELEPORT_TO_HOUSE(Type.TABLET, true, "House", "POH", ItemID.TELEPORT_TO_HOUSE),

	ENCHANT_SAPPHIRE_OR_OPAL(Type.TABLET, true, "E.Saph", "E SO", ItemID.ENCHANT_SAPPHIRE_OR_OPAL),
	ENCHANT_EMERALD_OR_JADE(Type.TABLET, true, "E.Emer", "E EJ", ItemID.ENCHANT_EMERALD_OR_JADE),
	ENCHANT_RUBY_OR_TOPAZ(Type.TABLET, true, "E.Ruby", "E RT", ItemID.ENCHANT_RUBY_OR_TOPAZ),
	ENCHANT_DIAMOND(Type.TABLET, true, "E.Diam", "E DIA", ItemID.ENCHANT_DIAMOND),
	ENCHANT_DRAGONSTONE(Type.TABLET, true, "E.Dstn", "E DS", ItemID.ENCHANT_DRAGONSTONE),
	ENCHANT_ONYX(Type.TABLET, true, "E.Onyx", "E ONX", ItemID.ENCHANT_ONYX),

	TELEKINETIC_GRAB(Type.TABLET, true, "T.grab", "T.GRB", ItemID.TELEKINETIC_GRAB),
	BONES_TO_PEACHES(Type.TABLET, true, "Peach", "BtP", ItemID.BONES_TO_PEACHES_8015),
	BONES_TO_BANANAS(Type.TABLET, true, "Banana", "BtB", ItemID.BONES_TO_BANANAS),

	RIMMINGTON_TELEPORT(Type.TABLET, true, "Rimmi", "RIM", ItemID.RIMMINGTON_TELEPORT),
	TAVERLEY_TELEPORT(Type.TABLET, true, "Taver", "TAV", ItemID.TAVERLEY_TELEPORT),
	POLLNIVNEACH_TELEPORT(Type.TABLET, true, "Pollnv", "POL", ItemID.POLLNIVNEACH_TELEPORT),
	RELLEKKA_TELEPORT(Type.TABLET, true, "Rell", "REL", ItemID.RELLEKKA_TELEPORT),
	BRIMHAVEN_TELEPORT(Type.TABLET, true, "Brimh", "BRIM", ItemID.BRIMHAVEN_TELEPORT),
	YANILLE_TELEPORT(Type.TABLET, true, "Yanille", "YAN", ItemID.YANILLE_TELEPORT),
	TROLLHEIM_TELEPORT(Type.TABLET, true, "Trollh", "T.HM", ItemID.TROLLHEIM_TELEPORT),
	PRIFDDINAS_TELEPORT(Type.TABLET, true, "Prifd", "PRIF", ItemID.PRIFDDINAS_TELEPORT),
	HOSIDIUS_TELEPORT(Type.TABLET, true, "Hosid", "HOS", ItemID.HOSIDIUS_TELEPORT),

	ANNAKARL_TELEPORT(Type.TABLET, true, "Annak", "GDZ", ItemID.ANNAKARL_TELEPORT),
	CARRALLANGAR_TELEPORT(Type.TABLET, true, "Carra", "CAR", ItemID.CARRALLANGAR_TELEPORT),
	DAREEYAK_TELEPORT(Type.TABLET, true, "Dareey", "DAR", ItemID.DAREEYAK_TELEPORT),
	GHORROCK_TELEPORT(Type.TABLET, true, "Ghorr", "GHRK", ItemID.GHORROCK_TELEPORT),
	KHARYRLL_TELEPORT(Type.TABLET, true, "Khary", "KHRL", ItemID.KHARYRLL_TELEPORT),
	LASSAR_TELEPORT(Type.TABLET, true, "Lass", "LSR", ItemID.LASSAR_TELEPORT),
	PADDEWWA_TELEPORT(Type.TABLET, true, "Paddew", "PDW", ItemID.PADDEWWA_TELEPORT),
	SENNTISTEN_TELEPORT(Type.TABLET, true, "Sennt", "SNT", ItemID.SENNTISTEN_TELEPORT),

	ARCEUUS_LIBRARY_TELEPORT(Type.TABLET, false, "Arc.Lib", "A.LIB", ItemID.ARCEUUS_LIBRARY_TELEPORT),
	DRAYNOR_MANOR_TELEPORT(Type.TABLET, true, "D.Manor", "D.MNR", ItemID.DRAYNOR_MANOR_TELEPORT),
	MIND_ALTAR_TELEPORT(Type.TABLET, true, "M.Altar", "M.ALT", ItemID.MIND_ALTAR_TELEPORT),
	SALVE_GRAVEYARD_TELEPORT(Type.TABLET, true, "S.Grave", "S.GRV", ItemID.SALVE_GRAVEYARD_TELEPORT),
	FENKENSTRAINS_CASTLE_TELEPORT(Type.TABLET, true, "Fenk", "FNK", ItemID.FENKENSTRAINS_CASTLE_TELEPORT),
	WEST_ARDOUGNE_TELEPORT(Type.TABLET, true, "W.Ardy", "W.ARD", ItemID.WEST_ARDOUGNE_TELEPORT),
	HARMONY_ISLAND_TELEPORT(Type.TABLET, true, "H.Isle", "HRM", ItemID.HARMONY_ISLAND_TELEPORT),
	CEMETERY_TELEPORT(Type.TABLET, true, "Cemet", "CEM", ItemID.CEMETERY_TELEPORT),
	BARROWS_TELEPORT(Type.TABLET, false, "Barrow", "BAR", ItemID.BARROWS_TELEPORT),
	APE_ATOLL_TELEPORT(Type.TABLET, false, "Atoll", "APE", ItemID.APE_ATOLL_TELEPORT),
	BATTLEFRONT_TELEPORT(Type.TABLET, false, "B.Front", "BF", ItemID.BATTLEFRONT_TELEPORT),

	MOONCLAN_TELEPORT(Type.TABLET, false, "Moon", "MOON", ItemID.MOONCLAN_TELEPORT),
	OURANIA_TELEPORT(Type.TABLET, false, "Ourania", "ZMI", ItemID.OURANIA_TELEPORT),
	WATERBIRTH_TELEPORT(Type.TABLET, false, "W.Birth", "WAT", ItemID.WATERBIRTH_TELEPORT),
	BARBARIAN_TELEPORT(Type.TABLET, false, "Barb", "BARB", ItemID.BARBARIAN_TELEPORT),
	KHAZARD_TELEPORT(Type.TABLET, false, "Khaz", "KHA", ItemID.KHAZARD_TELEPORT),
	FISHING_GUILD_TELEPORT(Type.TABLET, false, "Fish G.", "FIS", ItemID.FISHING_GUILD_TELEPORT),
	CATHERBY_TELEPORT(Type.TABLET, false, "Cathy", "CATH", ItemID.CATHERBY_TELEPORT),
	ICE_PLATEAU(Type.TABLET, false, "Ice Pl.", "ICE", ItemID.ICE_PLATEAU_TELEPORT),

	TARGET_TELEPORT(Type.TABLET, true, "Target", "TRG", ItemID.TARGET_TELEPORT),
	VOLCANIC_MINE_TELEPORT(Type.TABLET, true, "V.Mine", "VM", ItemID.VOLCANIC_MINE_TELEPORT),
	WILDERNESS_CRABS_TELEPORT(Type.TABLET, true, "W.Crab", "CRAB", ItemID.WILDERNESS_CRABS_TELEPORT),

	// Scrolls
	NARDAH_TELEPORT(Type.SCROLL, false, "Nardah", "NAR", ItemID.NARDAH_TELEPORT),
	DIGSITE_TELEPORT(Type.SCROLL, false, "Digsite", "DIG", ItemID.DIGSITE_TELEPORT),
	FELDIP_HILLS_TELEPORT(Type.SCROLL, false, "F.Hills", "F.H", ItemID.FELDIP_HILLS_TELEPORT),
	LUNAR_ISLE_TELEPORT(Type.SCROLL, false, "L.Isle", "L.I", ItemID.LUNAR_ISLE_TELEPORT),
	MORTTON_TELEPORT(Type.SCROLL, false, "Mort'ton", "MORT", ItemID.MORTTON_TELEPORT),
	PEST_CONTROL_TELEPORT(Type.SCROLL, false, "P.Cont", "PEST", ItemID.PEST_CONTROL_TELEPORT),
	PISCATORIS_TELEPORT(Type.SCROLL, false, "Pisca", "PISC", ItemID.PISCATORIS_TELEPORT),
	TAI_BWO_WANNAI_TELEPORT(Type.SCROLL, false, "TaiBwo", "TAI", ItemID.TAI_BWO_WANNAI_TELEPORT),
	IORWERTH_CAMP_TELEPORT(Type.SCROLL, false, "Iorwerth", "IOR", ItemID.IORWERTH_CAMP_TELEPORT),
	MOS_LEHARMLESS_TELEPORT(Type.SCROLL, false, "M.LeHarm", "M.L", ItemID.MOS_LEHARMLESS_TELEPORT),
	LUMBERYARD_TELEPORT(Type.SCROLL, false, "Lumber", "LUMB", ItemID.LUMBERYARD_TELEPORT),

	ZUL_ANDRA_TELEPORT(Type.SCROLL, true, "Zul-andra", "ZUL", ItemID.ZULANDRA_TELEPORT),
	KEY_MASTER_TELEPORT(Type.SCROLL, true, "Key master", "KEY", ItemID.KEY_MASTER_TELEPORT),
	REVENANT_CAVE_TELEPORT(Type.SCROLL, true, "Rev cave", "REV", ItemID.REVENANT_CAVE_TELEPORT),
	WATSON_TELEPORT(Type.SCROLL, false, "Watson", "WATS", ItemID.WATSON_TELEPORT);

	final Type type;
	final boolean isIconUnique;
	final String medName;
	final String shortName;
	final int[] itemIDs;

	ItemIdentification(Type type, boolean isIconUnique, String medName, String shortName, int... ids)
	{
		this.type = type;
		this.isIconUnique = isIconUnique;
		this.medName = medName;
		this.shortName = shortName;
		this.itemIDs = ids;
	}

	private static final Map<Integer, ItemIdentification> itemIdentifications;

	static
	{
		ImmutableMap.Builder<Integer, ItemIdentification> builder = new ImmutableMap.Builder<>();

		for (ItemIdentification i : values())
		{
			for (int id : i.itemIDs)
			{
				builder.put(id, i);
			}
		}

		itemIdentifications = builder.build();
	}

	static ItemIdentification get(int id)
	{
		return itemIdentifications.get(id);
	}

	@AllArgsConstructor
	enum Type
	{
		SEED(ItemIdentificationConfig::showSeeds),
		SACK(ItemIdentificationConfig::showSacks),
		HERB(ItemIdentificationConfig::showHerbs),
		LOGS(ItemIdentificationConfig::showLogs),
		PLANK(ItemIdentificationConfig::showPlanks),
		SAPLING(ItemIdentificationConfig::showSaplings),
		COMPOST(ItemIdentificationConfig::showComposts),
		ORE(ItemIdentificationConfig::showOres),
		BAR(ItemIdentificationConfig::showBars),
		GEM(ItemIdentificationConfig::showGems),
		POTION(ItemIdentificationConfig::showPotions),
		IMPLING_JAR(ItemIdentificationConfig::showImplingJars),
		TABLET(ItemIdentificationConfig::showTablets),
		SCROLL(ItemIdentificationConfig::showTeleportScrolls);

		final Predicate<ItemIdentificationConfig> enabled;
	}
}
