package net.runelite.client.plugins.raids3.PalmRoom;

public enum PalmTreeTasks {
  Retrieve_Water_Container,
  WATERFALL1_ENTRANCE_TILE,
  WATERFALL1_FILL_WATER,
  LEAVE_WATERFALL1,
  WATER_PALM_TREE1,
  WATERFALL2_ENTRANCE_TILE,
  WATERFALL2_FILL_WATER,
  LEAVE_WATERFALL2,
  WATER_PALM_TREE2,
  Enter_Gate,
  WATERFALL1_CLICK,
  WATERFALL2_CLICK,
  CLICK_PALM,
  COMPLETE;
}