/*
 * This file is generated by jOOQ.
 */
package net.runelite.client.database.data;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.annotation.Generated;
import net.runelite.client.database.data.tables.Loottrackerevents;
import net.runelite.client.database.data.tables.Loottrackerlink;
import net.runelite.client.database.data.tables.Loottrackerloot;
import net.runelite.client.database.data.tables.User;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.11.12"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Public extends SchemaImpl
{

	private static final long serialVersionUID = 1499404561;

	/**
	 * The reference instance of <code>PUBLIC</code>
	 */
	public static final Public PUBLIC = new Public();

	/**
	 * The table <code>PUBLIC.LOOTTRACKEREVENTS</code>.
	 */
	public final Loottrackerevents LOOTTRACKEREVENTS = net.runelite.client.database.data.tables.Loottrackerevents.LOOTTRACKEREVENTS;

	/**
	 * The table <code>PUBLIC.LOOTTRACKERLINK</code>.
	 */
	public final Loottrackerlink LOOTTRACKERLINK = net.runelite.client.database.data.tables.Loottrackerlink.LOOTTRACKERLINK;

	/**
	 * The table <code>PUBLIC.LOOTTRACKERLOOT</code>.
	 */
	public final Loottrackerloot LOOTTRACKERLOOT = net.runelite.client.database.data.tables.Loottrackerloot.LOOTTRACKERLOOT;

	/**
	 * The table <code>PUBLIC.USER</code>.
	 */
	public final User USER = net.runelite.client.database.data.tables.User.USER;

	/**
	 * No further instances allowed
	 */
	private Public()
	{
		super("PUBLIC", null);
	}


	/**
	 * {@inheritDoc}
	 */
	@Override
	public Catalog getCatalog()
	{
		return DefaultCatalog.DEFAULT_CATALOG;
	}

	@Override
	public final List<Table<?>> getTables()
	{
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0()
	{
		return Arrays.<Table<?>>asList(
			Loottrackerevents.LOOTTRACKEREVENTS,
			Loottrackerlink.LOOTTRACKERLINK,
			Loottrackerloot.LOOTTRACKERLOOT,
			User.USER);
	}
}
