/*
 * This file is generated by jOOQ.
 */
package net.runelite.client.database.data;


import javax.annotation.processing.Generated;
import net.runelite.client.database.data.tables.Loottrackerevents;
import net.runelite.client.database.data.tables.Loottrackerlink;
import net.runelite.client.database.data.tables.Loottrackerloot;
import net.runelite.client.database.data.tables.TmorphSets;
import net.runelite.client.database.data.tables.User;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.12.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables
{

	/**
	 * The table <code>PUBLIC.LOOTTRACKEREVENTS</code>.
	 */
	public static final Loottrackerevents LOOTTRACKEREVENTS = Loottrackerevents.LOOTTRACKEREVENTS;

	/**
	 * The table <code>PUBLIC.LOOTTRACKERLINK</code>.
	 */
	public static final Loottrackerlink LOOTTRACKERLINK = Loottrackerlink.LOOTTRACKERLINK;

	/**
	 * The table <code>PUBLIC.LOOTTRACKERLOOT</code>.
	 */
	public static final Loottrackerloot LOOTTRACKERLOOT = Loottrackerloot.LOOTTRACKERLOOT;

	/**
	 * The table <code>PUBLIC.TMORPH_SETS</code>.
	 */
	public static final TmorphSets TMORPH_SETS = TmorphSets.TMORPH_SETS;

	/**
	 * The table <code>PUBLIC.USER</code>.
	 */
	public static final User USER = User.USER;
}
