package net.runelite.deob.deobfuscators.rename.graph;

public enum EdgeType
{
	INVOKE,
	GETFIELD,
	SETFIELD,
	
	INVOKED_FROM,
	GETFIELD_FROM,
	SETFIELD_FROM,
	
	FIELD_ASSOCIATION,
	FIELD_ASSOCIATION_FROM,
	
	METHOD_ASSOCIATION,
	METHOD_ASSOCIATION_FROM,
	
	PREV_FIELD,
	PREV_FIELD_FROM,
	
	FIELD_ASSIGNMENT_FIELD,
	FIELD_ASSIGNMENT_FIELD_FROM;
}
